//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSCoordinatorLayoutPlugin\src\main\java\com\ashera\coordinatorlayout\CoordinatorLayoutImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_CoordinatorLayoutImpl")
#ifdef RESTRICT_CoordinatorLayoutImpl
#define INCLUDE_ALL_CoordinatorLayoutImpl 0
#else
#define INCLUDE_ALL_CoordinatorLayoutImpl 1
#endif
#undef RESTRICT_CoordinatorLayoutImpl

#if !defined (ASCoordinatorLayoutImpl_) && (INCLUDE_ALL_CoordinatorLayoutImpl || defined(INCLUDE_ASCoordinatorLayoutImpl))
#define ASCoordinatorLayoutImpl_

#define RESTRICT_BaseHasWidgets 1
#define INCLUDE_ASBaseHasWidgets 1
#include "BaseHasWidgets.h"

@class ASCoordinatorLayoutImpl_CoordinatorLayoutBean;
@class ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder;
@class ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder;
@class ASCoordinatorLayoutImpl_CoordinatorLayoutParamsBean;
@class ASWidgetAttribute;
@class IOSClass;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASCoordinatorLayoutImpl : ASBaseHasWidgets
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)localname;

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname;

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(jint)index;

- (id)asNativeWidget;

- (id)asWidget;

- (jboolean)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutBean *)getBean;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)getBuilder;

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutParamsBean *)getParamsBean;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *)getParamsBuilder;

- (id)getPluginWithNSString:(NSString *)plugin;

- (IOSClass *)getViewClass;

- (void)invalidate;

- (void)loadAttributesWithNSString:(NSString *)localName;

- (void)nativeCreateWithJavaUtilMap:(id<JavaUtilMap>)params;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (jboolean)removeWithInt:(jint)index;

- (jboolean)removeWithASIWidget:(id<ASIWidget>)w;

- (void)requestLayout;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setVisibleWithBoolean:(jboolean)b;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCoordinatorLayoutImpl)

inline NSString *ASCoordinatorLayoutImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASCoordinatorLayoutImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASCoordinatorLayoutImpl, LOCAL_NAME, NSString *)

inline NSString *ASCoordinatorLayoutImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASCoordinatorLayoutImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASCoordinatorLayoutImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASCoordinatorLayoutImpl_init(ASCoordinatorLayoutImpl *self);

FOUNDATION_EXPORT ASCoordinatorLayoutImpl *new_ASCoordinatorLayoutImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCoordinatorLayoutImpl *create_ASCoordinatorLayoutImpl_init(void);

FOUNDATION_EXPORT void ASCoordinatorLayoutImpl_initWithNSString_(ASCoordinatorLayoutImpl *self, NSString *localname);

FOUNDATION_EXPORT ASCoordinatorLayoutImpl *new_ASCoordinatorLayoutImpl_initWithNSString_(NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCoordinatorLayoutImpl *create_ASCoordinatorLayoutImpl_initWithNSString_(NSString *localname);

FOUNDATION_EXPORT void ASCoordinatorLayoutImpl_initWithNSString_withNSString_(ASCoordinatorLayoutImpl *self, NSString *groupName, NSString *localname);

FOUNDATION_EXPORT ASCoordinatorLayoutImpl *new_ASCoordinatorLayoutImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCoordinatorLayoutImpl *create_ASCoordinatorLayoutImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname);

J2OBJC_TYPE_LITERAL_HEADER(ASCoordinatorLayoutImpl)

@compatibility_alias ComAsheraCoordinatorlayoutCoordinatorLayoutImpl ASCoordinatorLayoutImpl;

#endif

#if !defined (ASCoordinatorLayoutImpl_InsetEdge_) && (INCLUDE_ALL_CoordinatorLayoutImpl || defined(INCLUDE_ASCoordinatorLayoutImpl_InsetEdge))
#define ASCoordinatorLayoutImpl_InsetEdge_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASCoordinatorLayoutImpl_InsetEdge : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCoordinatorLayoutImpl_InsetEdge)

FOUNDATION_EXPORT void ASCoordinatorLayoutImpl_InsetEdge_init(ASCoordinatorLayoutImpl_InsetEdge *self);

FOUNDATION_EXPORT ASCoordinatorLayoutImpl_InsetEdge *new_ASCoordinatorLayoutImpl_InsetEdge_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCoordinatorLayoutImpl_InsetEdge *create_ASCoordinatorLayoutImpl_InsetEdge_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASCoordinatorLayoutImpl_InsetEdge)

#endif

#if !defined (ASCoordinatorLayoutImpl_DodgeInsetEdge_) && (INCLUDE_ALL_CoordinatorLayoutImpl || defined(INCLUDE_ASCoordinatorLayoutImpl_DodgeInsetEdge))
#define ASCoordinatorLayoutImpl_DodgeInsetEdge_

#define RESTRICT_AbstractBitFlagConverter 1
#define INCLUDE_ASAbstractBitFlagConverter 1
#include "AbstractBitFlagConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASCoordinatorLayoutImpl_DodgeInsetEdge : ASAbstractBitFlagConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCoordinatorLayoutImpl_DodgeInsetEdge)

FOUNDATION_EXPORT void ASCoordinatorLayoutImpl_DodgeInsetEdge_init(ASCoordinatorLayoutImpl_DodgeInsetEdge *self);

FOUNDATION_EXPORT ASCoordinatorLayoutImpl_DodgeInsetEdge *new_ASCoordinatorLayoutImpl_DodgeInsetEdge_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCoordinatorLayoutImpl_DodgeInsetEdge *create_ASCoordinatorLayoutImpl_DodgeInsetEdge_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASCoordinatorLayoutImpl_DodgeInsetEdge)

#endif

#if !defined (ASCoordinatorLayoutImpl_CoordinatorLayoutExt_) && (INCLUDE_ALL_CoordinatorLayoutImpl || defined(INCLUDE_ASCoordinatorLayoutImpl_CoordinatorLayoutExt))
#define ASCoordinatorLayoutImpl_CoordinatorLayoutExt_

#define RESTRICT_CoordinatorLayout 1
#define INCLUDE_ADXCoordinatorLayout 1
#include "CoordinatorLayout.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

#define RESTRICT_IMaxDimension 1
#define INCLUDE_ASIMaxDimension 1
#include "IMaxDimension.h"

@class ADRect;
@class ADView;
@class ASCoordinatorLayoutImpl;
@class ASWidgetAttribute;
@class IOSIntArray;
@class IOSObjectArray;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASCoordinatorLayoutImpl_CoordinatorLayoutExt : ADXCoordinatorLayout < ASILifeCycleDecorator, ASIMaxDimension >

#pragma mark Public

- (instancetype)initWithASCoordinatorLayoutImpl:(ASCoordinatorLayoutImpl *)outer$;

- (void)drawableStateChanged;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation;

- (jint)getMaxHeight;

- (jint)getMaxWidth;

- (id<JavaUtilList>)getMethods;

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(jint)offset;

- (void)offsetTopAndBottomWithInt:(jint)offset;

- (void)onLayoutChildWithADView:(ADView *)child
                        withInt:(jint)layoutDirection;

- (void)onMeasureWithInt:(jint)widthMeasureSpec
                 withInt:(jint)heightMeasureSpec;

- (void)remeasure;

- (void)removeFromParent;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setMaxHeightWithInt:(jint)height;

- (void)setMaxWidthWithInt:(jint)width;

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value;

- (void)setVisibilityWithInt:(jint)visibility;

- (void)updateMeasuredDimensionWithInt:(jint)width
                               withInt:(jint)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(jboolean)changed
                    withInt:(jint)l
                    withInt:(jint)t
                    withInt:(jint)r
                    withInt:(jint)b;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCoordinatorLayoutImpl_CoordinatorLayoutExt)

FOUNDATION_EXPORT void ASCoordinatorLayoutImpl_CoordinatorLayoutExt_initWithASCoordinatorLayoutImpl_(ASCoordinatorLayoutImpl_CoordinatorLayoutExt *self, ASCoordinatorLayoutImpl *outer$);

FOUNDATION_EXPORT ASCoordinatorLayoutImpl_CoordinatorLayoutExt *new_ASCoordinatorLayoutImpl_CoordinatorLayoutExt_initWithASCoordinatorLayoutImpl_(ASCoordinatorLayoutImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCoordinatorLayoutImpl_CoordinatorLayoutExt *create_ASCoordinatorLayoutImpl_CoordinatorLayoutExt_initWithASCoordinatorLayoutImpl_(ASCoordinatorLayoutImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASCoordinatorLayoutImpl_CoordinatorLayoutExt)

#endif

#if !defined (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder_) && (INCLUDE_ALL_CoordinatorLayoutImpl || defined(INCLUDE_ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder))
#define ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupCommandBuilder 1
#include "ViewGroupImpl.h"

@class ASCoordinatorLayoutImpl;

@interface ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder : ASViewGroupImpl_ViewGroupCommandBuilder

#pragma mark Public

- (instancetype)initWithASCoordinatorLayoutImpl:(ASCoordinatorLayoutImpl *)outer$;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)addAllModelWithId:(id)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)addModelByIndexWithId:(id)arg0
                                                                            withId:(id)arg1;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)addModelWithId:(id)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)executeWithBoolean:(jboolean)setter;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)invalidate;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)notifyDataSetChangedWithBoolean:(jboolean)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)refreshUiFromModelWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)removeModelAtIndexWithInt:(jint)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)removeModelByIdWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)requestLayout;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)reset;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setAddStatesFromChildrenWithBoolean:(jboolean)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setAlphaWithFloat:(jfloat)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setAsDragSourceWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setAttributeUnderTestWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setBackgroundRepeatWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setBackgroundTintModeWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setBackgroundTintWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setBackgroundWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setChildXmlWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setClickableWithBoolean:(jboolean)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setClipChildrenWithBoolean:(jboolean)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setClipToPaddingWithBoolean:(jboolean)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setContentDescriptionWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setCustomErrorMessageKeysWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setCustomErrorMessageValuesWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setDuplicateParentStateWithBoolean:(jboolean)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setEnabledWithBoolean:(jboolean)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setErrorStyleWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setFocusableWithBoolean:(jboolean)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setForegroundGravityWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setForegroundRepeatWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setForegroundTintModeWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setForegroundTintWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setForegroundWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setIdWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setInvalidateOnFrameChangeWithBoolean:(jboolean)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setIosAccessibilityHintWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setIosAccessibilityIgnoresInvertColorsWithBoolean:(jboolean)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setIosAccessibilityLabelWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setIosAccessibilityTraitsWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setIosAccessibilityValueWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setIosAlphaWithFloat:(jfloat)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setIosAutoresizesSubviewsWithBoolean:(jboolean)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setIosBackgroundColorWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setIosClearsContextBeforeDrawingWithBoolean:(jboolean)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setIosClipsToBoundsWithBoolean:(jboolean)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setIosContentScaleFactorWithFloat:(jfloat)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setIosInsetsLayoutMarginsFromSafeAreaWithBoolean:(jboolean)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setIosIsAccessibilityElementWithBoolean:(jboolean)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setIosIsExclusiveTouchWithBoolean:(jboolean)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setIosIsHiddenWithBoolean:(jboolean)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setIosIsMultipleTouchEnabledWithBoolean:(jboolean)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setIosIsOpaqueWithBoolean:(jboolean)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setIosIsUserInteractionEnabledWithBoolean:(jboolean)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setIosLargeContentImageWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setIosLargeContentTitleWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setIosLayerBorderColorWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setIosLayerBorderWidthWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setIosLayerCornerRadiusWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setIosLayerMasksToBoundsWithBoolean:(jboolean)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setIosPreservesSuperviewLayoutMarginsWithBoolean:(jboolean)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setIosRestorationIdentifierWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setIosScalesLargeContentImageWithBoolean:(jboolean)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setIosShowsLargeContentViewerWithBoolean:(jboolean)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setIosTagWithInt:(jint)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setIosTintColorWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setIosTranslatesAutoresizingMaskIntoConstraintsWithBoolean:(jboolean)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setKeepScreenOnWithBoolean:(jboolean)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setKeylinesWithNSString:(NSString *)value;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setLayoutDirectionWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setLayoutModeWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setListitemWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setLongClickableWithBoolean:(jboolean)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setMaxHeightWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setMaxWidthWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setMinHeightWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setMinWidthWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setModelDescPathWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setModelForWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setModelIdPathWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setModelParamWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setModelPojoToUiParamsWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setModelPojoToUiWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setModelSyncEventsWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setModelUiToPojoEventIdsWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setModelUiToPojoWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setOnChildViewAddedWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setOnChildViewRemovedWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setOnClickWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setOnDragWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setOnKeyWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setOnLongClickWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setOnSwipedWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setOnTouchWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setOutsideTouchableWithBoolean:(jboolean)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setPaddingBottomWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setPaddingEndWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setPaddingHorizontalWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setPaddingLeftWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setPaddingRightWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setPaddingStartWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setPaddingTopWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setPaddingVerticalWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setPaddingWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setRotationWithFloat:(jfloat)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setRotationXWithFloat:(jfloat)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setRotationYWithFloat:(jfloat)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setScaleXWithFloat:(jfloat)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setScaleYWithFloat:(jfloat)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setSelectedWithBoolean:(jboolean)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setStyleWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setTextAlignmentWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setTextDirectionWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setTransformPivotXWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setTransformPivotYWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setTranslationXWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setTranslationYWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setTranslationZWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setV_maxlengthWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setV_maxWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setV_minlengthWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setV_minWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setV_patternWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setV_requiredWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setV_typeWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setValidationErrorDisplayTypeWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setValidationWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setVisibilityWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setZIndexWithInt:(jint)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetAddStatesFromChildren;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetAlpha;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetBackground;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetBackgroundTint;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetBackgroundTintMode;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetClickable;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetClipChildren;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetClipToPadding;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetContentDescription;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetDuplicateParentState;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetEnabled;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetFocusable;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetForeground;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetForegroundGravity;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetForegroundTint;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetForegroundTintMode;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetId;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetIosAccessibilityHint;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetIosAccessibilityIgnoresInvertColors;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetIosAccessibilityLabel;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetIosAccessibilityTraits;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetIosAccessibilityValue;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetIosAlpha;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetIosAutoresizesSubviews;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetIosBackgroundColor;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetIosClearsContextBeforeDrawing;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetIosClipsToBounds;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetIosContentScaleFactor;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetIosInsetsLayoutMarginsFromSafeArea;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetIosIsAccessibilityElement;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetIosIsExclusiveTouch;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetIosIsFocused;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetIosIsHidden;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetIosIsMultipleTouchEnabled;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetIosIsOpaque;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetIosIsUserInteractionEnabled;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetIosLargeContentImage;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetIosLargeContentTitle;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetIosPreservesSuperviewLayoutMargins;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetIosRestorationIdentifier;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetIosScalesLargeContentImage;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetIosShowsLargeContentViewer;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetIosTag;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetIosTintColor;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetIosTranslatesAutoresizingMaskIntoConstraints;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetKeepScreenOn;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetLayoutDirection;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetLayoutMode;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetLongClickable;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetMaxHeight;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetMaxWidth;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetMinHeight;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetMinWidth;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetModelDescPath;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetModelIdPath;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetModelParam;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetModelPojoToUi;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetModelSyncEvents;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetModelUiToPojo;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetPaddingBottom;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetPaddingEnd;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetPaddingLeft;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetPaddingRight;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetPaddingStart;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetPaddingTop;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetRotation;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetRotationX;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetRotationY;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetScaleX;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetScaleY;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetSelected;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetTextAlignment;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetTextDirection;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetTransformPivotX;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetTransformPivotY;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetTranslationX;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetTranslationY;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetTranslationZ;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetValidateForm;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)tryGetVisibility;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)updateModelDataWithNSString:(NSString *)arg0
                                                                                  withId:(id)arg1;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)validateFormWithNSString:(NSString *)arg0;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder)

FOUNDATION_EXPORT void ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder_initWithASCoordinatorLayoutImpl_(ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *self, ASCoordinatorLayoutImpl *outer$);

FOUNDATION_EXPORT ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *new_ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder_initWithASCoordinatorLayoutImpl_(ASCoordinatorLayoutImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *create_ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder_initWithASCoordinatorLayoutImpl_(ASCoordinatorLayoutImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder)

#endif

#if !defined (ASCoordinatorLayoutImpl_CoordinatorLayoutBean_) && (INCLUDE_ALL_CoordinatorLayoutImpl || defined(INCLUDE_ASCoordinatorLayoutImpl_CoordinatorLayoutBean))
#define ASCoordinatorLayoutImpl_CoordinatorLayoutBean_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupBean 1
#include "ViewGroupImpl.h"

@class ASCoordinatorLayoutImpl;
@protocol ASIWidget;

@interface ASCoordinatorLayoutImpl_CoordinatorLayoutBean : ASViewGroupImpl_ViewGroupBean

#pragma mark Public

- (instancetype)initWithASCoordinatorLayoutImpl:(ASCoordinatorLayoutImpl *)outer$;

- (void)setKeylinesWithNSString:(NSString *)value;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithASIWidget:(id<ASIWidget>)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCoordinatorLayoutImpl_CoordinatorLayoutBean)

FOUNDATION_EXPORT void ASCoordinatorLayoutImpl_CoordinatorLayoutBean_initWithASCoordinatorLayoutImpl_(ASCoordinatorLayoutImpl_CoordinatorLayoutBean *self, ASCoordinatorLayoutImpl *outer$);

FOUNDATION_EXPORT ASCoordinatorLayoutImpl_CoordinatorLayoutBean *new_ASCoordinatorLayoutImpl_CoordinatorLayoutBean_initWithASCoordinatorLayoutImpl_(ASCoordinatorLayoutImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCoordinatorLayoutImpl_CoordinatorLayoutBean *create_ASCoordinatorLayoutImpl_CoordinatorLayoutBean_initWithASCoordinatorLayoutImpl_(ASCoordinatorLayoutImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASCoordinatorLayoutImpl_CoordinatorLayoutBean)

#endif

#if !defined (ASCoordinatorLayoutImpl_CoordinatorLayoutParamsBean_) && (INCLUDE_ALL_CoordinatorLayoutImpl || defined(INCLUDE_ASCoordinatorLayoutImpl_CoordinatorLayoutParamsBean))
#define ASCoordinatorLayoutImpl_CoordinatorLayoutParamsBean_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupParamsBean 1
#include "ViewGroupImpl.h"

@class ASCoordinatorLayoutImpl;
@protocol ASIWidget;

@interface ASCoordinatorLayoutImpl_CoordinatorLayoutParamsBean : ASViewGroupImpl_ViewGroupParamsBean

#pragma mark Public

- (instancetype)initWithASCoordinatorLayoutImpl:(ASCoordinatorLayoutImpl *)outer$;

- (id)getLayoutAnchorWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutAnchorGravityWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutDodgeInsetEdgesWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutGravityWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutInsetEdgeWithASIWidget:(id<ASIWidget>)w;

- (id)getLayoutKeylineWithASIWidget:(id<ASIWidget>)w;

- (void)setLayoutAnchorWithASIWidget:(id<ASIWidget>)w
                        withNSString:(NSString *)value;

- (void)setLayoutAnchorGravityWithASIWidget:(id<ASIWidget>)w
                               withNSString:(NSString *)value;

- (void)setLayoutBehaviorWithASIWidget:(id<ASIWidget>)w
                          withNSString:(NSString *)value;

- (void)setLayoutDodgeInsetEdgesWithASIWidget:(id<ASIWidget>)w
                                 withNSString:(NSString *)value;

- (void)setLayoutGravityWithASIWidget:(id<ASIWidget>)w
                         withNSString:(NSString *)value;

- (void)setLayoutInsetEdgeWithASIWidget:(id<ASIWidget>)w
                           withNSString:(NSString *)value;

- (void)setLayoutKeylineWithASIWidget:(id<ASIWidget>)w
                              withInt:(jint)value;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCoordinatorLayoutImpl_CoordinatorLayoutParamsBean)

FOUNDATION_EXPORT void ASCoordinatorLayoutImpl_CoordinatorLayoutParamsBean_initWithASCoordinatorLayoutImpl_(ASCoordinatorLayoutImpl_CoordinatorLayoutParamsBean *self, ASCoordinatorLayoutImpl *outer$);

FOUNDATION_EXPORT ASCoordinatorLayoutImpl_CoordinatorLayoutParamsBean *new_ASCoordinatorLayoutImpl_CoordinatorLayoutParamsBean_initWithASCoordinatorLayoutImpl_(ASCoordinatorLayoutImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCoordinatorLayoutImpl_CoordinatorLayoutParamsBean *create_ASCoordinatorLayoutImpl_CoordinatorLayoutParamsBean_initWithASCoordinatorLayoutImpl_(ASCoordinatorLayoutImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASCoordinatorLayoutImpl_CoordinatorLayoutParamsBean)

#endif

#if !defined (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder_) && (INCLUDE_ALL_CoordinatorLayoutImpl || defined(INCLUDE_ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder))
#define ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupCommandParamsBuilder 1
#include "ViewGroupImpl.h"

@class ASCoordinatorLayoutImpl;

@interface ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder : ASViewGroupImpl_ViewGroupCommandParamsBuilder

#pragma mark Public

- (instancetype)initWithASCoordinatorLayoutImpl:(ASCoordinatorLayoutImpl *)outer$;

- (id)getLayoutAnchor;

- (id)getLayoutAnchorGravity;

- (id)getLayoutDodgeInsetEdges;

- (id)getLayoutGravity;

- (id)getLayoutInsetEdge;

- (id)getLayoutKeyline;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *)reset;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *)setLayoutAnchorWithNSString:(NSString *)value;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *)setLayoutAnchorGravityWithNSString:(NSString *)value;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *)setLayoutBehaviorWithNSString:(NSString *)value;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *)setLayoutDodgeInsetEdgesWithNSString:(NSString *)value;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *)setLayoutGravityWithNSString:(NSString *)value;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *)setLayoutInsetEdgeWithNSString:(NSString *)value;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *)setLayoutKeylineWithInt:(jint)value;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *)setLayoutMarginBottomWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *)setLayoutMarginEndWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *)setLayoutMarginHorizontalWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *)setLayoutMarginLeftWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *)setLayoutMarginRightWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *)setLayoutMarginStartWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *)setLayoutMarginTopWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *)setLayoutMarginVerticalWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *)setLayoutMarginWithNSString:(NSString *)arg0;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *)tryGetLayoutAnchor;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *)tryGetLayoutAnchorGravity;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *)tryGetLayoutDodgeInsetEdges;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *)tryGetLayoutGravity;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *)tryGetLayoutInsetEdge;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *)tryGetLayoutKeyline;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *)tryGetLayoutMarginBottom;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *)tryGetLayoutMarginEnd;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *)tryGetLayoutMarginLeft;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *)tryGetLayoutMarginRight;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *)tryGetLayoutMarginStart;

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *)tryGetLayoutMarginTop;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder)

FOUNDATION_EXPORT void ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder_initWithASCoordinatorLayoutImpl_(ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *self, ASCoordinatorLayoutImpl *outer$);

FOUNDATION_EXPORT ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *new_ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder_initWithASCoordinatorLayoutImpl_(ASCoordinatorLayoutImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *create_ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder_initWithASCoordinatorLayoutImpl_(ASCoordinatorLayoutImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder)

#endif

#pragma pop_macro("INCLUDE_ALL_CoordinatorLayoutImpl")
