//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSCoordinatorLayoutPlugin\src\main\java\com\ashera\coordinatorlayout\CoordinatorLayoutImpl.java
//

#include "AbstractBitFlagConverter.h"
#include "AbstractEnumToIntConverter.h"
#include "BaseHasWidgets.h"
#include "Context.h"
#include "ConverterFactory.h"
#include "CoordinatorLayout.h"
#include "CoordinatorLayoutImpl.h"
#include "DisplayMetrics.h"
#include "HasWidgets.h"
#include "IAttributable.h"
#include "IFragment.h"
#include "ILifeCycleDecorator.h"
#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "IOSPrimitiveArray.h"
#include "IWidget.h"
#include "IWidgetLifeCycleListener.h"
#include "J2ObjC_source.h"
#include "MeasureEvent.h"
#include "OnLayoutEvent.h"
#include "Rect.h"
#include "Resources.h"
#include "View.h"
#include "ViewGroup.h"
#include "ViewGroupImpl.h"
#include "ViewImpl.h"
#include "WidgetAttribute.h"
#include "WidgetFactory.h"
#include "java/lang/Boolean.h"
#include "java/lang/Integer.h"
#include "java/lang/RuntimeException.h"
#include "java/lang/UnsupportedOperationException.h"
#include "java/util/HashMap.h"
#include "java/util/List.h"
#include "java/util/Map.h"

#include <UIKit/UIKit.h>
#include "ASUIView.h"
#include "HasLifeCycleDecorators.h"

@protocol JavaUtilMap;


#pragma clang diagnostic ignored "-Wincomplete-implementation"

@interface ASCoordinatorLayoutImpl () {
 @public
  id uiView_;
  ADXCoordinatorLayout *coordinatorLayout_;
  ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *builder_;
  ASCoordinatorLayoutImpl_CoordinatorLayoutBean *bean_;
  ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *paramsBuilder_;
  ASCoordinatorLayoutImpl_CoordinatorLayoutParamsBean *paramsBean_;
}

- (void)setWidgetOnNativeClass;

- (void)createLayoutParamsWithADView:(ADView *)view;

- (ADXCoordinatorLayout_LayoutParams *)getLayoutParamsWithADView:(ADView *)view;

- (void)setBehaviorWithADXCoordinatorLayout_LayoutParams:(ADXCoordinatorLayout_LayoutParams *)layoutParams
                                                  withId:(id)objValue;

- (void)setKeyLinesWithId:(id)objValue;

- (void)setMyKeyLinesWithIntArray:(IOSIntArray *)keyLines;

@end

J2OBJC_FIELD_SETTER(ASCoordinatorLayoutImpl, uiView_, id)
J2OBJC_FIELD_SETTER(ASCoordinatorLayoutImpl, coordinatorLayout_, ADXCoordinatorLayout *)
J2OBJC_FIELD_SETTER(ASCoordinatorLayoutImpl, builder_, ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)
J2OBJC_FIELD_SETTER(ASCoordinatorLayoutImpl, bean_, ASCoordinatorLayoutImpl_CoordinatorLayoutBean *)
J2OBJC_FIELD_SETTER(ASCoordinatorLayoutImpl, paramsBuilder_, ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *)
J2OBJC_FIELD_SETTER(ASCoordinatorLayoutImpl, paramsBean_, ASCoordinatorLayoutImpl_CoordinatorLayoutParamsBean *)

__attribute__((unused)) static void ASCoordinatorLayoutImpl_setWidgetOnNativeClass(ASCoordinatorLayoutImpl *self);

__attribute__((unused)) static void ASCoordinatorLayoutImpl_createLayoutParamsWithADView_(ASCoordinatorLayoutImpl *self, ADView *view);

__attribute__((unused)) static ADXCoordinatorLayout_LayoutParams *ASCoordinatorLayoutImpl_getLayoutParamsWithADView_(ASCoordinatorLayoutImpl *self, ADView *view);

__attribute__((unused)) static void ASCoordinatorLayoutImpl_setBehaviorWithADXCoordinatorLayout_LayoutParams_withId_(ASCoordinatorLayoutImpl *self, ADXCoordinatorLayout_LayoutParams *layoutParams, id objValue);

__attribute__((unused)) static void ASCoordinatorLayoutImpl_setKeyLinesWithId_(ASCoordinatorLayoutImpl *self, id objValue);

__attribute__((unused)) static void ASCoordinatorLayoutImpl_setMyKeyLinesWithIntArray_(ASCoordinatorLayoutImpl *self, IOSIntArray *keyLines);

@interface ASCoordinatorLayoutImpl_InsetEdge () {
 @public
  id<JavaUtilMap> mapping_;
}

@end

J2OBJC_FIELD_SETTER(ASCoordinatorLayoutImpl_InsetEdge, mapping_, id<JavaUtilMap>)

@interface ASCoordinatorLayoutImpl_DodgeInsetEdge () {
 @public
  id<JavaUtilMap> mapping_;
}

@end

J2OBJC_FIELD_SETTER(ASCoordinatorLayoutImpl_DodgeInsetEdge, mapping_, id<JavaUtilMap>)

@interface ASCoordinatorLayoutImpl_CoordinatorLayoutExt () {
 @public
  __unsafe_unretained ASCoordinatorLayoutImpl *this$0_;
  ASMeasureEvent *measureFinished_;
  ASOnLayoutEvent *onLayoutEvent_;
  jint mMaxWidth_;
  jint mMaxHeight_;
  id<JavaUtilMap> templates_;
}

@end

J2OBJC_FIELD_SETTER(ASCoordinatorLayoutImpl_CoordinatorLayoutExt, measureFinished_, ASMeasureEvent *)
J2OBJC_FIELD_SETTER(ASCoordinatorLayoutImpl_CoordinatorLayoutExt, onLayoutEvent_, ASOnLayoutEvent *)
J2OBJC_FIELD_SETTER(ASCoordinatorLayoutImpl_CoordinatorLayoutExt, templates_, id<JavaUtilMap>)

@interface ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder () {
 @public
  ASCoordinatorLayoutImpl *this$0_;
}

@end

@interface ASCoordinatorLayoutImpl_CoordinatorLayoutBean () {
 @public
  ASCoordinatorLayoutImpl *this$0_;
}

@end

@interface ASCoordinatorLayoutImpl_CoordinatorLayoutParamsBean () {
 @public
  ASCoordinatorLayoutImpl *this$0_;
}

@end

NSString *ASCoordinatorLayoutImpl_LOCAL_NAME = @"androidx.coordinatorlayout.widget.CoordinatorLayout";
NSString *ASCoordinatorLayoutImpl_GROUP_NAME = @"androidx.coordinatorlayout.widget.CoordinatorLayout";

@implementation ASCoordinatorLayoutImpl

@synthesize uiView = uiView_;

- (void)loadAttributesWithNSString:(NSString *)localName {
  ASViewGroupImpl_register__WithNSString_(localName);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"keylines"])) withTypeWithNSString:@"array"])) withArrayTypeWithNSString:@"int"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"layout_gravity"])) withTypeWithNSString:@"gravity"])) forChild]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"layout_behavior"])) withTypeWithNSString:@"string"])) forChild]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"layout_anchor"])) withTypeWithNSString:@"id"])) forChild]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"layout_keyline"])) withTypeWithNSString:@"int"])) forChild]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"layout_anchorGravity"])) withTypeWithNSString:@"gravity"])) forChild]);
  ASConverterFactory_register__WithNSString_withASIConverter_(@"androidx.coordinatorlayout.widget.CoordinatorLayout.insetEdge", new_ASCoordinatorLayoutImpl_InsetEdge_init());
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"layout_insetEdge"])) withTypeWithNSString:@"androidx.coordinatorlayout.widget.CoordinatorLayout.insetEdge"])) forChild]);
  ASConverterFactory_register__WithNSString_withASIConverter_(@"androidx.coordinatorlayout.widget.CoordinatorLayout.dodgeInsetEdge", new_ASCoordinatorLayoutImpl_DodgeInsetEdge_init());
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"layout_dodgeInsetEdges"])) withTypeWithNSString:@"androidx.coordinatorlayout.widget.CoordinatorLayout.dodgeInsetEdge"])) forChild]);
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ASCoordinatorLayoutImpl_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (instancetype)initWithNSString:(NSString *)localname {
  ASCoordinatorLayoutImpl_initWithNSString_(self, localname);
  return self;
}

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname {
  ASCoordinatorLayoutImpl_initWithNSString_withNSString_(self, groupName, localname);
  return self;
}

- (id<ASIWidget>)newInstance {
  return new_ASCoordinatorLayoutImpl_initWithNSString_withNSString_(groupName_, localName_);
}

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params {
  [super createWithASIFragment:fragment withJavaUtilMap:params];
  coordinatorLayout_ = new_ASCoordinatorLayoutImpl_CoordinatorLayoutExt_initWithASCoordinatorLayoutImpl_(self);
  [self nativeCreateWithJavaUtilMap:params];
  ASViewGroupImpl_registerCommandConveterWithASIWidget_(self);
  ASCoordinatorLayoutImpl_setWidgetOnNativeClass(self);
}

- (void)setWidgetOnNativeClass {
  ASCoordinatorLayoutImpl_setWidgetOnNativeClass(self);
}

- (id)asWidget {
  return coordinatorLayout_;
}

- (jboolean)removeWithASIWidget:(id<ASIWidget>)w {
  jboolean remove = [super removeWithASIWidget:w];
  [((ADXCoordinatorLayout *) nil_chk(coordinatorLayout_)) removeViewWithADView:(ADView *) cast_chk([((id<ASIWidget>) nil_chk(w)) asWidget], [ADView class])];
  ASViewGroupImpl_nativeRemoveViewWithASIWidget_(w);
  return remove;
}

- (jboolean)removeWithInt:(jint)index {
  id<ASIWidget> widget = [((id<JavaUtilList>) nil_chk(widgets_)) getWithInt:index];
  jboolean remove = [super removeWithInt:index];
  if (index + 1 <= [((ADXCoordinatorLayout *) nil_chk(coordinatorLayout_)) getChildCount]) {
    [((ADXCoordinatorLayout *) nil_chk(coordinatorLayout_)) removeViewAtWithInt:index];
    ASViewGroupImpl_nativeRemoveViewWithASIWidget_(widget);
  }
  return remove;
}

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(jint)index {
  if (index != -2) {
    ADView *view = (ADView *) cast_chk([((id<ASIWidget>) nil_chk(w)) asWidget], [ADView class]);
    ASCoordinatorLayoutImpl_createLayoutParamsWithADView_(self, view);
    if (index == -1) {
      [((ADXCoordinatorLayout *) nil_chk(coordinatorLayout_)) addViewWithADView:view];
    }
    else {
      [((ADXCoordinatorLayout *) nil_chk(coordinatorLayout_)) addViewWithADView:view withInt:index];
    }
  }
  ASViewGroupImpl_nativeAddViewWithId_withId_([self asNativeWidget], [((id<ASIWidget>) nil_chk(w)) asNativeWidget]);
  [super addWithASIWidget:w withInt:index];
}

- (void)createLayoutParamsWithADView:(ADView *)view {
  ASCoordinatorLayoutImpl_createLayoutParamsWithADView_(self, view);
}

- (ADXCoordinatorLayout_LayoutParams *)getLayoutParamsWithADView:(ADView *)view {
  return ASCoordinatorLayoutImpl_getLayoutParamsWithADView_(self, view);
}

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue {
  ADView *view = (ADView *) cast_chk([((id<ASIWidget>) nil_chk(w)) asWidget], [ADView class]);
  ADXCoordinatorLayout_LayoutParams *layoutParams = ASCoordinatorLayoutImpl_getLayoutParamsWithADView_(self, view);
  ASViewGroupImpl_setChildAttributeWithASIWidget_withASWidgetAttribute_withId_withId_(w, key, objValue, layoutParams);
  switch (JreIndexOfStr([((ASWidgetAttribute *) nil_chk(key)) getAttributeName], (id[]){ @"layout_width", @"layout_height", @"layout_gravity", @"layout_behavior", @"layout_anchor", @"layout_keyline", @"layout_anchorGravity", @"layout_insetEdge", @"layout_dodgeInsetEdges" }, 9)) {
    case 0:
    ((ADXCoordinatorLayout_LayoutParams *) nil_chk(layoutParams))->width_ = [((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class]))) intValue];
    break;
    case 1:
    ((ADXCoordinatorLayout_LayoutParams *) nil_chk(layoutParams))->height_ = [((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class]))) intValue];
    break;
    case 2:
    {
      ((ADXCoordinatorLayout_LayoutParams *) nil_chk(layoutParams))->gravity_ = [((JavaLangInteger *) nil_chk(((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class])))) intValue];
    }
    break;
    case 3:
    {
      ASCoordinatorLayoutImpl_setBehaviorWithADXCoordinatorLayout_LayoutParams_withId_(self, layoutParams, objValue);
    }
    break;
    case 4:
    {
      [((ADXCoordinatorLayout_LayoutParams *) nil_chk(layoutParams)) setAnchorIdWithInt:[((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class]))) intValue]];
    }
    break;
    case 5:
    {
      ((ADXCoordinatorLayout_LayoutParams *) nil_chk(layoutParams))->keyline_ = [((JavaLangInteger *) nil_chk(((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class])))) intValue];
    }
    break;
    case 6:
    {
      ((ADXCoordinatorLayout_LayoutParams *) nil_chk(layoutParams))->anchorGravity_ = [((JavaLangInteger *) nil_chk(((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class])))) intValue];
    }
    break;
    case 7:
    {
      ((ADXCoordinatorLayout_LayoutParams *) nil_chk(layoutParams))->insetEdge_ = [((JavaLangInteger *) nil_chk(((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class])))) intValue];
    }
    break;
    case 8:
    {
      ((ADXCoordinatorLayout_LayoutParams *) nil_chk(layoutParams))->dodgeInsetEdges_ = [((JavaLangInteger *) nil_chk(((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class])))) intValue];
    }
    break;
    default:
    break;
  }
  [((ADView *) nil_chk(view)) setLayoutParamsWithADViewGroup_LayoutParams:layoutParams];
}

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key {
  id attributeValue = ASViewGroupImpl_getChildAttributeWithASIWidget_withASWidgetAttribute_(w, key);
  if (attributeValue != nil) {
    return attributeValue;
  }
  ADView *view = (ADView *) cast_chk([((id<ASIWidget>) nil_chk(w)) asWidget], [ADView class]);
  ADXCoordinatorLayout_LayoutParams *layoutParams = ASCoordinatorLayoutImpl_getLayoutParamsWithADView_(self, view);
  switch (JreIndexOfStr([((ASWidgetAttribute *) nil_chk(key)) getAttributeName], (id[]){ @"layout_width", @"layout_height", @"layout_gravity", @"layout_anchor", @"layout_keyline", @"layout_anchorGravity", @"layout_insetEdge", @"layout_dodgeInsetEdges" }, 8)) {
    case 0:
    return JavaLangInteger_valueOfWithInt_(((ADXCoordinatorLayout_LayoutParams *) nil_chk(layoutParams))->width_);
    case 1:
    return JavaLangInteger_valueOfWithInt_(((ADXCoordinatorLayout_LayoutParams *) nil_chk(layoutParams))->height_);
    case 2:
    {
      return JavaLangInteger_valueOfWithInt_(((ADXCoordinatorLayout_LayoutParams *) nil_chk(layoutParams))->gravity_);
    }
    case 3:
    {
      return JavaLangInteger_valueOfWithInt_([((ADXCoordinatorLayout_LayoutParams *) nil_chk(layoutParams)) getAnchorId]);
    }
    case 4:
    {
      return JavaLangInteger_valueOfWithInt_(((ADXCoordinatorLayout_LayoutParams *) nil_chk(layoutParams))->keyline_);
    }
    case 5:
    {
      return JavaLangInteger_valueOfWithInt_(((ADXCoordinatorLayout_LayoutParams *) nil_chk(layoutParams))->anchorGravity_);
    }
    case 6:
    {
      return JavaLangInteger_valueOfWithInt_(((ADXCoordinatorLayout_LayoutParams *) nil_chk(layoutParams))->insetEdge_);
    }
    case 7:
    {
      return JavaLangInteger_valueOfWithInt_(((ADXCoordinatorLayout_LayoutParams *) nil_chk(layoutParams))->dodgeInsetEdges_);
    }
  }
  return nil;
}

- (IOSClass *)getViewClass {
  return ASCoordinatorLayoutImpl_CoordinatorLayoutExt_class_();
}

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator {
  ASViewGroupImpl_setAttributeWithASIWidget_withASWidgetAttribute_withNSString_withId_withASILifeCycleDecorator_(self, key, strValue, objValue, decorator);
  id nativeWidget = [self asNativeWidget];
  switch (JreIndexOfStr([((ASWidgetAttribute *) nil_chk(key)) getAttributeName], (id[]){ @"keylines" }, 1)) {
    case 0:
    {
      ASCoordinatorLayoutImpl_setKeyLinesWithId_(self, objValue);
    }
    break;
    default:
    break;
  }
}

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator {
  id attributeValue = ASViewGroupImpl_getAttributeWithASIWidget_withASWidgetAttribute_withASILifeCycleDecorator_(self, key, decorator);
  if (attributeValue != nil) {
    return attributeValue;
  }
  id nativeWidget = [self asNativeWidget];
  switch (JreIndexOfStr([((ASWidgetAttribute *) nil_chk(key)) getAttributeName], (id[]){  }, 0)) {
  }
  return nil;
}

- (id)asNativeWidget {
  return uiView_;
}

- (jboolean)checkIosVersionWithNSString:(NSString *)v {
  return ([[[UIDevice currentDevice] systemVersion] compare:v options:NSNumericSearch] == NSOrderedDescending);
}

- (void)nativeCreateWithJavaUtilMap:(id<JavaUtilMap>)params {
  ASUIView* uiView = [ASUIView new];
  uiView.backgroundColor = [UIColor clearColor];
  uiView_ = uiView;
}

- (void)requestLayout {
  if ([self isInitialised]) {
    ASViewImpl_requestLayoutWithASIWidget_withId_(self, [self asNativeWidget]);
  }
}

- (void)invalidate {
  if ([self isInitialised]) {
    ASViewImpl_invalidateWithASIWidget_withId_(self, [self asNativeWidget]);
  }
}

- (void)setBehaviorWithADXCoordinatorLayout_LayoutParams:(ADXCoordinatorLayout_LayoutParams *)layoutParams
                                                  withId:(id)objValue {
  ASCoordinatorLayoutImpl_setBehaviorWithADXCoordinatorLayout_LayoutParams_withId_(self, layoutParams, objValue);
}

- (void)setKeyLinesWithId:(id)objValue {
  ASCoordinatorLayoutImpl_setKeyLinesWithId_(self, objValue);
}

- (void)setMyKeyLinesWithIntArray:(IOSIntArray *)keyLines {
  ASCoordinatorLayoutImpl_setMyKeyLinesWithIntArray_(self, keyLines);
}

- (void)setIdWithNSString:(NSString *)id_ {
  if (id_ != nil && ![id_ isEqual:@""]) {
    [super setIdWithNSString:id_];
    [((ADXCoordinatorLayout *) nil_chk(coordinatorLayout_)) setIdWithInt:[((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk([self quickConvertWithId:id_ withNSString:@"id"], [JavaLangInteger class]))) intValue]];
  }
}

- (void)setVisibleWithBoolean:(jboolean)b {
  [((ADView *) nil_chk(((ADView *) cast_chk([self asWidget], [ADView class])))) setVisibilityWithInt:b ? ADView_VISIBLE : ADView_GONE];
}

- (id)getPluginWithNSString:(NSString *)plugin {
  return [((id<ASIAttributable>) nil_chk(ASWidgetFactory_getAttributableWithNSString_(plugin))) newInstanceWithASIWidget:self];
}

- (ASCoordinatorLayoutImpl_CoordinatorLayoutBean *)getBean {
  if (bean_ == nil) {
    bean_ = new_ASCoordinatorLayoutImpl_CoordinatorLayoutBean_initWithASCoordinatorLayoutImpl_(self);
  }
  return bean_;
}

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)getBuilder {
  if (builder_ == nil) {
    builder_ = new_ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder_initWithASCoordinatorLayoutImpl_(self);
  }
  return builder_;
}

- (ASCoordinatorLayoutImpl_CoordinatorLayoutParamsBean *)getParamsBean {
  if (paramsBean_ == nil) {
    paramsBean_ = new_ASCoordinatorLayoutImpl_CoordinatorLayoutParamsBean_initWithASCoordinatorLayoutImpl_(self);
  }
  return paramsBean_;
}

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *)getParamsBuilder {
  if (paramsBuilder_ == nil) {
    paramsBuilder_ = new_ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder_initWithASCoordinatorLayoutImpl_(self);
  }
  return paramsBuilder_;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "V", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 2, -1, -1, -1, -1 },
    { NULL, "LASIWidget;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 3, 4, -1, 5, -1, -1 },
    { NULL, "V", 0x102, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, 6, 7, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, 6, 8, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 9, 10, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 11, 12, -1, -1, -1, -1 },
    { NULL, "LADXCoordinatorLayout_LayoutParams;", 0x2, 13, 12, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 14, 15, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 16, 17, -1, -1, -1, -1 },
    { NULL, "LIOSClass;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 18, 19, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 20, 21, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x101, 22, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x101, 23, 24, -1, 25, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 26, 27, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 28, 29, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 30, 31, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 32, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 33, 34, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 35, 1, -1, -1, -1, -1 },
    { NULL, "LASCoordinatorLayoutImpl_CoordinatorLayoutBean;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LASCoordinatorLayoutImpl_CoordinatorLayoutParamsBean;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(loadAttributesWithNSString:);
  methods[1].selector = @selector(init);
  methods[2].selector = @selector(initWithNSString:);
  methods[3].selector = @selector(initWithNSString:withNSString:);
  methods[4].selector = @selector(newInstance);
  methods[5].selector = @selector(createWithASIFragment:withJavaUtilMap:);
  methods[6].selector = @selector(setWidgetOnNativeClass);
  methods[7].selector = @selector(asWidget);
  methods[8].selector = @selector(removeWithASIWidget:);
  methods[9].selector = @selector(removeWithInt:);
  methods[10].selector = @selector(addWithASIWidget:withInt:);
  methods[11].selector = @selector(createLayoutParamsWithADView:);
  methods[12].selector = @selector(getLayoutParamsWithADView:);
  methods[13].selector = @selector(setChildAttributeWithASIWidget:withASWidgetAttribute:withNSString:withId:);
  methods[14].selector = @selector(getChildAttributeWithASIWidget:withASWidgetAttribute:);
  methods[15].selector = @selector(getViewClass);
  methods[16].selector = @selector(setAttributeWithASWidgetAttribute:withNSString:withId:withASILifeCycleDecorator:);
  methods[17].selector = @selector(getAttributeWithASWidgetAttribute:withASILifeCycleDecorator:);
  methods[18].selector = @selector(asNativeWidget);
  methods[19].selector = @selector(checkIosVersionWithNSString:);
  methods[20].selector = @selector(nativeCreateWithJavaUtilMap:);
  methods[21].selector = @selector(requestLayout);
  methods[22].selector = @selector(invalidate);
  methods[23].selector = @selector(setBehaviorWithADXCoordinatorLayout_LayoutParams:withId:);
  methods[24].selector = @selector(setKeyLinesWithId:);
  methods[25].selector = @selector(setMyKeyLinesWithIntArray:);
  methods[26].selector = @selector(setIdWithNSString:);
  methods[27].selector = @selector(setVisibleWithBoolean:);
  methods[28].selector = @selector(getPluginWithNSString:);
  methods[29].selector = @selector(getBean);
  methods[30].selector = @selector(getBuilder);
  methods[31].selector = @selector(getParamsBean);
  methods[32].selector = @selector(getParamsBuilder);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "uiView_", "LNSObject;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "LOCAL_NAME", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 36, -1, -1 },
    { "GROUP_NAME", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 37, -1, -1 },
    { "coordinatorLayout_", "LADXCoordinatorLayout;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "builder_", "LASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "bean_", "LASCoordinatorLayoutImpl_CoordinatorLayoutBean;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "paramsBuilder_", "LASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "paramsBean_", "LASCoordinatorLayoutImpl_CoordinatorLayoutParamsBean;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "loadAttributes", "LNSString;", "LNSString;LNSString;", "create", "LASIFragment;LJavaUtilMap;", "(Lcom/ashera/core/IFragment;Ljava/util/Map<Ljava/lang/String;Ljava/lang/Object;>;)V", "remove", "LASIWidget;", "I", "add", "LASIWidget;I", "createLayoutParams", "LADView;", "getLayoutParams", "setChildAttribute", "LASIWidget;LASWidgetAttribute;LNSString;LNSObject;", "getChildAttribute", "LASIWidget;LASWidgetAttribute;", "setAttribute", "LASWidgetAttribute;LNSString;LNSObject;LASILifeCycleDecorator;", "getAttribute", "LASWidgetAttribute;LASILifeCycleDecorator;", "checkIosVersion", "nativeCreate", "LJavaUtilMap;", "(Ljava/util/Map<Ljava/lang/String;Ljava/lang/Object;>;)V", "setBehavior", "LADXCoordinatorLayout_LayoutParams;LNSObject;", "setKeyLines", "LNSObject;", "setMyKeyLines", "[I", "setId", "setVisible", "Z", "getPlugin", &ASCoordinatorLayoutImpl_LOCAL_NAME, &ASCoordinatorLayoutImpl_GROUP_NAME, "LASCoordinatorLayoutImpl_InsetEdge;LASCoordinatorLayoutImpl_DodgeInsetEdge;LASCoordinatorLayoutImpl_CoordinatorLayoutExt;LASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder;LASCoordinatorLayoutImpl_CoordinatorLayoutBean;LASCoordinatorLayoutImpl_CoordinatorLayoutParamsBean;LASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder;" };
  static const J2ObjcClassInfo _ASCoordinatorLayoutImpl = { "CoordinatorLayoutImpl", "com.ashera.coordinatorlayout", ptrTable, methods, fields, 7, 0x1, 33, 8, -1, 38, -1, -1, -1 };
  return &_ASCoordinatorLayoutImpl;
}

@end

void ASCoordinatorLayoutImpl_init(ASCoordinatorLayoutImpl *self) {
  ASBaseHasWidgets_initWithNSString_withNSString_(self, ASCoordinatorLayoutImpl_GROUP_NAME, ASCoordinatorLayoutImpl_LOCAL_NAME);
}

ASCoordinatorLayoutImpl *new_ASCoordinatorLayoutImpl_init() {
  J2OBJC_NEW_IMPL(ASCoordinatorLayoutImpl, init)
}

ASCoordinatorLayoutImpl *create_ASCoordinatorLayoutImpl_init() {
  J2OBJC_CREATE_IMPL(ASCoordinatorLayoutImpl, init)
}

void ASCoordinatorLayoutImpl_initWithNSString_(ASCoordinatorLayoutImpl *self, NSString *localname) {
  ASBaseHasWidgets_initWithNSString_withNSString_(self, ASCoordinatorLayoutImpl_GROUP_NAME, localname);
}

ASCoordinatorLayoutImpl *new_ASCoordinatorLayoutImpl_initWithNSString_(NSString *localname) {
  J2OBJC_NEW_IMPL(ASCoordinatorLayoutImpl, initWithNSString_, localname)
}

ASCoordinatorLayoutImpl *create_ASCoordinatorLayoutImpl_initWithNSString_(NSString *localname) {
  J2OBJC_CREATE_IMPL(ASCoordinatorLayoutImpl, initWithNSString_, localname)
}

void ASCoordinatorLayoutImpl_initWithNSString_withNSString_(ASCoordinatorLayoutImpl *self, NSString *groupName, NSString *localname) {
  ASBaseHasWidgets_initWithNSString_withNSString_(self, groupName, localname);
}

ASCoordinatorLayoutImpl *new_ASCoordinatorLayoutImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) {
  J2OBJC_NEW_IMPL(ASCoordinatorLayoutImpl, initWithNSString_withNSString_, groupName, localname)
}

ASCoordinatorLayoutImpl *create_ASCoordinatorLayoutImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) {
  J2OBJC_CREATE_IMPL(ASCoordinatorLayoutImpl, initWithNSString_withNSString_, groupName, localname)
}

void ASCoordinatorLayoutImpl_setWidgetOnNativeClass(ASCoordinatorLayoutImpl *self) {
  ((ASUIView*) [self asNativeWidget]).widget = self;
}

void ASCoordinatorLayoutImpl_createLayoutParamsWithADView_(ASCoordinatorLayoutImpl *self, ADView *view) {
  ADXCoordinatorLayout_LayoutParams *layoutParams = (ADXCoordinatorLayout_LayoutParams *) cast_chk([((ADView *) nil_chk(view)) getLayoutParams], [ADXCoordinatorLayout_LayoutParams class]);
  layoutParams = (ADXCoordinatorLayout_LayoutParams *) cast_chk([view getLayoutParams], [ADXCoordinatorLayout_LayoutParams class]);
  if (layoutParams == nil) {
    layoutParams = new_ADXCoordinatorLayout_LayoutParams_initWithInt_withInt_(-2, -2);
    [view setLayoutParamsWithADViewGroup_LayoutParams:layoutParams];
  }
  else {
    layoutParams->height_ = -2;
    layoutParams->width_ = -2;
  }
}

ADXCoordinatorLayout_LayoutParams *ASCoordinatorLayoutImpl_getLayoutParamsWithADView_(ASCoordinatorLayoutImpl *self, ADView *view) {
  return (ADXCoordinatorLayout_LayoutParams *) cast_chk([((ADView *) nil_chk(view)) getLayoutParams], [ADXCoordinatorLayout_LayoutParams class]);
}

void ASCoordinatorLayoutImpl_setBehaviorWithADXCoordinatorLayout_LayoutParams_withId_(ASCoordinatorLayoutImpl *self, ADXCoordinatorLayout_LayoutParams *layoutParams, id objValue) {
  id behavior = ASWidgetFactory_getBehaviorWithNSString_((NSString *) cast_chk(objValue, [NSString class]));
  if (behavior == nil) {
    @throw new_JavaLangRuntimeException_initWithNSString_(JreStrcat("$$", @"Call WidgetFactory.registerBehavior for ", (NSString *) cast_chk(objValue, [NSString class])));
  }
  [((ADXCoordinatorLayout_LayoutParams *) nil_chk(layoutParams)) setBehaviorWithADXCoordinatorLayout_Behavior:(ADXCoordinatorLayout_Behavior *) cast_chk(behavior, [ADXCoordinatorLayout_Behavior class])];
}

void ASCoordinatorLayoutImpl_setKeyLinesWithId_(ASCoordinatorLayoutImpl *self, id objValue) {
  id<JavaUtilList> values = (id<JavaUtilList>) cast_check(objValue, JavaUtilList_class_());
  IOSIntArray *keyLines = [IOSIntArray newArrayWithLength:[((id<JavaUtilList>) nil_chk(values)) size]];
  for (jint i = 0; i < [values size]; i++) {
    jint obj = [((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk([values getWithInt:i], [JavaLangInteger class]))) intValue];
    *IOSIntArray_GetRef(keyLines, i) = JreFpToInt((obj * ((ADDisplayMetrics *) nil_chk([((ADResources *) nil_chk([((ADContext *) nil_chk([((ADXCoordinatorLayout *) nil_chk(self->coordinatorLayout_)) getContext])) getResources])) getDisplayMetrics]))->density_));
  }
  ASCoordinatorLayoutImpl_setMyKeyLinesWithIntArray_(self, keyLines);
}

void ASCoordinatorLayoutImpl_setMyKeyLinesWithIntArray_(ASCoordinatorLayoutImpl *self, IOSIntArray *keyLines) {
  [((ADXCoordinatorLayout *) nil_chk(self->coordinatorLayout_)) setKeyLinesWithIntArray:keyLines];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASCoordinatorLayoutImpl)

@implementation ASCoordinatorLayoutImpl_InsetEdge

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ASCoordinatorLayoutImpl_InsetEdge_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (id<JavaUtilMap>)getMapping {
  return mapping_;
}

- (JavaLangInteger *)getDefault {
  return JavaLangInteger_valueOfWithInt_(0);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
    { NULL, "LJavaUtilMap;", 0x1, -1, -1, -1, 0, -1, -1 },
    { NULL, "LJavaLangInteger;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(getMapping);
  methods[2].selector = @selector(getDefault);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "mapping_", "LJavaUtilMap;", .constantValue.asLong = 0, 0x2, -1, -1, 1, -1 },
  };
  static const void *ptrTable[] = { "()Ljava/util/Map<Ljava/lang/String;Ljava/lang/Integer;>;", "Ljava/util/Map<Ljava/lang/String;Ljava/lang/Integer;>;", "LASCoordinatorLayoutImpl;" };
  static const J2ObjcClassInfo _ASCoordinatorLayoutImpl_InsetEdge = { "InsetEdge", "com.ashera.coordinatorlayout", ptrTable, methods, fields, 7, 0x18, 3, 1, 2, -1, -1, -1, -1 };
  return &_ASCoordinatorLayoutImpl_InsetEdge;
}

@end

void ASCoordinatorLayoutImpl_InsetEdge_init(ASCoordinatorLayoutImpl_InsetEdge *self) {
  ASAbstractEnumToIntConverter_init(self);
  self->mapping_ = new_JavaUtilHashMap_init();
  {
    (void) [self->mapping_ putWithId:@"none" withId:JavaLangInteger_valueOfWithInt_((jint) 0x0)];
    (void) [((id<JavaUtilMap>) nil_chk(self->mapping_)) putWithId:@"top" withId:JavaLangInteger_valueOfWithInt_((jint) 0x30)];
    (void) [((id<JavaUtilMap>) nil_chk(self->mapping_)) putWithId:@"bottom" withId:JavaLangInteger_valueOfWithInt_((jint) 0x50)];
    (void) [((id<JavaUtilMap>) nil_chk(self->mapping_)) putWithId:@"left" withId:JavaLangInteger_valueOfWithInt_((jint) 0x03)];
    (void) [((id<JavaUtilMap>) nil_chk(self->mapping_)) putWithId:@"right" withId:JavaLangInteger_valueOfWithInt_((jint) 0x05)];
    (void) [((id<JavaUtilMap>) nil_chk(self->mapping_)) putWithId:@"start" withId:JavaLangInteger_valueOfWithInt_((jint) 0x00800003)];
    (void) [((id<JavaUtilMap>) nil_chk(self->mapping_)) putWithId:@"end" withId:JavaLangInteger_valueOfWithInt_((jint) 0x00800005)];
  }
}

ASCoordinatorLayoutImpl_InsetEdge *new_ASCoordinatorLayoutImpl_InsetEdge_init() {
  J2OBJC_NEW_IMPL(ASCoordinatorLayoutImpl_InsetEdge, init)
}

ASCoordinatorLayoutImpl_InsetEdge *create_ASCoordinatorLayoutImpl_InsetEdge_init() {
  J2OBJC_CREATE_IMPL(ASCoordinatorLayoutImpl_InsetEdge, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASCoordinatorLayoutImpl_InsetEdge)

@implementation ASCoordinatorLayoutImpl_DodgeInsetEdge

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ASCoordinatorLayoutImpl_DodgeInsetEdge_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (id<JavaUtilMap>)getMapping {
  return mapping_;
}

- (JavaLangInteger *)getDefault {
  return JavaLangInteger_valueOfWithInt_(0);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
    { NULL, "LJavaUtilMap;", 0x1, -1, -1, -1, 0, -1, -1 },
    { NULL, "LJavaLangInteger;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(getMapping);
  methods[2].selector = @selector(getDefault);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "mapping_", "LJavaUtilMap;", .constantValue.asLong = 0, 0x2, -1, -1, 1, -1 },
  };
  static const void *ptrTable[] = { "()Ljava/util/Map<Ljava/lang/String;Ljava/lang/Integer;>;", "Ljava/util/Map<Ljava/lang/String;Ljava/lang/Integer;>;", "LASCoordinatorLayoutImpl;" };
  static const J2ObjcClassInfo _ASCoordinatorLayoutImpl_DodgeInsetEdge = { "DodgeInsetEdge", "com.ashera.coordinatorlayout", ptrTable, methods, fields, 7, 0x18, 3, 1, 2, -1, -1, -1, -1 };
  return &_ASCoordinatorLayoutImpl_DodgeInsetEdge;
}

@end

void ASCoordinatorLayoutImpl_DodgeInsetEdge_init(ASCoordinatorLayoutImpl_DodgeInsetEdge *self) {
  ASAbstractBitFlagConverter_init(self);
  self->mapping_ = new_JavaUtilHashMap_init();
  {
    (void) [self->mapping_ putWithId:@"none" withId:JavaLangInteger_valueOfWithInt_((jint) 0x0)];
    (void) [((id<JavaUtilMap>) nil_chk(self->mapping_)) putWithId:@"top" withId:JavaLangInteger_valueOfWithInt_((jint) 0x30)];
    (void) [((id<JavaUtilMap>) nil_chk(self->mapping_)) putWithId:@"bottom" withId:JavaLangInteger_valueOfWithInt_((jint) 0x50)];
    (void) [((id<JavaUtilMap>) nil_chk(self->mapping_)) putWithId:@"left" withId:JavaLangInteger_valueOfWithInt_((jint) 0x03)];
    (void) [((id<JavaUtilMap>) nil_chk(self->mapping_)) putWithId:@"right" withId:JavaLangInteger_valueOfWithInt_((jint) 0x05)];
    (void) [((id<JavaUtilMap>) nil_chk(self->mapping_)) putWithId:@"start" withId:JavaLangInteger_valueOfWithInt_((jint) 0x00800003)];
    (void) [((id<JavaUtilMap>) nil_chk(self->mapping_)) putWithId:@"end" withId:JavaLangInteger_valueOfWithInt_((jint) 0x00800005)];
    (void) [((id<JavaUtilMap>) nil_chk(self->mapping_)) putWithId:@"all" withId:JavaLangInteger_valueOfWithInt_((jint) 0x77)];
  }
}

ASCoordinatorLayoutImpl_DodgeInsetEdge *new_ASCoordinatorLayoutImpl_DodgeInsetEdge_init() {
  J2OBJC_NEW_IMPL(ASCoordinatorLayoutImpl_DodgeInsetEdge, init)
}

ASCoordinatorLayoutImpl_DodgeInsetEdge *create_ASCoordinatorLayoutImpl_DodgeInsetEdge_init() {
  J2OBJC_CREATE_IMPL(ASCoordinatorLayoutImpl_DodgeInsetEdge, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASCoordinatorLayoutImpl_DodgeInsetEdge)

@implementation ASCoordinatorLayoutImpl_CoordinatorLayoutExt

- (id<ASIWidget>)getWidget {
  return this$0_;
}

- (void)setMaxWidthWithInt:(jint)width {
  mMaxWidth_ = width;
}

- (void)setMaxHeightWithInt:(jint)height {
  mMaxHeight_ = height;
}

- (jint)getMaxWidth {
  return mMaxWidth_;
}

- (jint)getMaxHeight {
  return mMaxHeight_;
}

- (instancetype)initWithASCoordinatorLayoutImpl:(ASCoordinatorLayoutImpl *)outer$ {
  ASCoordinatorLayoutImpl_CoordinatorLayoutExt_initWithASCoordinatorLayoutImpl_(self, outer$);
  return self;
}

- (void)onMeasureWithInt:(jint)widthMeasureSpec
                 withInt:(jint)heightMeasureSpec {
  if (mMaxWidth_ > 0) {
    widthMeasureSpec = ADView_MeasureSpec_makeMeasureSpecWithInt_withInt_(mMaxWidth_, ADView_MeasureSpec_AT_MOST);
  }
  if (mMaxHeight_ > 0) {
    heightMeasureSpec = ADView_MeasureSpec_makeMeasureSpecWithInt_withInt_(mMaxHeight_, ADView_MeasureSpec_AT_MOST);
  }
  [super onMeasureWithInt:widthMeasureSpec withInt:heightMeasureSpec];
  id<ASIWidgetLifeCycleListener> listener = [this$0_ getListener];
  if (listener != nil) {
    [((ASMeasureEvent *) nil_chk(measureFinished_)) setWidthWithInt:[self getMeasuredWidth]];
    [((ASMeasureEvent *) nil_chk(measureFinished_)) setHeightWithInt:[self getMeasuredHeight]];
    [listener eventOccurredWithASIWidgetLifeCycleListener_EventId:JreLoadEnum(ASIWidgetLifeCycleListener_EventId, measureFinished) withASWidgetEvent:measureFinished_];
  }
}

- (void)onLayoutWithBoolean:(jboolean)changed
                    withInt:(jint)l
                    withInt:(jint)t
                    withInt:(jint)r
                    withInt:(jint)b {
  [super onLayoutWithBoolean:changed withInt:l withInt:t withInt:r withInt:b];
  ASViewImpl_setDrawableBoundsWithASIWidget_withInt_withInt_withInt_withInt_(this$0_, l, t, r, b);
  ASViewImpl_nativeMakeFrameWithId_withInt_withInt_withInt_withInt_([this$0_ asNativeWidget], l, t, r, b);
  [this$0_ replayBufferedEvents];
  ASViewImpl_redrawDrawablesWithASIWidget_(this$0_);
  id<ASIWidgetLifeCycleListener> listener = [this$0_ getListener];
  if (listener != nil) {
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setBWithInt:b];
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setLWithInt:l];
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setRWithInt:r];
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setTWithInt:t];
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setChangedWithBoolean:changed];
    [listener eventOccurredWithASIWidgetLifeCycleListener_EventId:JreLoadEnum(ASIWidgetLifeCycleListener_EventId, onLayout) withASWidgetEvent:onLayoutEvent_];
  }
  if ([this$0_ isInvalidateOnFrameChange] && [this$0_ isInitialised]) {
    [this$0_ invalidate];
  }
}

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas {
}

- (void)updateMeasuredDimensionWithInt:(jint)width
                               withInt:(jint)height {
  [self setMeasuredDimensionWithInt:width withInt:height];
}

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (id<JavaUtilList>)getMethods {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (void)initialized {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (void)drawableStateChanged {
  [super drawableStateChanged];
  ASViewImpl_drawableStateChangedWithASIWidget_(this$0_);
}

- (ADView *)inflateViewWithNSString:(NSString *)layout {
  if (templates_ == nil) {
    templates_ = new_JavaUtilHashMap_init();
  }
  id<ASIWidget> template_ = [templates_ getWithId:layout];
  if (template_ == nil) {
    template_ = (id<ASIWidget>) cast_check([this$0_ quickConvertWithId:layout withNSString:@"template"], ASIWidget_class_());
    (void) [((id<JavaUtilMap>) nil_chk(templates_)) putWithId:layout withId:template_];
  }
  id<ASIWidget> widget = [((id<ASIWidget>) nil_chk(template_)) loadLazyWidgetsWithASHasWidgets:[this$0_ getParent]];
  return (ADView *) cast_chk([((id<ASIWidget>) nil_chk(widget)) asWidget], [ADView class]);
}

- (void)remeasure {
  [((id<ASIFragment>) nil_chk([this$0_ getFragment])) remeasure];
}

- (void)removeFromParent {
  [((id<ASHasWidgets>) nil_chk([this$0_ getParent])) removeWithASIWidget:this$0_];
}

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation {
  *IOSIntArray_GetRef(nil_chk(appScreenLocation), 0) = ASViewImpl_getLocationXOnScreenWithId_([this$0_ asNativeWidget]);
  *IOSIntArray_GetRef(appScreenLocation, 1) = ASViewImpl_getLocationYOnScreenWithId_([this$0_ asNativeWidget]);
}

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame {
  ((ADRect *) nil_chk(displayFrame))->left_ = ASViewImpl_getLocationXOnScreenWithId_([this$0_ asNativeWidget]);
  displayFrame->top_ = ASViewImpl_getLocationYOnScreenWithId_([this$0_ asNativeWidget]);
  displayFrame->right_ = displayFrame->left_ + [self getWidth];
  displayFrame->bottom_ = displayFrame->top_ + [self getHeight];
}

- (void)offsetTopAndBottomWithInt:(jint)offset {
  [super offsetTopAndBottomWithInt:offset];
  ASViewImpl_nativeMakeFrameWithId_withInt_withInt_withInt_withInt_([this$0_ asNativeWidget], [self getLeft], [self getTop], [self getRight], [self getBottom]);
}

- (void)offsetLeftAndRightWithInt:(jint)offset {
  [super offsetLeftAndRightWithInt:offset];
  ASViewImpl_nativeMakeFrameWithId_withInt_withInt_withInt_withInt_([this$0_ asNativeWidget], [self getLeft], [self getTop], [self getRight], [self getBottom]);
}

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value {
  [this$0_ setAttributeWithNSString:name withId:value withBoolean:true];
}

- (void)setVisibilityWithInt:(jint)visibility {
  [super setVisibilityWithInt:visibility];
  ASViewImpl_nativeSetVisibilityWithId_withBoolean_([this$0_ asNativeWidget], visibility != ADView_VISIBLE);
}

- (void)onLayoutChildWithADView:(ADView *)child
                        withInt:(jint)layoutDirection {
  [super onLayoutChildWithADView:child withInt:layoutDirection];
  if ([this$0_ isInitialised]) {
    [((ADXCoordinatorLayout *) nil_chk(this$0_->coordinatorLayout_)) onChildViewsChangedWithInt:0];
  }
}

- (void)state0 {
  ASViewImpl_stateWithASIWidget_withInt_(this$0_, 0);
}

- (void)state1 {
  ASViewImpl_stateWithASIWidget_withInt_(this$0_, 1);
}

- (void)state2 {
  ASViewImpl_stateWithASIWidget_withInt_(this$0_, 2);
}

- (void)state3 {
  ASViewImpl_stateWithASIWidget_withInt_(this$0_, 3);
}

- (void)state4 {
  ASViewImpl_stateWithASIWidget_withInt_(this$0_, 4);
}

- (void)stateYes {
  ASViewImpl_stateYesWithASIWidget_(this$0_);
}

- (void)stateNo {
  ASViewImpl_stateNoWithASIWidget_(this$0_);
}

- (void)__javaClone:(ASCoordinatorLayoutImpl_CoordinatorLayoutExt *)original {
  [super __javaClone:original];
  JreRelease(this$0_);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LASIWidget;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 2, 1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 3, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 4, 5, -1, -1, -1, -1 },
    { NULL, "V", 0x4, 6, 7, -1, -1, -1, -1 },
    { NULL, "V", 0x81, 8, 9, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 10, 5, -1, -1, -1, -1 },
    { NULL, "LASILifeCycleDecorator;", 0x1, 11, 12, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 13, 14, -1, -1, -1, -1 },
    { NULL, "LJavaUtilList;", 0x1, -1, -1, -1, 15, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 16, 17, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LADView;", 0x1, 18, 19, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 20, 21, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 22, 23, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 24, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 25, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 26, 27, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 28, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 29, 30, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(getWidget);
  methods[1].selector = @selector(setMaxWidthWithInt:);
  methods[2].selector = @selector(setMaxHeightWithInt:);
  methods[3].selector = @selector(getMaxWidth);
  methods[4].selector = @selector(getMaxHeight);
  methods[5].selector = @selector(initWithASCoordinatorLayoutImpl:);
  methods[6].selector = @selector(onMeasureWithInt:withInt:);
  methods[7].selector = @selector(onLayoutWithBoolean:withInt:withInt:withInt:withInt:);
  methods[8].selector = @selector(executeWithNSString:withNSObjectArray:);
  methods[9].selector = @selector(updateMeasuredDimensionWithInt:withInt:);
  methods[10].selector = @selector(newInstanceWithASIWidget:);
  methods[11].selector = @selector(setAttributeWithASWidgetAttribute:withNSString:withId:);
  methods[12].selector = @selector(getMethods);
  methods[13].selector = @selector(initialized);
  methods[14].selector = @selector(getAttributeWithASWidgetAttribute:);
  methods[15].selector = @selector(drawableStateChanged);
  methods[16].selector = @selector(inflateViewWithNSString:);
  methods[17].selector = @selector(remeasure);
  methods[18].selector = @selector(removeFromParent);
  methods[19].selector = @selector(getLocationOnScreenWithIntArray:);
  methods[20].selector = @selector(getWindowVisibleDisplayFrameWithADRect:);
  methods[21].selector = @selector(offsetTopAndBottomWithInt:);
  methods[22].selector = @selector(offsetLeftAndRightWithInt:);
  methods[23].selector = @selector(setMyAttributeWithNSString:withId:);
  methods[24].selector = @selector(setVisibilityWithInt:);
  methods[25].selector = @selector(onLayoutChildWithADView:withInt:);
  methods[26].selector = @selector(state0);
  methods[27].selector = @selector(state1);
  methods[28].selector = @selector(state2);
  methods[29].selector = @selector(state3);
  methods[30].selector = @selector(state4);
  methods[31].selector = @selector(stateYes);
  methods[32].selector = @selector(stateNo);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LASCoordinatorLayoutImpl;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
    { "measureFinished_", "LASMeasureEvent;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "onLayoutEvent_", "LASOnLayoutEvent;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "mMaxWidth_", "I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "mMaxHeight_", "I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "templates_", "LJavaUtilMap;", .constantValue.asLong = 0, 0x2, -1, -1, 31, -1 },
  };
  static const void *ptrTable[] = { "setMaxWidth", "I", "setMaxHeight", "LASCoordinatorLayoutImpl;", "onMeasure", "II", "onLayout", "ZIIII", "execute", "LNSString;[LNSObject;", "updateMeasuredDimension", "newInstance", "LASIWidget;", "setAttribute", "LASWidgetAttribute;LNSString;LNSObject;", "()Ljava/util/List<Ljava/lang/String;>;", "getAttribute", "LASWidgetAttribute;", "inflateView", "LNSString;", "getLocationOnScreen", "[I", "getWindowVisibleDisplayFrame", "LADRect;", "offsetTopAndBottom", "offsetLeftAndRight", "setMyAttribute", "LNSString;LNSObject;", "setVisibility", "onLayoutChild", "LADView;I", "Ljava/util/Map<Ljava/lang/String;Lcom/ashera/widget/IWidget;>;" };
  static const J2ObjcClassInfo _ASCoordinatorLayoutImpl_CoordinatorLayoutExt = { "CoordinatorLayoutExt", "com.ashera.coordinatorlayout", ptrTable, methods, fields, 7, 0x1, 33, 6, 3, -1, -1, -1, -1 };
  return &_ASCoordinatorLayoutImpl_CoordinatorLayoutExt;
}

@end

void ASCoordinatorLayoutImpl_CoordinatorLayoutExt_initWithASCoordinatorLayoutImpl_(ASCoordinatorLayoutImpl_CoordinatorLayoutExt *self, ASCoordinatorLayoutImpl *outer$) {
  self->this$0_ = outer$;
  ADXCoordinatorLayout_init(self);
  self->measureFinished_ = new_ASMeasureEvent_init();
  self->onLayoutEvent_ = new_ASOnLayoutEvent_init();
  self->mMaxWidth_ = -1;
  self->mMaxHeight_ = -1;
}

ASCoordinatorLayoutImpl_CoordinatorLayoutExt *new_ASCoordinatorLayoutImpl_CoordinatorLayoutExt_initWithASCoordinatorLayoutImpl_(ASCoordinatorLayoutImpl *outer$) {
  J2OBJC_NEW_IMPL(ASCoordinatorLayoutImpl_CoordinatorLayoutExt, initWithASCoordinatorLayoutImpl_, outer$)
}

ASCoordinatorLayoutImpl_CoordinatorLayoutExt *create_ASCoordinatorLayoutImpl_CoordinatorLayoutExt_initWithASCoordinatorLayoutImpl_(ASCoordinatorLayoutImpl *outer$) {
  J2OBJC_CREATE_IMPL(ASCoordinatorLayoutImpl_CoordinatorLayoutExt, initWithASCoordinatorLayoutImpl_, outer$)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASCoordinatorLayoutImpl_CoordinatorLayoutExt)

@implementation ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder

- (instancetype)initWithASCoordinatorLayoutImpl:(ASCoordinatorLayoutImpl *)outer$ {
  ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder_initWithASCoordinatorLayoutImpl_(self, outer$);
  return self;
}

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)executeWithBoolean:(jboolean)setter {
  if (setter) {
    [this$0_ executeCommandWithJavaUtilMap:command_ withASIWidget_CommandCallBack:nil withInt:ASIWidget_COMMAND_EXEC_SETTER_METHOD];
    [((id<ASIFragment>) nil_chk([this$0_ getFragment])) remeasure];
  }
  [this$0_ executeCommandWithJavaUtilMap:command_ withASIWidget_CommandCallBack:nil withInt:ASIWidget_COMMAND_EXEC_GETTER_METHOD];
  return self;
}

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *)setKeylinesWithNSString:(NSString *)value {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"keylines"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"setter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderSet" withId:JavaLangInteger_valueOfWithInt_(++orderSet_)];
  (void) [attrs putWithId:@"value" withId:value];
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "LASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder;", 0x1, 1, 2, -1, -1, -1, -1 },
    { NULL, "LASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder;", 0x1, 3, 4, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithASCoordinatorLayoutImpl:);
  methods[1].selector = @selector(executeWithBoolean:);
  methods[2].selector = @selector(setKeylinesWithNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LASCoordinatorLayoutImpl;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LASCoordinatorLayoutImpl;", "execute", "Z", "setKeylines", "LNSString;", "Lcom/ashera/layout/ViewGroupImpl$ViewGroupCommandBuilder<Lcom/ashera/coordinatorlayout/CoordinatorLayoutImpl$CoordinatorLayoutCommandBuilder;>;" };
  static const J2ObjcClassInfo _ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder = { "CoordinatorLayoutCommandBuilder", "com.ashera.coordinatorlayout", ptrTable, methods, fields, 7, 0x1, 3, 1, 0, -1, -1, 5, -1 };
  return &_ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder;
}

@end

void ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder_initWithASCoordinatorLayoutImpl_(ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *self, ASCoordinatorLayoutImpl *outer$) {
  self->this$0_ = outer$;
  ASViewGroupImpl_ViewGroupCommandBuilder_init(self);
}

ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *new_ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder_initWithASCoordinatorLayoutImpl_(ASCoordinatorLayoutImpl *outer$) {
  J2OBJC_NEW_IMPL(ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder, initWithASCoordinatorLayoutImpl_, outer$)
}

ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *create_ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder_initWithASCoordinatorLayoutImpl_(ASCoordinatorLayoutImpl *outer$) {
  J2OBJC_CREATE_IMPL(ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder, initWithASCoordinatorLayoutImpl_, outer$)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder)

@implementation ASCoordinatorLayoutImpl_CoordinatorLayoutBean

- (instancetype)initWithASCoordinatorLayoutImpl:(ASCoordinatorLayoutImpl *)outer$ {
  ASCoordinatorLayoutImpl_CoordinatorLayoutBean_initWithASCoordinatorLayoutImpl_(self, outer$);
  return self;
}

- (void)setKeylinesWithNSString:(NSString *)value {
  (void) [((ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *) nil_chk([((ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *) nil_chk([((ASCoordinatorLayoutImpl_CoordinatorLayoutCommandBuilder *) nil_chk([this$0_ getBuilder])) reset])) setKeylinesWithNSString:value])) executeWithBoolean:true];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 1, 2, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithASCoordinatorLayoutImpl:);
  methods[1].selector = @selector(setKeylinesWithNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LASCoordinatorLayoutImpl;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LASCoordinatorLayoutImpl;", "setKeylines", "LNSString;" };
  static const J2ObjcClassInfo _ASCoordinatorLayoutImpl_CoordinatorLayoutBean = { "CoordinatorLayoutBean", "com.ashera.coordinatorlayout", ptrTable, methods, fields, 7, 0x1, 2, 1, 0, -1, -1, -1, -1 };
  return &_ASCoordinatorLayoutImpl_CoordinatorLayoutBean;
}

@end

void ASCoordinatorLayoutImpl_CoordinatorLayoutBean_initWithASCoordinatorLayoutImpl_(ASCoordinatorLayoutImpl_CoordinatorLayoutBean *self, ASCoordinatorLayoutImpl *outer$) {
  self->this$0_ = outer$;
  ASViewGroupImpl_ViewGroupBean_initWithASIWidget_(self, outer$);
}

ASCoordinatorLayoutImpl_CoordinatorLayoutBean *new_ASCoordinatorLayoutImpl_CoordinatorLayoutBean_initWithASCoordinatorLayoutImpl_(ASCoordinatorLayoutImpl *outer$) {
  J2OBJC_NEW_IMPL(ASCoordinatorLayoutImpl_CoordinatorLayoutBean, initWithASCoordinatorLayoutImpl_, outer$)
}

ASCoordinatorLayoutImpl_CoordinatorLayoutBean *create_ASCoordinatorLayoutImpl_CoordinatorLayoutBean_initWithASCoordinatorLayoutImpl_(ASCoordinatorLayoutImpl *outer$) {
  J2OBJC_CREATE_IMPL(ASCoordinatorLayoutImpl_CoordinatorLayoutBean, initWithASCoordinatorLayoutImpl_, outer$)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASCoordinatorLayoutImpl_CoordinatorLayoutBean)

@implementation ASCoordinatorLayoutImpl_CoordinatorLayoutParamsBean

- (instancetype)initWithASCoordinatorLayoutImpl:(ASCoordinatorLayoutImpl *)outer$ {
  ASCoordinatorLayoutImpl_CoordinatorLayoutParamsBean_initWithASCoordinatorLayoutImpl_(self, outer$);
  return self;
}

- (id)getLayoutGravityWithASIWidget:(id<ASIWidget>)w {
  id<JavaUtilMap> layoutParams = new_JavaUtilHashMap_init();
  id<JavaUtilMap> command = [((ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *) nil_chk([((ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *) nil_chk([((ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *) nil_chk([this$0_ getParamsBuilder])) reset])) tryGetLayoutGravity])) getCommand];
  (void) [layoutParams putWithId:@"layoutParams" withId:command];
  [((id<ASIWidget>) nil_chk(w)) executeCommandWithJavaUtilMap:layoutParams withASIWidget_CommandCallBack:nil withInt:ASIWidget_COMMAND_EXEC_GETTER_METHOD];
  return [((ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *) nil_chk([this$0_ getParamsBuilder])) getLayoutGravity];
}

- (void)setLayoutGravityWithASIWidget:(id<ASIWidget>)w
                         withNSString:(NSString *)value {
  id<JavaUtilMap> layoutParams = new_JavaUtilHashMap_init();
  (void) [layoutParams putWithId:@"layoutParams" withId:[((ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *) nil_chk([((ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *) nil_chk([((ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *) nil_chk([this$0_ getParamsBuilder])) reset])) setLayoutGravityWithNSString:value])) getCommand]];
  [((id<ASIWidget>) nil_chk(w)) executeCommandWithJavaUtilMap:layoutParams withASIWidget_CommandCallBack:nil withInt:ASIWidget_COMMAND_EXEC_SETTER_METHOD];
  [((id<ASIFragment>) nil_chk([w getFragment])) remeasure];
}

- (void)setLayoutBehaviorWithASIWidget:(id<ASIWidget>)w
                          withNSString:(NSString *)value {
  id<JavaUtilMap> layoutParams = new_JavaUtilHashMap_init();
  (void) [layoutParams putWithId:@"layoutParams" withId:[((ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *) nil_chk([((ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *) nil_chk([((ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *) nil_chk([this$0_ getParamsBuilder])) reset])) setLayoutBehaviorWithNSString:value])) getCommand]];
  [((id<ASIWidget>) nil_chk(w)) executeCommandWithJavaUtilMap:layoutParams withASIWidget_CommandCallBack:nil withInt:ASIWidget_COMMAND_EXEC_SETTER_METHOD];
  [((id<ASIFragment>) nil_chk([w getFragment])) remeasure];
}

- (id)getLayoutAnchorWithASIWidget:(id<ASIWidget>)w {
  id<JavaUtilMap> layoutParams = new_JavaUtilHashMap_init();
  id<JavaUtilMap> command = [((ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *) nil_chk([((ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *) nil_chk([((ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *) nil_chk([this$0_ getParamsBuilder])) reset])) tryGetLayoutAnchor])) getCommand];
  (void) [layoutParams putWithId:@"layoutParams" withId:command];
  [((id<ASIWidget>) nil_chk(w)) executeCommandWithJavaUtilMap:layoutParams withASIWidget_CommandCallBack:nil withInt:ASIWidget_COMMAND_EXEC_GETTER_METHOD];
  return [((ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *) nil_chk([this$0_ getParamsBuilder])) getLayoutAnchor];
}

- (void)setLayoutAnchorWithASIWidget:(id<ASIWidget>)w
                        withNSString:(NSString *)value {
  id<JavaUtilMap> layoutParams = new_JavaUtilHashMap_init();
  (void) [layoutParams putWithId:@"layoutParams" withId:[((ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *) nil_chk([((ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *) nil_chk([((ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *) nil_chk([this$0_ getParamsBuilder])) reset])) setLayoutAnchorWithNSString:value])) getCommand]];
  [((id<ASIWidget>) nil_chk(w)) executeCommandWithJavaUtilMap:layoutParams withASIWidget_CommandCallBack:nil withInt:ASIWidget_COMMAND_EXEC_SETTER_METHOD];
  [((id<ASIFragment>) nil_chk([w getFragment])) remeasure];
}

- (id)getLayoutKeylineWithASIWidget:(id<ASIWidget>)w {
  id<JavaUtilMap> layoutParams = new_JavaUtilHashMap_init();
  id<JavaUtilMap> command = [((ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *) nil_chk([((ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *) nil_chk([((ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *) nil_chk([this$0_ getParamsBuilder])) reset])) tryGetLayoutKeyline])) getCommand];
  (void) [layoutParams putWithId:@"layoutParams" withId:command];
  [((id<ASIWidget>) nil_chk(w)) executeCommandWithJavaUtilMap:layoutParams withASIWidget_CommandCallBack:nil withInt:ASIWidget_COMMAND_EXEC_GETTER_METHOD];
  return [((ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *) nil_chk([this$0_ getParamsBuilder])) getLayoutKeyline];
}

- (void)setLayoutKeylineWithASIWidget:(id<ASIWidget>)w
                              withInt:(jint)value {
  id<JavaUtilMap> layoutParams = new_JavaUtilHashMap_init();
  (void) [layoutParams putWithId:@"layoutParams" withId:[((ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *) nil_chk([((ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *) nil_chk([((ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *) nil_chk([this$0_ getParamsBuilder])) reset])) setLayoutKeylineWithInt:value])) getCommand]];
  [((id<ASIWidget>) nil_chk(w)) executeCommandWithJavaUtilMap:layoutParams withASIWidget_CommandCallBack:nil withInt:ASIWidget_COMMAND_EXEC_SETTER_METHOD];
  [((id<ASIFragment>) nil_chk([w getFragment])) remeasure];
}

- (id)getLayoutAnchorGravityWithASIWidget:(id<ASIWidget>)w {
  id<JavaUtilMap> layoutParams = new_JavaUtilHashMap_init();
  id<JavaUtilMap> command = [((ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *) nil_chk([((ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *) nil_chk([((ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *) nil_chk([this$0_ getParamsBuilder])) reset])) tryGetLayoutAnchorGravity])) getCommand];
  (void) [layoutParams putWithId:@"layoutParams" withId:command];
  [((id<ASIWidget>) nil_chk(w)) executeCommandWithJavaUtilMap:layoutParams withASIWidget_CommandCallBack:nil withInt:ASIWidget_COMMAND_EXEC_GETTER_METHOD];
  return [((ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *) nil_chk([this$0_ getParamsBuilder])) getLayoutAnchorGravity];
}

- (void)setLayoutAnchorGravityWithASIWidget:(id<ASIWidget>)w
                               withNSString:(NSString *)value {
  id<JavaUtilMap> layoutParams = new_JavaUtilHashMap_init();
  (void) [layoutParams putWithId:@"layoutParams" withId:[((ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *) nil_chk([((ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *) nil_chk([((ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *) nil_chk([this$0_ getParamsBuilder])) reset])) setLayoutAnchorGravityWithNSString:value])) getCommand]];
  [((id<ASIWidget>) nil_chk(w)) executeCommandWithJavaUtilMap:layoutParams withASIWidget_CommandCallBack:nil withInt:ASIWidget_COMMAND_EXEC_SETTER_METHOD];
  [((id<ASIFragment>) nil_chk([w getFragment])) remeasure];
}

- (id)getLayoutInsetEdgeWithASIWidget:(id<ASIWidget>)w {
  id<JavaUtilMap> layoutParams = new_JavaUtilHashMap_init();
  id<JavaUtilMap> command = [((ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *) nil_chk([((ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *) nil_chk([((ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *) nil_chk([this$0_ getParamsBuilder])) reset])) tryGetLayoutInsetEdge])) getCommand];
  (void) [layoutParams putWithId:@"layoutParams" withId:command];
  [((id<ASIWidget>) nil_chk(w)) executeCommandWithJavaUtilMap:layoutParams withASIWidget_CommandCallBack:nil withInt:ASIWidget_COMMAND_EXEC_GETTER_METHOD];
  return [((ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *) nil_chk([this$0_ getParamsBuilder])) getLayoutInsetEdge];
}

- (void)setLayoutInsetEdgeWithASIWidget:(id<ASIWidget>)w
                           withNSString:(NSString *)value {
  id<JavaUtilMap> layoutParams = new_JavaUtilHashMap_init();
  (void) [layoutParams putWithId:@"layoutParams" withId:[((ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *) nil_chk([((ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *) nil_chk([((ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *) nil_chk([this$0_ getParamsBuilder])) reset])) setLayoutInsetEdgeWithNSString:value])) getCommand]];
  [((id<ASIWidget>) nil_chk(w)) executeCommandWithJavaUtilMap:layoutParams withASIWidget_CommandCallBack:nil withInt:ASIWidget_COMMAND_EXEC_SETTER_METHOD];
  [((id<ASIFragment>) nil_chk([w getFragment])) remeasure];
}

- (id)getLayoutDodgeInsetEdgesWithASIWidget:(id<ASIWidget>)w {
  id<JavaUtilMap> layoutParams = new_JavaUtilHashMap_init();
  id<JavaUtilMap> command = [((ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *) nil_chk([((ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *) nil_chk([((ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *) nil_chk([this$0_ getParamsBuilder])) reset])) tryGetLayoutDodgeInsetEdges])) getCommand];
  (void) [layoutParams putWithId:@"layoutParams" withId:command];
  [((id<ASIWidget>) nil_chk(w)) executeCommandWithJavaUtilMap:layoutParams withASIWidget_CommandCallBack:nil withInt:ASIWidget_COMMAND_EXEC_GETTER_METHOD];
  return [((ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *) nil_chk([this$0_ getParamsBuilder])) getLayoutDodgeInsetEdges];
}

- (void)setLayoutDodgeInsetEdgesWithASIWidget:(id<ASIWidget>)w
                                 withNSString:(NSString *)value {
  id<JavaUtilMap> layoutParams = new_JavaUtilHashMap_init();
  (void) [layoutParams putWithId:@"layoutParams" withId:[((ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *) nil_chk([((ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *) nil_chk([((ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *) nil_chk([this$0_ getParamsBuilder])) reset])) setLayoutDodgeInsetEdgesWithNSString:value])) getCommand]];
  [((id<ASIWidget>) nil_chk(w)) executeCommandWithJavaUtilMap:layoutParams withASIWidget_CommandCallBack:nil withInt:ASIWidget_COMMAND_EXEC_SETTER_METHOD];
  [((id<ASIFragment>) nil_chk([w getFragment])) remeasure];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 1, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 3, 4, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 5, 4, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 6, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 7, 4, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 8, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 9, 10, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 11, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 12, 4, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 13, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 14, 4, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 15, 2, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 16, 4, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithASCoordinatorLayoutImpl:);
  methods[1].selector = @selector(getLayoutGravityWithASIWidget:);
  methods[2].selector = @selector(setLayoutGravityWithASIWidget:withNSString:);
  methods[3].selector = @selector(setLayoutBehaviorWithASIWidget:withNSString:);
  methods[4].selector = @selector(getLayoutAnchorWithASIWidget:);
  methods[5].selector = @selector(setLayoutAnchorWithASIWidget:withNSString:);
  methods[6].selector = @selector(getLayoutKeylineWithASIWidget:);
  methods[7].selector = @selector(setLayoutKeylineWithASIWidget:withInt:);
  methods[8].selector = @selector(getLayoutAnchorGravityWithASIWidget:);
  methods[9].selector = @selector(setLayoutAnchorGravityWithASIWidget:withNSString:);
  methods[10].selector = @selector(getLayoutInsetEdgeWithASIWidget:);
  methods[11].selector = @selector(setLayoutInsetEdgeWithASIWidget:withNSString:);
  methods[12].selector = @selector(getLayoutDodgeInsetEdgesWithASIWidget:);
  methods[13].selector = @selector(setLayoutDodgeInsetEdgesWithASIWidget:withNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LASCoordinatorLayoutImpl;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LASCoordinatorLayoutImpl;", "getLayoutGravity", "LASIWidget;", "setLayoutGravity", "LASIWidget;LNSString;", "setLayoutBehavior", "getLayoutAnchor", "setLayoutAnchor", "getLayoutKeyline", "setLayoutKeyline", "LASIWidget;I", "getLayoutAnchorGravity", "setLayoutAnchorGravity", "getLayoutInsetEdge", "setLayoutInsetEdge", "getLayoutDodgeInsetEdges", "setLayoutDodgeInsetEdges" };
  static const J2ObjcClassInfo _ASCoordinatorLayoutImpl_CoordinatorLayoutParamsBean = { "CoordinatorLayoutParamsBean", "com.ashera.coordinatorlayout", ptrTable, methods, fields, 7, 0x1, 14, 1, 0, -1, -1, -1, -1 };
  return &_ASCoordinatorLayoutImpl_CoordinatorLayoutParamsBean;
}

@end

void ASCoordinatorLayoutImpl_CoordinatorLayoutParamsBean_initWithASCoordinatorLayoutImpl_(ASCoordinatorLayoutImpl_CoordinatorLayoutParamsBean *self, ASCoordinatorLayoutImpl *outer$) {
  self->this$0_ = outer$;
  ASViewGroupImpl_ViewGroupParamsBean_init(self);
}

ASCoordinatorLayoutImpl_CoordinatorLayoutParamsBean *new_ASCoordinatorLayoutImpl_CoordinatorLayoutParamsBean_initWithASCoordinatorLayoutImpl_(ASCoordinatorLayoutImpl *outer$) {
  J2OBJC_NEW_IMPL(ASCoordinatorLayoutImpl_CoordinatorLayoutParamsBean, initWithASCoordinatorLayoutImpl_, outer$)
}

ASCoordinatorLayoutImpl_CoordinatorLayoutParamsBean *create_ASCoordinatorLayoutImpl_CoordinatorLayoutParamsBean_initWithASCoordinatorLayoutImpl_(ASCoordinatorLayoutImpl *outer$) {
  J2OBJC_CREATE_IMPL(ASCoordinatorLayoutImpl_CoordinatorLayoutParamsBean, initWithASCoordinatorLayoutImpl_, outer$)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASCoordinatorLayoutImpl_CoordinatorLayoutParamsBean)

@implementation ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder

- (instancetype)initWithASCoordinatorLayoutImpl:(ASCoordinatorLayoutImpl *)outer$ {
  ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder_initWithASCoordinatorLayoutImpl_(self, outer$);
  return self;
}

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *)tryGetLayoutGravity {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"layout_gravity"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"getter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderGet" withId:JavaLangInteger_valueOfWithInt_(++orderGet_)];
  return self;
}

- (id)getLayoutGravity {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"layout_gravity"];
  return [((id<JavaUtilMap>) nil_chk(attrs)) getWithId:@"commandReturnValue"];
}

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *)setLayoutGravityWithNSString:(NSString *)value {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"layout_gravity"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"setter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderSet" withId:JavaLangInteger_valueOfWithInt_(++orderSet_)];
  (void) [attrs putWithId:@"value" withId:value];
  return self;
}

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *)setLayoutBehaviorWithNSString:(NSString *)value {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"layout_behavior"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"setter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderSet" withId:JavaLangInteger_valueOfWithInt_(++orderSet_)];
  (void) [attrs putWithId:@"value" withId:value];
  return self;
}

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *)tryGetLayoutAnchor {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"layout_anchor"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"getter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderGet" withId:JavaLangInteger_valueOfWithInt_(++orderGet_)];
  return self;
}

- (id)getLayoutAnchor {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"layout_anchor"];
  return [((id<JavaUtilMap>) nil_chk(attrs)) getWithId:@"commandReturnValue"];
}

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *)setLayoutAnchorWithNSString:(NSString *)value {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"layout_anchor"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"setter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderSet" withId:JavaLangInteger_valueOfWithInt_(++orderSet_)];
  (void) [attrs putWithId:@"value" withId:value];
  return self;
}

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *)tryGetLayoutKeyline {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"layout_keyline"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"getter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderGet" withId:JavaLangInteger_valueOfWithInt_(++orderGet_)];
  return self;
}

- (id)getLayoutKeyline {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"layout_keyline"];
  return [((id<JavaUtilMap>) nil_chk(attrs)) getWithId:@"commandReturnValue"];
}

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *)setLayoutKeylineWithInt:(jint)value {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"layout_keyline"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"setter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderSet" withId:JavaLangInteger_valueOfWithInt_(++orderSet_)];
  (void) [attrs putWithId:@"value" withId:JavaLangInteger_valueOfWithInt_(value)];
  return self;
}

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *)tryGetLayoutAnchorGravity {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"layout_anchorGravity"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"getter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderGet" withId:JavaLangInteger_valueOfWithInt_(++orderGet_)];
  return self;
}

- (id)getLayoutAnchorGravity {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"layout_anchorGravity"];
  return [((id<JavaUtilMap>) nil_chk(attrs)) getWithId:@"commandReturnValue"];
}

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *)setLayoutAnchorGravityWithNSString:(NSString *)value {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"layout_anchorGravity"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"setter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderSet" withId:JavaLangInteger_valueOfWithInt_(++orderSet_)];
  (void) [attrs putWithId:@"value" withId:value];
  return self;
}

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *)tryGetLayoutInsetEdge {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"layout_insetEdge"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"getter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderGet" withId:JavaLangInteger_valueOfWithInt_(++orderGet_)];
  return self;
}

- (id)getLayoutInsetEdge {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"layout_insetEdge"];
  return [((id<JavaUtilMap>) nil_chk(attrs)) getWithId:@"commandReturnValue"];
}

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *)setLayoutInsetEdgeWithNSString:(NSString *)value {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"layout_insetEdge"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"setter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderSet" withId:JavaLangInteger_valueOfWithInt_(++orderSet_)];
  (void) [attrs putWithId:@"value" withId:value];
  return self;
}

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *)tryGetLayoutDodgeInsetEdges {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"layout_dodgeInsetEdges"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"getter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderGet" withId:JavaLangInteger_valueOfWithInt_(++orderGet_)];
  return self;
}

- (id)getLayoutDodgeInsetEdges {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"layout_dodgeInsetEdges"];
  return [((id<JavaUtilMap>) nil_chk(attrs)) getWithId:@"commandReturnValue"];
}

- (ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *)setLayoutDodgeInsetEdgesWithNSString:(NSString *)value {
  id<JavaUtilMap> attrs = [self initCommandWithNSString:@"layout_dodgeInsetEdges"];
  (void) [((id<JavaUtilMap>) nil_chk(attrs)) putWithId:@"type" withId:@"attribute"];
  (void) [attrs putWithId:@"setter" withId:JavaLangBoolean_valueOfWithBoolean_(true)];
  (void) [attrs putWithId:@"orderSet" withId:JavaLangInteger_valueOfWithInt_(++orderSet_)];
  (void) [attrs putWithId:@"value" withId:value];
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "LASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder;", 0x1, 1, 2, -1, -1, -1, -1 },
    { NULL, "LASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder;", 0x1, 3, 2, -1, -1, -1, -1 },
    { NULL, "LASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder;", 0x1, 4, 2, -1, -1, -1, -1 },
    { NULL, "LASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder;", 0x1, 5, 6, -1, -1, -1, -1 },
    { NULL, "LASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder;", 0x1, 7, 2, -1, -1, -1, -1 },
    { NULL, "LASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder;", 0x1, 8, 2, -1, -1, -1, -1 },
    { NULL, "LASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder;", 0x1, 9, 2, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithASCoordinatorLayoutImpl:);
  methods[1].selector = @selector(tryGetLayoutGravity);
  methods[2].selector = @selector(getLayoutGravity);
  methods[3].selector = @selector(setLayoutGravityWithNSString:);
  methods[4].selector = @selector(setLayoutBehaviorWithNSString:);
  methods[5].selector = @selector(tryGetLayoutAnchor);
  methods[6].selector = @selector(getLayoutAnchor);
  methods[7].selector = @selector(setLayoutAnchorWithNSString:);
  methods[8].selector = @selector(tryGetLayoutKeyline);
  methods[9].selector = @selector(getLayoutKeyline);
  methods[10].selector = @selector(setLayoutKeylineWithInt:);
  methods[11].selector = @selector(tryGetLayoutAnchorGravity);
  methods[12].selector = @selector(getLayoutAnchorGravity);
  methods[13].selector = @selector(setLayoutAnchorGravityWithNSString:);
  methods[14].selector = @selector(tryGetLayoutInsetEdge);
  methods[15].selector = @selector(getLayoutInsetEdge);
  methods[16].selector = @selector(setLayoutInsetEdgeWithNSString:);
  methods[17].selector = @selector(tryGetLayoutDodgeInsetEdges);
  methods[18].selector = @selector(getLayoutDodgeInsetEdges);
  methods[19].selector = @selector(setLayoutDodgeInsetEdgesWithNSString:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LASCoordinatorLayoutImpl;", "setLayoutGravity", "LNSString;", "setLayoutBehavior", "setLayoutAnchor", "setLayoutKeyline", "I", "setLayoutAnchorGravity", "setLayoutInsetEdge", "setLayoutDodgeInsetEdges", "Lcom/ashera/layout/ViewGroupImpl$ViewGroupCommandParamsBuilder<Lcom/ashera/coordinatorlayout/CoordinatorLayoutImpl$CoordinatorLayoutCommandParamsBuilder;>;" };
  static const J2ObjcClassInfo _ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder = { "CoordinatorLayoutCommandParamsBuilder", "com.ashera.coordinatorlayout", ptrTable, methods, NULL, 7, 0x1, 20, 0, 0, -1, -1, 10, -1 };
  return &_ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder;
}

@end

void ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder_initWithASCoordinatorLayoutImpl_(ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *self, ASCoordinatorLayoutImpl *outer$) {
  ASViewGroupImpl_ViewGroupCommandParamsBuilder_init(self);
}

ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *new_ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder_initWithASCoordinatorLayoutImpl_(ASCoordinatorLayoutImpl *outer$) {
  J2OBJC_NEW_IMPL(ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder, initWithASCoordinatorLayoutImpl_, outer$)
}

ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder *create_ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder_initWithASCoordinatorLayoutImpl_(ASCoordinatorLayoutImpl *outer$) {
  J2OBJC_CREATE_IMPL(ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder, initWithASCoordinatorLayoutImpl_, outer$)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASCoordinatorLayoutImpl_CoordinatorLayoutCommandParamsBuilder)
