//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSCoordinatorLayoutPlugin\src\main\java\com\ashera\coordinatorlayout\CoordinatorLayoutPlugin.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_CoordinatorLayoutPlugin")
#ifdef RESTRICT_CoordinatorLayoutPlugin
#define INCLUDE_ALL_CoordinatorLayoutPlugin 0
#else
#define INCLUDE_ALL_CoordinatorLayoutPlugin 1
#endif
#undef RESTRICT_CoordinatorLayoutPlugin

#if !defined (ASCoordinatorLayoutPlugin_) && (INCLUDE_ALL_CoordinatorLayoutPlugin || defined(INCLUDE_ASCoordinatorLayoutPlugin))
#define ASCoordinatorLayoutPlugin_

@interface ASCoordinatorLayoutPlugin : NSObject

#pragma mark Public

- (instancetype)init;

+ (void)initPlugin OBJC_METHOD_FAMILY_NONE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCoordinatorLayoutPlugin)

FOUNDATION_EXPORT void ASCoordinatorLayoutPlugin_init(ASCoordinatorLayoutPlugin *self);

FOUNDATION_EXPORT ASCoordinatorLayoutPlugin *new_ASCoordinatorLayoutPlugin_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCoordinatorLayoutPlugin *create_ASCoordinatorLayoutPlugin_init(void);

FOUNDATION_EXPORT void ASCoordinatorLayoutPlugin_initPlugin(void);

J2OBJC_TYPE_LITERAL_HEADER(ASCoordinatorLayoutPlugin)

@compatibility_alias ComAsheraCoordinatorlayoutCoordinatorLayoutPlugin ASCoordinatorLayoutPlugin;


#endif

#pragma pop_macro("INCLUDE_ALL_CoordinatorLayoutPlugin")
