//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSCoordinatorLayoutPlugin\src\main\java\com\ashera\coordinatorlayout\CoordinatorLayoutImpl.java
//

#define J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION 1




#include "AbstractBitFlagConverter.h"
#include "AbstractEnumToIntConverter.h"
#include "BaseHasWidgets.h"
#include "BottomSheetBehavior.h"
#include "Context.h"
#include "ConverterFactory.h"
#include "CoordinatorLayout.h"
#include "CoordinatorLayoutImpl.h"
#include "DisplayMetrics.h"
#include "EventCommand.h"
#include "EventCommandFactory.h"
#include "EventExpressionParser.h"
#include "HasWidgets.h"
#include "IActivity.h"
#include "IFragment.h"
#include "ILifeCycleDecorator.h"
#include "IListener.h"
#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "IOSPrimitiveArray.h"
#include "IWidget.h"
#include "IWidgetLifeCycleListener.h"
#include "J2ObjC_source.h"
#include "LayoutTransition.h"
#include "MeasureEvent.h"
#include "OnLayoutEvent.h"
#include "PluginInvoker.h"
#include "Rect.h"
#include "Resources.h"
#include "View.h"
#include "ViewGroup.h"
#include "ViewGroupImpl.h"
#include "ViewImpl.h"
#include "WidgetAttribute.h"
#include "WidgetFactory.h"
#include "java/lang/Boolean.h"
#include "java/lang/Float.h"
#include "java/lang/Integer.h"
#include "java/lang/Runnable.h"
#include "java/lang/RuntimeException.h"
#include "java/lang/UnsupportedOperationException.h"
#include "java/util/HashMap.h"
#include "java/util/List.h"
#include "java/util/Map.h"

#include <UIKit/UIKit.h>
#include "ASUIView.h"
#include "HasLifeCycleDecorators.h"


@class NSString;


#pragma clang diagnostic error "-Wreturn-type"
#pragma clang diagnostic ignored "-Wswitch"


#pragma clang diagnostic ignored "-Wprotocol"

@interface ASCoordinatorLayoutImpl () {
 @public
  id uiView_;
  ADXCoordinatorLayout *coordinatorLayout_;
  ADXBottomSheetBehavior_BottomSheetCallback *onSlideCallBack_;
  ADXBottomSheetBehavior_BottomSheetCallback *onStateChangeCallBack_;
}

- (void)setWidgetOnNativeClass;

- (void)nativeRemoveViewWithASIWidget:(id<ASIWidget>)widget;

- (void)createLayoutParamsWithADView:(ADView *)view;

- (ADXCoordinatorLayout_LayoutParams *)getLayoutParamsWithADView:(ADView *)view;

- (void)setBehaviorWithADXCoordinatorLayout_LayoutParams:(ADXCoordinatorLayout_LayoutParams *)layoutParams
                                                  withId:(id)objValue;

- (void)setKeyLinesWithId:(id)objValue;

- (void)setBehaviorSignificantVelocityThresholdWithADXCoordinatorLayout_LayoutParams:(ADXCoordinatorLayout_LayoutParams *)layoutParams
                                                                              withId:(id)objValue;

- (void)setBehaviorExpandedOffsetWithADXCoordinatorLayout_LayoutParams:(ADXCoordinatorLayout_LayoutParams *)layoutParams
                                                                withId:(id)objValue;

- (void)setBehaviorHalfExpandedRatioWithADXCoordinatorLayout_LayoutParams:(ADXCoordinatorLayout_LayoutParams *)layoutParams
                                                                   withId:(id)objValue;

- (void)setBehaviorDraggableWithADXCoordinatorLayout_LayoutParams:(ADXCoordinatorLayout_LayoutParams *)layoutParams
                                                           withId:(id)objValue;

- (void)setBehaviorSkipCollapsedWithADXCoordinatorLayout_LayoutParams:(ADXCoordinatorLayout_LayoutParams *)layoutParams
                                                               withId:(id)objValue;

- (void)setBehaviorHideableWithADXCoordinatorLayout_LayoutParams:(ADXCoordinatorLayout_LayoutParams *)layoutParams
                                                          withId:(id)objValue;

- (void)setBehaviorFitToContentsWithADXCoordinatorLayout_LayoutParams:(ADXCoordinatorLayout_LayoutParams *)layoutParams
                                                               withId:(id)objValue;

- (void)setBehaviorPeekHeightWithADXCoordinatorLayout_LayoutParams:(ADXCoordinatorLayout_LayoutParams *)layoutParams
                                                            withId:(id)objValue;

- (void)setOnSlideWithADXCoordinatorLayout_LayoutParams:(ADXCoordinatorLayout_LayoutParams *)layoutParams
                                                 withId:(id)objValue;

- (void)setOnStateChangedWithADXCoordinatorLayout_LayoutParams:(ADXCoordinatorLayout_LayoutParams *)layoutParams
                                                        withId:(id)objValue;

- (void)setBehaviorStateWithADXCoordinatorLayout_LayoutParams:(ADXCoordinatorLayout_LayoutParams *)layoutParams
                                                       withId:(id)objValue;

- (void)setMyKeyLinesWithIntArray:(IOSIntArray *)keyLines;

- (void)onChildViewsChanged;

@end

J2OBJC_FIELD_SETTER(ASCoordinatorLayoutImpl, uiView_, id)
J2OBJC_FIELD_SETTER(ASCoordinatorLayoutImpl, coordinatorLayout_, ADXCoordinatorLayout *)
J2OBJC_FIELD_SETTER(ASCoordinatorLayoutImpl, onSlideCallBack_, ADXBottomSheetBehavior_BottomSheetCallback *)
J2OBJC_FIELD_SETTER(ASCoordinatorLayoutImpl, onStateChangeCallBack_, ADXBottomSheetBehavior_BottomSheetCallback *)

__attribute__((unused)) static void ASCoordinatorLayoutImpl_setWidgetOnNativeClass(ASCoordinatorLayoutImpl *self);

__attribute__((unused)) static void ASCoordinatorLayoutImpl_nativeRemoveViewWithASIWidget_(ASCoordinatorLayoutImpl *self, id<ASIWidget> widget);

__attribute__((unused)) static void ASCoordinatorLayoutImpl_createLayoutParamsWithADView_(ASCoordinatorLayoutImpl *self, ADView *view);

__attribute__((unused)) static ADXCoordinatorLayout_LayoutParams *ASCoordinatorLayoutImpl_getLayoutParamsWithADView_(ASCoordinatorLayoutImpl *self, ADView *view);

__attribute__((unused)) static void ASCoordinatorLayoutImpl_setBehaviorWithADXCoordinatorLayout_LayoutParams_withId_(ASCoordinatorLayoutImpl *self, ADXCoordinatorLayout_LayoutParams *layoutParams, id objValue);

__attribute__((unused)) static void ASCoordinatorLayoutImpl_setKeyLinesWithId_(ASCoordinatorLayoutImpl *self, id objValue);

__attribute__((unused)) static void ASCoordinatorLayoutImpl_setBehaviorSignificantVelocityThresholdWithADXCoordinatorLayout_LayoutParams_withId_(ASCoordinatorLayoutImpl *self, ADXCoordinatorLayout_LayoutParams *layoutParams, id objValue);

__attribute__((unused)) static void ASCoordinatorLayoutImpl_setBehaviorExpandedOffsetWithADXCoordinatorLayout_LayoutParams_withId_(ASCoordinatorLayoutImpl *self, ADXCoordinatorLayout_LayoutParams *layoutParams, id objValue);

__attribute__((unused)) static void ASCoordinatorLayoutImpl_setBehaviorHalfExpandedRatioWithADXCoordinatorLayout_LayoutParams_withId_(ASCoordinatorLayoutImpl *self, ADXCoordinatorLayout_LayoutParams *layoutParams, id objValue);

__attribute__((unused)) static void ASCoordinatorLayoutImpl_setBehaviorDraggableWithADXCoordinatorLayout_LayoutParams_withId_(ASCoordinatorLayoutImpl *self, ADXCoordinatorLayout_LayoutParams *layoutParams, id objValue);

__attribute__((unused)) static void ASCoordinatorLayoutImpl_setBehaviorSkipCollapsedWithADXCoordinatorLayout_LayoutParams_withId_(ASCoordinatorLayoutImpl *self, ADXCoordinatorLayout_LayoutParams *layoutParams, id objValue);

__attribute__((unused)) static void ASCoordinatorLayoutImpl_setBehaviorHideableWithADXCoordinatorLayout_LayoutParams_withId_(ASCoordinatorLayoutImpl *self, ADXCoordinatorLayout_LayoutParams *layoutParams, id objValue);

__attribute__((unused)) static void ASCoordinatorLayoutImpl_setBehaviorFitToContentsWithADXCoordinatorLayout_LayoutParams_withId_(ASCoordinatorLayoutImpl *self, ADXCoordinatorLayout_LayoutParams *layoutParams, id objValue);

__attribute__((unused)) static void ASCoordinatorLayoutImpl_setBehaviorPeekHeightWithADXCoordinatorLayout_LayoutParams_withId_(ASCoordinatorLayoutImpl *self, ADXCoordinatorLayout_LayoutParams *layoutParams, id objValue);

__attribute__((unused)) static void ASCoordinatorLayoutImpl_setOnSlideWithADXCoordinatorLayout_LayoutParams_withId_(ASCoordinatorLayoutImpl *self, ADXCoordinatorLayout_LayoutParams *layoutParams, id objValue);

__attribute__((unused)) static void ASCoordinatorLayoutImpl_setOnStateChangedWithADXCoordinatorLayout_LayoutParams_withId_(ASCoordinatorLayoutImpl *self, ADXCoordinatorLayout_LayoutParams *layoutParams, id objValue);

__attribute__((unused)) static void ASCoordinatorLayoutImpl_setBehaviorStateWithADXCoordinatorLayout_LayoutParams_withId_(ASCoordinatorLayoutImpl *self, ADXCoordinatorLayout_LayoutParams *layoutParams, id objValue);

__attribute__((unused)) static void ASCoordinatorLayoutImpl_setMyKeyLinesWithIntArray_(ASCoordinatorLayoutImpl *self, IOSIntArray *keyLines);

__attribute__((unused)) static void ASCoordinatorLayoutImpl_onChildViewsChanged(ASCoordinatorLayoutImpl *self);

@interface ASCoordinatorLayoutImpl_InsetEdge () {
 @public
  id<JavaUtilMap> mapping_;
}

@end

J2OBJC_FIELD_SETTER(ASCoordinatorLayoutImpl_InsetEdge, mapping_, id<JavaUtilMap>)

@interface ASCoordinatorLayoutImpl_DodgeInsetEdge () {
 @public
  id<JavaUtilMap> mapping_;
}

@end

J2OBJC_FIELD_SETTER(ASCoordinatorLayoutImpl_DodgeInsetEdge, mapping_, id<JavaUtilMap>)

@interface ASCoordinatorLayoutImpl_BehaviorState () {
 @public
  id<JavaUtilMap> mapping_;
}

@end

J2OBJC_FIELD_SETTER(ASCoordinatorLayoutImpl_BehaviorState, mapping_, id<JavaUtilMap>)

@interface ASCoordinatorLayoutImpl_CoordinatorLayoutExt () {
 @public
  WEAK_ ASCoordinatorLayoutImpl *this$0_;
  ASMeasureEvent *measureFinished_;
  ASOnLayoutEvent *onLayoutEvent_;
  id<JavaUtilList> overlays_;
  int32_t mMaxWidth_;
  int32_t mMaxHeight_;
  id<JavaUtilMap> templates_;
}

@end

J2OBJC_FIELD_SETTER(ASCoordinatorLayoutImpl_CoordinatorLayoutExt, measureFinished_, ASMeasureEvent *)
J2OBJC_FIELD_SETTER(ASCoordinatorLayoutImpl_CoordinatorLayoutExt, onLayoutEvent_, ASOnLayoutEvent *)
J2OBJC_FIELD_SETTER(ASCoordinatorLayoutImpl_CoordinatorLayoutExt, overlays_, id<JavaUtilList>)
J2OBJC_FIELD_SETTER(ASCoordinatorLayoutImpl_CoordinatorLayoutExt, templates_, id<JavaUtilMap>)

@interface ASCoordinatorLayoutImpl_BottomSheetCallback : ADXBottomSheetBehavior_BottomSheetCallback < ASIListener > {
 @public
  id<ASIWidget> w_;
  ADView *view_;
  NSString *strValue_;
  NSString *action_;
}

- (NSString *)getAction;

- (instancetype)initWithASIWidget:(id<ASIWidget>)w
                     withNSString:(NSString *)strValue;

- (instancetype)initWithASIWidget:(id<ASIWidget>)w
                     withNSString:(NSString *)strValue
                     withNSString:(NSString *)action;

- (void)onStateChangedWithADView:(ADView *)bottomSheet
                         withInt:(int32_t)newState;

- (id<JavaUtilMap>)getOnStateChangedEventObjWithADView:(ADView *)bottomSheet
                                               withInt:(int32_t)newState;

- (void)onSlideWithADView:(ADView *)bottomSheet
                withFloat:(float)slideOffset;

- (id<JavaUtilMap>)getOnSlideEventObjWithADView:(ADView *)bottomSheet
                                      withFloat:(float)slideOffset;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCoordinatorLayoutImpl_BottomSheetCallback)

J2OBJC_FIELD_SETTER(ASCoordinatorLayoutImpl_BottomSheetCallback, w_, id<ASIWidget>)
J2OBJC_FIELD_SETTER(ASCoordinatorLayoutImpl_BottomSheetCallback, view_, ADView *)
J2OBJC_FIELD_SETTER(ASCoordinatorLayoutImpl_BottomSheetCallback, strValue_, NSString *)
J2OBJC_FIELD_SETTER(ASCoordinatorLayoutImpl_BottomSheetCallback, action_, NSString *)

__attribute__((unused)) static void ASCoordinatorLayoutImpl_BottomSheetCallback_initWithASIWidget_withNSString_(ASCoordinatorLayoutImpl_BottomSheetCallback *self, id<ASIWidget> w, NSString *strValue);

__attribute__((unused)) static ASCoordinatorLayoutImpl_BottomSheetCallback *new_ASCoordinatorLayoutImpl_BottomSheetCallback_initWithASIWidget_withNSString_(id<ASIWidget> w, NSString *strValue) NS_RETURNS_RETAINED;

__attribute__((unused)) static ASCoordinatorLayoutImpl_BottomSheetCallback *create_ASCoordinatorLayoutImpl_BottomSheetCallback_initWithASIWidget_withNSString_(id<ASIWidget> w, NSString *strValue);

__attribute__((unused)) static void ASCoordinatorLayoutImpl_BottomSheetCallback_initWithASIWidget_withNSString_withNSString_(ASCoordinatorLayoutImpl_BottomSheetCallback *self, id<ASIWidget> w, NSString *strValue, NSString *action);

__attribute__((unused)) static ASCoordinatorLayoutImpl_BottomSheetCallback *new_ASCoordinatorLayoutImpl_BottomSheetCallback_initWithASIWidget_withNSString_withNSString_(id<ASIWidget> w, NSString *strValue, NSString *action) NS_RETURNS_RETAINED;

__attribute__((unused)) static ASCoordinatorLayoutImpl_BottomSheetCallback *create_ASCoordinatorLayoutImpl_BottomSheetCallback_initWithASIWidget_withNSString_withNSString_(id<ASIWidget> w, NSString *strValue, NSString *action);

J2OBJC_TYPE_LITERAL_HEADER(ASCoordinatorLayoutImpl_BottomSheetCallback)


@interface ASCoordinatorLayoutImpl_$Lambda$1 : NSObject < JavaLangRunnable > {
 @public
  id<ASIWidget> val$widget_;
}

- (void)run;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCoordinatorLayoutImpl_$Lambda$1)

__attribute__((unused)) static void ASCoordinatorLayoutImpl_$Lambda$1_initWithASIWidget_(ASCoordinatorLayoutImpl_$Lambda$1 *self, id<ASIWidget> capture$0);

__attribute__((unused)) static ASCoordinatorLayoutImpl_$Lambda$1 *new_ASCoordinatorLayoutImpl_$Lambda$1_initWithASIWidget_(id<ASIWidget> capture$0) NS_RETURNS_RETAINED;

__attribute__((unused)) static ASCoordinatorLayoutImpl_$Lambda$1 *create_ASCoordinatorLayoutImpl_$Lambda$1_initWithASIWidget_(id<ASIWidget> capture$0);


NSString *ASCoordinatorLayoutImpl_LOCAL_NAME = @"androidx.coordinatorlayout.widget.CoordinatorLayout";
NSString *ASCoordinatorLayoutImpl_GROUP_NAME = @"androidx.coordinatorlayout.widget.CoordinatorLayout";

@implementation ASCoordinatorLayoutImpl

@synthesize uiView = uiView_;

- (void)loadAttributesWithNSString:(NSString *)localName {
  ASViewGroupImpl_register__WithNSString_(localName);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"keylines"])) withTypeWithNSString:@"array"])) withArrayTypeWithNSString:@"int"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"childViewsChanged"])) withTypeWithNSString:@"nil"]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"layout_gravity"])) withTypeWithNSString:@"gravity"])) forChild]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"layout_behavior"])) withTypeWithNSString:@"string"])) forChild]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"layout_anchor"])) withTypeWithNSString:@"id"])) forChild]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"layout_keyline"])) withTypeWithNSString:@"int"])) forChild]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"layout_anchorGravity"])) withTypeWithNSString:@"gravity"])) forChild]);
  ASConverterFactory_register__WithNSString_withASIConverter_(@"androidx.coordinatorlayout.widget.CoordinatorLayout.insetEdge", new_ASCoordinatorLayoutImpl_InsetEdge_init());
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"layout_insetEdge"])) withTypeWithNSString:@"androidx.coordinatorlayout.widget.CoordinatorLayout.insetEdge"])) forChild]);
  ASConverterFactory_register__WithNSString_withASIConverter_(@"androidx.coordinatorlayout.widget.CoordinatorLayout.dodgeInsetEdge", new_ASCoordinatorLayoutImpl_DodgeInsetEdge_init());
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"layout_dodgeInsetEdges"])) withTypeWithNSString:@"androidx.coordinatorlayout.widget.CoordinatorLayout.dodgeInsetEdge"])) forChild]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"layout_behavior_fitToContents"])) withTypeWithNSString:@"boolean"])) withOrderWithInt:200])) forChild]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"layout_behavior_peekHeight"])) withTypeWithNSString:@"dimension"])) withOrderWithInt:200])) forChild]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"layout_behavior_hideable"])) withTypeWithNSString:@"boolean"])) withOrderWithInt:200])) forChild]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"layout_behavior_skipCollapsed"])) withTypeWithNSString:@"boolean"])) withOrderWithInt:200])) forChild]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"layout_behavior_draggable"])) withTypeWithNSString:@"boolean"])) withOrderWithInt:200])) forChild]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"layout_behavior_halfExpandedRatio"])) withTypeWithNSString:@"float"])) withOrderWithInt:200])) forChild]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"layout_behavior_expandedOffset"])) withTypeWithNSString:@"dimension"])) withOrderWithInt:200])) forChild]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"layout_behavior_significantVelocityThreshold"])) withTypeWithNSString:@"dimension"])) withOrderWithInt:200])) forChild]);
  ASConverterFactory_register__WithNSString_withASIConverter_(@"androidx.coordinatorlayout.widget.CoordinatorLayout.behaviorState", new_ASCoordinatorLayoutImpl_BehaviorState_init());
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"layout_behavior_state"])) withTypeWithNSString:@"androidx.coordinatorlayout.widget.CoordinatorLayout.behaviorState"])) withOrderWithInt:200])) forChild]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"layout_behavior_onStateChanged"])) withTypeWithNSString:@"string"])) forChild]);
  ASWidgetFactory_registerAttributeWithNSString_withASWidgetAttribute_Builder_(localName, [((ASWidgetAttribute_Builder *) nil_chk([((ASWidgetAttribute_Builder *) nil_chk([new_ASWidgetAttribute_Builder_init() withNameWithNSString:@"layout_behavior_onSlide"])) withTypeWithNSString:@"string"])) forChild]);
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ASCoordinatorLayoutImpl_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (instancetype)initWithNSString:(NSString *)localname {
  ASCoordinatorLayoutImpl_initWithNSString_(self, localname);
  return self;
}

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname {
  ASCoordinatorLayoutImpl_initWithNSString_withNSString_(self, groupName, localname);
  return self;
}

- (id<ASIWidget>)newInstance {
  return new_ASCoordinatorLayoutImpl_initWithNSString_withNSString_(groupName_, localName_);
}

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params {
  [super createWithASIFragment:fragment withJavaUtilMap:params];
  coordinatorLayout_ = new_ASCoordinatorLayoutImpl_CoordinatorLayoutExt_initWithASCoordinatorLayoutImpl_(self);
  [self nativeCreateWithJavaUtilMap:params];
  ASViewGroupImpl_registerCommandConveterWithASIWidget_(self);
  ASCoordinatorLayoutImpl_setWidgetOnNativeClass(self);
}

- (void)setWidgetOnNativeClass {
  ASCoordinatorLayoutImpl_setWidgetOnNativeClass(self);
}

- (id)asWidget {
  return coordinatorLayout_;
}

- (bool)removeWithASIWidget:(id<ASIWidget>)w {
  bool remove = [super removeWithASIWidget:w];
  [((ADXCoordinatorLayout *) nil_chk(coordinatorLayout_)) removeViewWithADView:(ADView *) cast_chk([((id<ASIWidget>) nil_chk(w)) asWidget], [ADView class])];
  ASCoordinatorLayoutImpl_nativeRemoveViewWithASIWidget_(self, w);
  return remove;
}

- (bool)removeWithInt:(int32_t)index {
  id<ASIWidget> widget = [((id<JavaUtilList>) nil_chk(widgets_)) getWithInt:index];
  bool remove = [super removeWithInt:index];
  if (index + 1 <= [((ADXCoordinatorLayout *) nil_chk(coordinatorLayout_)) getChildCount]) {
    [((ADXCoordinatorLayout *) nil_chk(coordinatorLayout_)) removeViewAtWithInt:index];
    ASCoordinatorLayoutImpl_nativeRemoveViewWithASIWidget_(self, widget);
  }
  return remove;
}

- (void)nativeRemoveViewWithASIWidget:(id<ASIWidget>)widget {
  ASCoordinatorLayoutImpl_nativeRemoveViewWithASIWidget_(self, widget);
}

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(int32_t)index {
  if (index != -2) {
    ADView *view = (ADView *) cast_chk([((id<ASIWidget>) nil_chk(w)) asWidget], [ADView class]);
    ASCoordinatorLayoutImpl_createLayoutParamsWithADView_(self, view);
    if (index == -1) {
      [((ADXCoordinatorLayout *) nil_chk(coordinatorLayout_)) addViewWithADView:view];
    }
    else {
      [((ADXCoordinatorLayout *) nil_chk(coordinatorLayout_)) addViewWithADView:view withInt:index];
    }
  }
  ASViewGroupImpl_nativeAddViewWithId_withId_([self asNativeWidget], [((id<ASIWidget>) nil_chk(w)) asNativeWidget]);
  [super addWithASIWidget:w withInt:index];
}

- (void)createLayoutParamsWithADView:(ADView *)view {
  ASCoordinatorLayoutImpl_createLayoutParamsWithADView_(self, view);
}

- (ADXCoordinatorLayout_LayoutParams *)getLayoutParamsWithADView:(ADView *)view {
  return ASCoordinatorLayoutImpl_getLayoutParamsWithADView_(self, view);
}

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue {
  ADView *view = (ADView *) cast_chk([((id<ASIWidget>) nil_chk(w)) asWidget], [ADView class]);
  ADXCoordinatorLayout_LayoutParams *layoutParams = ASCoordinatorLayoutImpl_getLayoutParamsWithADView_(self, view);
  ASViewGroupImpl_setChildAttributeWithASIWidget_withASWidgetAttribute_withId_withId_(w, key, objValue, layoutParams);
  switch (JreIndexOfStr([((ASWidgetAttribute *) nil_chk(key)) getAttributeName], (id[]){ @"layout_width", @"layout_height", @"layout_gravity", @"layout_behavior", @"layout_anchor", @"layout_keyline", @"layout_anchorGravity", @"layout_insetEdge", @"layout_dodgeInsetEdges", @"layout_behavior_fitToContents", @"layout_behavior_peekHeight", @"layout_behavior_hideable", @"layout_behavior_skipCollapsed", @"layout_behavior_draggable", @"layout_behavior_halfExpandedRatio", @"layout_behavior_expandedOffset", @"layout_behavior_significantVelocityThreshold", @"layout_behavior_state", @"layout_behavior_onStateChanged", @"layout_behavior_onSlide" }, 20)) {
    case 0:
    ((ADXCoordinatorLayout_LayoutParams *) nil_chk(layoutParams))->width_ = [((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class]))) intValue];
    break;
    case 1:
    ((ADXCoordinatorLayout_LayoutParams *) nil_chk(layoutParams))->height_ = [((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class]))) intValue];
    break;
    case 2:
    {
      ((ADXCoordinatorLayout_LayoutParams *) nil_chk(layoutParams))->gravity_ = [((JavaLangInteger *) nil_chk(((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class])))) intValue];
    }
    break;
    case 3:
    {
      ASCoordinatorLayoutImpl_setBehaviorWithADXCoordinatorLayout_LayoutParams_withId_(self, layoutParams, objValue);
    }
    break;
    case 4:
    {
      [((ADXCoordinatorLayout_LayoutParams *) nil_chk(layoutParams)) setAnchorIdWithInt:[((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class]))) intValue]];
    }
    break;
    case 5:
    {
      ((ADXCoordinatorLayout_LayoutParams *) nil_chk(layoutParams))->keyline_ = [((JavaLangInteger *) nil_chk(((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class])))) intValue];
    }
    break;
    case 6:
    {
      ((ADXCoordinatorLayout_LayoutParams *) nil_chk(layoutParams))->anchorGravity_ = [((JavaLangInteger *) nil_chk(((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class])))) intValue];
    }
    break;
    case 7:
    {
      ((ADXCoordinatorLayout_LayoutParams *) nil_chk(layoutParams))->insetEdge_ = [((JavaLangInteger *) nil_chk(((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class])))) intValue];
    }
    break;
    case 8:
    {
      ((ADXCoordinatorLayout_LayoutParams *) nil_chk(layoutParams))->dodgeInsetEdges_ = [((JavaLangInteger *) nil_chk(((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class])))) intValue];
    }
    break;
    case 9:
    {
      ASCoordinatorLayoutImpl_setBehaviorFitToContentsWithADXCoordinatorLayout_LayoutParams_withId_(self, layoutParams, objValue);
    }
    break;
    case 10:
    {
      ASCoordinatorLayoutImpl_setBehaviorPeekHeightWithADXCoordinatorLayout_LayoutParams_withId_(self, layoutParams, objValue);
    }
    break;
    case 11:
    {
      ASCoordinatorLayoutImpl_setBehaviorHideableWithADXCoordinatorLayout_LayoutParams_withId_(self, layoutParams, objValue);
    }
    break;
    case 12:
    {
      ASCoordinatorLayoutImpl_setBehaviorSkipCollapsedWithADXCoordinatorLayout_LayoutParams_withId_(self, layoutParams, objValue);
    }
    break;
    case 13:
    {
      ASCoordinatorLayoutImpl_setBehaviorDraggableWithADXCoordinatorLayout_LayoutParams_withId_(self, layoutParams, objValue);
    }
    break;
    case 14:
    {
      ASCoordinatorLayoutImpl_setBehaviorHalfExpandedRatioWithADXCoordinatorLayout_LayoutParams_withId_(self, layoutParams, objValue);
    }
    break;
    case 15:
    {
      ASCoordinatorLayoutImpl_setBehaviorExpandedOffsetWithADXCoordinatorLayout_LayoutParams_withId_(self, layoutParams, objValue);
    }
    break;
    case 16:
    {
      ASCoordinatorLayoutImpl_setBehaviorSignificantVelocityThresholdWithADXCoordinatorLayout_LayoutParams_withId_(self, layoutParams, objValue);
    }
    break;
    case 17:
    {
      ASCoordinatorLayoutImpl_setBehaviorStateWithADXCoordinatorLayout_LayoutParams_withId_(self, layoutParams, objValue);
    }
    break;
    case 18:
    {
      ASCoordinatorLayoutImpl_setOnStateChangedWithADXCoordinatorLayout_LayoutParams_withId_(self, layoutParams, objValue);
    }
    break;
    case 19:
    {
      ASCoordinatorLayoutImpl_setOnSlideWithADXCoordinatorLayout_LayoutParams_withId_(self, layoutParams, objValue);
    }
    break;
    default:
    break;
  }
  [((ADView *) nil_chk(view)) setLayoutParamsWithADViewGroup_LayoutParams:layoutParams];
}

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key {
  id attributeValue = ASViewGroupImpl_getChildAttributeWithASIWidget_withASWidgetAttribute_(w, key);
  if (attributeValue != nil) {
    return attributeValue;
  }
  ADView *view = (ADView *) cast_chk([((id<ASIWidget>) nil_chk(w)) asWidget], [ADView class]);
  ADXCoordinatorLayout_LayoutParams *layoutParams = ASCoordinatorLayoutImpl_getLayoutParamsWithADView_(self, view);
  switch (JreIndexOfStr([((ASWidgetAttribute *) nil_chk(key)) getAttributeName], (id[]){ @"layout_width", @"layout_height", @"layout_gravity", @"layout_anchor", @"layout_keyline", @"layout_anchorGravity", @"layout_insetEdge", @"layout_dodgeInsetEdges" }, 8)) {
    case 0:
    return JavaLangInteger_valueOfWithInt_(((ADXCoordinatorLayout_LayoutParams *) nil_chk(layoutParams))->width_);
    case 1:
    return JavaLangInteger_valueOfWithInt_(((ADXCoordinatorLayout_LayoutParams *) nil_chk(layoutParams))->height_);
    case 2:
    {
      return JavaLangInteger_valueOfWithInt_(((ADXCoordinatorLayout_LayoutParams *) nil_chk(layoutParams))->gravity_);
    }
    case 3:
    {
      return JavaLangInteger_valueOfWithInt_([((ADXCoordinatorLayout_LayoutParams *) nil_chk(layoutParams)) getAnchorId]);
    }
    case 4:
    {
      return JavaLangInteger_valueOfWithInt_(((ADXCoordinatorLayout_LayoutParams *) nil_chk(layoutParams))->keyline_);
    }
    case 5:
    {
      return JavaLangInteger_valueOfWithInt_(((ADXCoordinatorLayout_LayoutParams *) nil_chk(layoutParams))->anchorGravity_);
    }
    case 6:
    {
      return JavaLangInteger_valueOfWithInt_(((ADXCoordinatorLayout_LayoutParams *) nil_chk(layoutParams))->insetEdge_);
    }
    case 7:
    {
      return JavaLangInteger_valueOfWithInt_(((ADXCoordinatorLayout_LayoutParams *) nil_chk(layoutParams))->dodgeInsetEdges_);
    }
  }
  return nil;
}

- (IOSClass *)getViewClass {
  return ASCoordinatorLayoutImpl_CoordinatorLayoutExt_class_();
}

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator {
  ASViewGroupImpl_setAttributeWithASIWidget_withASWidgetAttribute_withNSString_withId_withASILifeCycleDecorator_(self, key, strValue, objValue, decorator);
  id nativeWidget = [self asNativeWidget];
  switch (JreIndexOfStr([((ASWidgetAttribute *) nil_chk(key)) getAttributeName], (id[]){ @"keylines", @"childViewsChanged" }, 2)) {
    case 0:
    {
      ASCoordinatorLayoutImpl_setKeyLinesWithId_(self, objValue);
    }
    break;
    case 1:
    {
      ASCoordinatorLayoutImpl_onChildViewsChanged(self);
    }
    break;
    default:
    break;
  }
}

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator {
  id attributeValue = ASViewGroupImpl_getAttributeWithASIWidget_withASWidgetAttribute_withASILifeCycleDecorator_(self, key, decorator);
  if (attributeValue != nil) {
    return attributeValue;
  }
  id nativeWidget = [self asNativeWidget];
  switch (JreIndexOfStr([((ASWidgetAttribute *) nil_chk(key)) getAttributeName], (id[]){  }, 0)) {
  }
  return nil;
}

- (id)asNativeWidget {
  return uiView_;
}

- (bool)checkIosVersionWithNSString:(NSString *)v {
  return ([[[UIDevice currentDevice] systemVersion] compare:v options:NSNumericSearch] == NSOrderedDescending);
}

- (void)nativeCreateWithJavaUtilMap:(id<JavaUtilMap>)params {
  ASUIView* uiView = [ASUIView new];
  uiView.backgroundColor = [UIColor clearColor];
  uiView_ = uiView;
}

- (void)requestLayout {
  if ([self isInitialised]) {
    ASViewImpl_requestLayoutWithASIWidget_withId_(self, [self asNativeWidget]);
  }
}

- (void)invalidate {
  if ([self isInitialised]) {
    ASViewImpl_invalidateWithASIWidget_withId_(self, [self asNativeWidget]);
  }
}

- (void)setBehaviorWithADXCoordinatorLayout_LayoutParams:(ADXCoordinatorLayout_LayoutParams *)layoutParams
                                                  withId:(id)objValue {
  ASCoordinatorLayoutImpl_setBehaviorWithADXCoordinatorLayout_LayoutParams_withId_(self, layoutParams, objValue);
}

- (void)setKeyLinesWithId:(id)objValue {
  ASCoordinatorLayoutImpl_setKeyLinesWithId_(self, objValue);
}

- (void)setBehaviorSignificantVelocityThresholdWithADXCoordinatorLayout_LayoutParams:(ADXCoordinatorLayout_LayoutParams *)layoutParams
                                                                              withId:(id)objValue {
  ASCoordinatorLayoutImpl_setBehaviorSignificantVelocityThresholdWithADXCoordinatorLayout_LayoutParams_withId_(self, layoutParams, objValue);
}

- (void)setBehaviorExpandedOffsetWithADXCoordinatorLayout_LayoutParams:(ADXCoordinatorLayout_LayoutParams *)layoutParams
                                                                withId:(id)objValue {
  ASCoordinatorLayoutImpl_setBehaviorExpandedOffsetWithADXCoordinatorLayout_LayoutParams_withId_(self, layoutParams, objValue);
}

- (void)setBehaviorHalfExpandedRatioWithADXCoordinatorLayout_LayoutParams:(ADXCoordinatorLayout_LayoutParams *)layoutParams
                                                                   withId:(id)objValue {
  ASCoordinatorLayoutImpl_setBehaviorHalfExpandedRatioWithADXCoordinatorLayout_LayoutParams_withId_(self, layoutParams, objValue);
}

- (void)setBehaviorDraggableWithADXCoordinatorLayout_LayoutParams:(ADXCoordinatorLayout_LayoutParams *)layoutParams
                                                           withId:(id)objValue {
  ASCoordinatorLayoutImpl_setBehaviorDraggableWithADXCoordinatorLayout_LayoutParams_withId_(self, layoutParams, objValue);
}

- (void)setBehaviorSkipCollapsedWithADXCoordinatorLayout_LayoutParams:(ADXCoordinatorLayout_LayoutParams *)layoutParams
                                                               withId:(id)objValue {
  ASCoordinatorLayoutImpl_setBehaviorSkipCollapsedWithADXCoordinatorLayout_LayoutParams_withId_(self, layoutParams, objValue);
}

- (void)setBehaviorHideableWithADXCoordinatorLayout_LayoutParams:(ADXCoordinatorLayout_LayoutParams *)layoutParams
                                                          withId:(id)objValue {
  ASCoordinatorLayoutImpl_setBehaviorHideableWithADXCoordinatorLayout_LayoutParams_withId_(self, layoutParams, objValue);
}

- (void)setBehaviorFitToContentsWithADXCoordinatorLayout_LayoutParams:(ADXCoordinatorLayout_LayoutParams *)layoutParams
                                                               withId:(id)objValue {
  ASCoordinatorLayoutImpl_setBehaviorFitToContentsWithADXCoordinatorLayout_LayoutParams_withId_(self, layoutParams, objValue);
}

- (void)setBehaviorPeekHeightWithADXCoordinatorLayout_LayoutParams:(ADXCoordinatorLayout_LayoutParams *)layoutParams
                                                            withId:(id)objValue {
  ASCoordinatorLayoutImpl_setBehaviorPeekHeightWithADXCoordinatorLayout_LayoutParams_withId_(self, layoutParams, objValue);
}

- (void)setOnSlideWithADXCoordinatorLayout_LayoutParams:(ADXCoordinatorLayout_LayoutParams *)layoutParams
                                                 withId:(id)objValue {
  ASCoordinatorLayoutImpl_setOnSlideWithADXCoordinatorLayout_LayoutParams_withId_(self, layoutParams, objValue);
}

- (void)setOnStateChangedWithADXCoordinatorLayout_LayoutParams:(ADXCoordinatorLayout_LayoutParams *)layoutParams
                                                        withId:(id)objValue {
  ASCoordinatorLayoutImpl_setOnStateChangedWithADXCoordinatorLayout_LayoutParams_withId_(self, layoutParams, objValue);
}

- (void)setBehaviorStateWithADXCoordinatorLayout_LayoutParams:(ADXCoordinatorLayout_LayoutParams *)layoutParams
                                                       withId:(id)objValue {
  ASCoordinatorLayoutImpl_setBehaviorStateWithADXCoordinatorLayout_LayoutParams_withId_(self, layoutParams, objValue);
}

- (void)setMyKeyLinesWithIntArray:(IOSIntArray *)keyLines {
  ASCoordinatorLayoutImpl_setMyKeyLinesWithIntArray_(self, keyLines);
}

- (void)onChildViewsChanged {
  ASCoordinatorLayoutImpl_onChildViewsChanged(self);
}

- (void)setIdWithNSString:(NSString *)id_ {
  if (id_ != nil && ![id_ isEqual:@""]) {
    [super setIdWithNSString:id_];
    [((ADXCoordinatorLayout *) nil_chk(coordinatorLayout_)) setIdWithInt:[((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk([self quickConvertWithId:id_ withNSString:@"id"], [JavaLangInteger class]))) intValue]];
  }
}

- (void)setVisibleWithBoolean:(bool)b {
  [((ADView *) nil_chk(((ADView *) cast_chk([self asWidget], [ADView class])))) setVisibilityWithInt:b ? ADView_VISIBLE : ADView_GONE];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "V", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 2, -1, -1, -1, -1 },
    { NULL, "LASIWidget;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 3, 4, -1, 5, -1, -1 },
    { NULL, "V", 0x102, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, 6, 7, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, 6, 8, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 9, 7, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 10, 11, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 12, 13, -1, -1, -1, -1 },
    { NULL, "LADXCoordinatorLayout_LayoutParams;", 0x2, 14, 13, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 15, 16, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 17, 18, -1, -1, -1, -1 },
    { NULL, "LIOSClass;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 19, 20, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 21, 22, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x101, 23, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x101, 24, 25, -1, 26, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 27, 28, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 29, 30, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 31, 28, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 32, 28, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 33, 28, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 34, 28, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 35, 28, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 36, 28, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 37, 28, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 38, 28, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 39, 28, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 40, 28, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 41, 28, -1, -1, -1, -1 },
    { NULL, "V", 0x2, 42, 43, -1, -1, -1, -1 },
    { NULL, "V", 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 44, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 45, 46, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(loadAttributesWithNSString:);
  methods[1].selector = @selector(init);
  methods[2].selector = @selector(initWithNSString:);
  methods[3].selector = @selector(initWithNSString:withNSString:);
  methods[4].selector = @selector(newInstance);
  methods[5].selector = @selector(createWithASIFragment:withJavaUtilMap:);
  methods[6].selector = @selector(setWidgetOnNativeClass);
  methods[7].selector = @selector(asWidget);
  methods[8].selector = @selector(removeWithASIWidget:);
  methods[9].selector = @selector(removeWithInt:);
  methods[10].selector = @selector(nativeRemoveViewWithASIWidget:);
  methods[11].selector = @selector(addWithASIWidget:withInt:);
  methods[12].selector = @selector(createLayoutParamsWithADView:);
  methods[13].selector = @selector(getLayoutParamsWithADView:);
  methods[14].selector = @selector(setChildAttributeWithASIWidget:withASWidgetAttribute:withNSString:withId:);
  methods[15].selector = @selector(getChildAttributeWithASIWidget:withASWidgetAttribute:);
  methods[16].selector = @selector(getViewClass);
  methods[17].selector = @selector(setAttributeWithASWidgetAttribute:withNSString:withId:withASILifeCycleDecorator:);
  methods[18].selector = @selector(getAttributeWithASWidgetAttribute:withASILifeCycleDecorator:);
  methods[19].selector = @selector(asNativeWidget);
  methods[20].selector = @selector(checkIosVersionWithNSString:);
  methods[21].selector = @selector(nativeCreateWithJavaUtilMap:);
  methods[22].selector = @selector(requestLayout);
  methods[23].selector = @selector(invalidate);
  methods[24].selector = @selector(setBehaviorWithADXCoordinatorLayout_LayoutParams:withId:);
  methods[25].selector = @selector(setKeyLinesWithId:);
  methods[26].selector = @selector(setBehaviorSignificantVelocityThresholdWithADXCoordinatorLayout_LayoutParams:withId:);
  methods[27].selector = @selector(setBehaviorExpandedOffsetWithADXCoordinatorLayout_LayoutParams:withId:);
  methods[28].selector = @selector(setBehaviorHalfExpandedRatioWithADXCoordinatorLayout_LayoutParams:withId:);
  methods[29].selector = @selector(setBehaviorDraggableWithADXCoordinatorLayout_LayoutParams:withId:);
  methods[30].selector = @selector(setBehaviorSkipCollapsedWithADXCoordinatorLayout_LayoutParams:withId:);
  methods[31].selector = @selector(setBehaviorHideableWithADXCoordinatorLayout_LayoutParams:withId:);
  methods[32].selector = @selector(setBehaviorFitToContentsWithADXCoordinatorLayout_LayoutParams:withId:);
  methods[33].selector = @selector(setBehaviorPeekHeightWithADXCoordinatorLayout_LayoutParams:withId:);
  methods[34].selector = @selector(setOnSlideWithADXCoordinatorLayout_LayoutParams:withId:);
  methods[35].selector = @selector(setOnStateChangedWithADXCoordinatorLayout_LayoutParams:withId:);
  methods[36].selector = @selector(setBehaviorStateWithADXCoordinatorLayout_LayoutParams:withId:);
  methods[37].selector = @selector(setMyKeyLinesWithIntArray:);
  methods[38].selector = @selector(onChildViewsChanged);
  methods[39].selector = @selector(setIdWithNSString:);
  methods[40].selector = @selector(setVisibleWithBoolean:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "uiView_", "LNSObject;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "LOCAL_NAME", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 47, -1, -1 },
    { "GROUP_NAME", "LNSString;", .constantValue.asLong = 0, 0x19, -1, 48, -1, -1 },
    { "coordinatorLayout_", "LADXCoordinatorLayout;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "onSlideCallBack_", "LADXBottomSheetBehavior_BottomSheetCallback;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "onStateChangeCallBack_", "LADXBottomSheetBehavior_BottomSheetCallback;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "loadAttributes", "LNSString;", "LNSString;LNSString;", "create", "LASIFragment;LJavaUtilMap;", "(Lcom/ashera/core/IFragment;Ljava/util/Map<Ljava/lang/String;Ljava/lang/Object;>;)V", "remove", "LASIWidget;", "I", "nativeRemoveView", "add", "LASIWidget;I", "createLayoutParams", "LADView;", "getLayoutParams", "setChildAttribute", "LASIWidget;LASWidgetAttribute;LNSString;LNSObject;", "getChildAttribute", "LASIWidget;LASWidgetAttribute;", "setAttribute", "LASWidgetAttribute;LNSString;LNSObject;LASILifeCycleDecorator;", "getAttribute", "LASWidgetAttribute;LASILifeCycleDecorator;", "checkIosVersion", "nativeCreate", "LJavaUtilMap;", "(Ljava/util/Map<Ljava/lang/String;Ljava/lang/Object;>;)V", "setBehavior", "LADXCoordinatorLayout_LayoutParams;LNSObject;", "setKeyLines", "LNSObject;", "setBehaviorSignificantVelocityThreshold", "setBehaviorExpandedOffset", "setBehaviorHalfExpandedRatio", "setBehaviorDraggable", "setBehaviorSkipCollapsed", "setBehaviorHideable", "setBehaviorFitToContents", "setBehaviorPeekHeight", "setOnSlide", "setOnStateChanged", "setBehaviorState", "setMyKeyLines", "[I", "setId", "setVisible", "Z", &ASCoordinatorLayoutImpl_LOCAL_NAME, &ASCoordinatorLayoutImpl_GROUP_NAME, "LASCoordinatorLayoutImpl_InsetEdge;LASCoordinatorLayoutImpl_DodgeInsetEdge;LASCoordinatorLayoutImpl_BehaviorState;LASCoordinatorLayoutImpl_CoordinatorLayoutExt;LASCoordinatorLayoutImpl_BottomSheetCallback;" };
  static const J2ObjcClassInfo _ASCoordinatorLayoutImpl = { "CoordinatorLayoutImpl", "com.ashera.coordinatorlayout", ptrTable, methods, fields, 7, 0x1, 41, 6, -1, 49, -1, -1, -1 };
  return &_ASCoordinatorLayoutImpl;
}

@end

void ASCoordinatorLayoutImpl_init(ASCoordinatorLayoutImpl *self) {
  ASBaseHasWidgets_initWithNSString_withNSString_(self, ASCoordinatorLayoutImpl_GROUP_NAME, ASCoordinatorLayoutImpl_LOCAL_NAME);
}

ASCoordinatorLayoutImpl *new_ASCoordinatorLayoutImpl_init() {
  J2OBJC_NEW_IMPL(ASCoordinatorLayoutImpl, init)
}

ASCoordinatorLayoutImpl *create_ASCoordinatorLayoutImpl_init() {
  J2OBJC_CREATE_IMPL(ASCoordinatorLayoutImpl, init)
}

void ASCoordinatorLayoutImpl_initWithNSString_(ASCoordinatorLayoutImpl *self, NSString *localname) {
  ASBaseHasWidgets_initWithNSString_withNSString_(self, ASCoordinatorLayoutImpl_GROUP_NAME, localname);
}

ASCoordinatorLayoutImpl *new_ASCoordinatorLayoutImpl_initWithNSString_(NSString *localname) {
  J2OBJC_NEW_IMPL(ASCoordinatorLayoutImpl, initWithNSString_, localname)
}

ASCoordinatorLayoutImpl *create_ASCoordinatorLayoutImpl_initWithNSString_(NSString *localname) {
  J2OBJC_CREATE_IMPL(ASCoordinatorLayoutImpl, initWithNSString_, localname)
}

void ASCoordinatorLayoutImpl_initWithNSString_withNSString_(ASCoordinatorLayoutImpl *self, NSString *groupName, NSString *localname) {
  ASBaseHasWidgets_initWithNSString_withNSString_(self, groupName, localname);
}

ASCoordinatorLayoutImpl *new_ASCoordinatorLayoutImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) {
  J2OBJC_NEW_IMPL(ASCoordinatorLayoutImpl, initWithNSString_withNSString_, groupName, localname)
}

ASCoordinatorLayoutImpl *create_ASCoordinatorLayoutImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) {
  J2OBJC_CREATE_IMPL(ASCoordinatorLayoutImpl, initWithNSString_withNSString_, groupName, localname)
}

void ASCoordinatorLayoutImpl_setWidgetOnNativeClass(ASCoordinatorLayoutImpl *self) {
  ((ASUIView*) [self asNativeWidget]).widget = self;
}

void ASCoordinatorLayoutImpl_nativeRemoveViewWithASIWidget_(ASCoordinatorLayoutImpl *self, id<ASIWidget> widget) {
  ADLayoutTransition *layoutTransition = [((ADXCoordinatorLayout *) nil_chk(self->coordinatorLayout_)) getLayoutTransition];
  if (layoutTransition != nil && ([layoutTransition isTransitionTypeEnabledWithInt:ADLayoutTransition_CHANGE_DISAPPEARING] || [layoutTransition isTransitionTypeEnabledWithInt:ADLayoutTransition_DISAPPEARING])) {
    [self addToBufferedRunnablesWithJavaLangRunnable:new_ASCoordinatorLayoutImpl_$Lambda$1_initWithASIWidget_(widget)];
  }
  else {
    ASViewGroupImpl_nativeRemoveViewWithASIWidget_(widget);
  }
}

void ASCoordinatorLayoutImpl_createLayoutParamsWithADView_(ASCoordinatorLayoutImpl *self, ADView *view) {
  ADXCoordinatorLayout_LayoutParams *layoutParams = (ADXCoordinatorLayout_LayoutParams *) cast_chk([((ADView *) nil_chk(view)) getLayoutParams], [ADXCoordinatorLayout_LayoutParams class]);
  layoutParams = (ADXCoordinatorLayout_LayoutParams *) cast_chk([view getLayoutParams], [ADXCoordinatorLayout_LayoutParams class]);
  if (layoutParams == nil) {
    layoutParams = new_ADXCoordinatorLayout_LayoutParams_initWithInt_withInt_(-2, -2);
    [view setLayoutParamsWithADViewGroup_LayoutParams:layoutParams];
  }
  else {
    layoutParams->height_ = -2;
    layoutParams->width_ = -2;
  }
}

ADXCoordinatorLayout_LayoutParams *ASCoordinatorLayoutImpl_getLayoutParamsWithADView_(ASCoordinatorLayoutImpl *self, ADView *view) {
  return (ADXCoordinatorLayout_LayoutParams *) cast_chk([((ADView *) nil_chk(view)) getLayoutParams], [ADXCoordinatorLayout_LayoutParams class]);
}

void ASCoordinatorLayoutImpl_setBehaviorWithADXCoordinatorLayout_LayoutParams_withId_(ASCoordinatorLayoutImpl *self, ADXCoordinatorLayout_LayoutParams *layoutParams, id objValue) {
  id behavior = ASWidgetFactory_getBehaviorWithNSString_((NSString *) cast_chk(objValue, [NSString class]));
  if (behavior == nil) {
    @throw new_JavaLangRuntimeException_initWithNSString_(JreStrcat("$$", @"Call WidgetFactory.registerBehavior for ", (NSString *) cast_chk(objValue, [NSString class])));
  }
  [((ADXCoordinatorLayout_LayoutParams *) nil_chk(layoutParams)) setBehaviorWithADXCoordinatorLayout_Behavior:(ADXCoordinatorLayout_Behavior *) cast_chk(behavior, [ADXCoordinatorLayout_Behavior class])];
}

void ASCoordinatorLayoutImpl_setKeyLinesWithId_(ASCoordinatorLayoutImpl *self, id objValue) {
  id<JavaUtilList> values = (id<JavaUtilList>) cast_check(objValue, JavaUtilList_class_());
  IOSIntArray *keyLines = [IOSIntArray newArrayWithLength:[((id<JavaUtilList>) nil_chk(values)) size]];
  for (int32_t i = 0; i < [values size]; i++) {
    int32_t obj = [((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk([values getWithInt:i], [JavaLangInteger class]))) intValue];
    *IOSIntArray_GetRef(keyLines, i) = JreFpToInt((obj * ((ADDisplayMetrics *) nil_chk([((ADResources *) nil_chk([((ADContext *) nil_chk([((ADXCoordinatorLayout *) nil_chk(self->coordinatorLayout_)) getContext])) getResources])) getDisplayMetrics]))->density_));
  }
  ASCoordinatorLayoutImpl_setMyKeyLinesWithIntArray_(self, keyLines);
}

void ASCoordinatorLayoutImpl_setBehaviorSignificantVelocityThresholdWithADXCoordinatorLayout_LayoutParams_withId_(ASCoordinatorLayoutImpl *self, ADXCoordinatorLayout_LayoutParams *layoutParams, id objValue) {
  if ([[((ADXCoordinatorLayout_LayoutParams *) nil_chk(layoutParams)) getBehavior] isKindOfClass:[ADXBottomSheetBehavior class]]) {
    [((ADXBottomSheetBehavior *) nil_chk(((ADXBottomSheetBehavior *) cast_chk([layoutParams getBehavior], [ADXBottomSheetBehavior class])))) setSignificantVelocityThresholdWithInt:[((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class]))) intValue]];
  }
}

void ASCoordinatorLayoutImpl_setBehaviorExpandedOffsetWithADXCoordinatorLayout_LayoutParams_withId_(ASCoordinatorLayoutImpl *self, ADXCoordinatorLayout_LayoutParams *layoutParams, id objValue) {
  if ([[((ADXCoordinatorLayout_LayoutParams *) nil_chk(layoutParams)) getBehavior] isKindOfClass:[ADXBottomSheetBehavior class]]) {
    [((ADXBottomSheetBehavior *) nil_chk(((ADXBottomSheetBehavior *) cast_chk([layoutParams getBehavior], [ADXBottomSheetBehavior class])))) setExpandedOffsetWithInt:[((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class]))) intValue]];
  }
}

void ASCoordinatorLayoutImpl_setBehaviorHalfExpandedRatioWithADXCoordinatorLayout_LayoutParams_withId_(ASCoordinatorLayoutImpl *self, ADXCoordinatorLayout_LayoutParams *layoutParams, id objValue) {
  if ([[((ADXCoordinatorLayout_LayoutParams *) nil_chk(layoutParams)) getBehavior] isKindOfClass:[ADXBottomSheetBehavior class]]) {
    [((ADXBottomSheetBehavior *) nil_chk(((ADXBottomSheetBehavior *) cast_chk([layoutParams getBehavior], [ADXBottomSheetBehavior class])))) setHalfExpandedRatioWithFloat:[((JavaLangFloat *) nil_chk((JavaLangFloat *) cast_chk(objValue, [JavaLangFloat class]))) floatValue]];
  }
}

void ASCoordinatorLayoutImpl_setBehaviorDraggableWithADXCoordinatorLayout_LayoutParams_withId_(ASCoordinatorLayoutImpl *self, ADXCoordinatorLayout_LayoutParams *layoutParams, id objValue) {
  if ([[((ADXCoordinatorLayout_LayoutParams *) nil_chk(layoutParams)) getBehavior] isKindOfClass:[ADXBottomSheetBehavior class]]) {
    [((ADXBottomSheetBehavior *) nil_chk(((ADXBottomSheetBehavior *) cast_chk([layoutParams getBehavior], [ADXBottomSheetBehavior class])))) setDraggableWithBoolean:[((JavaLangBoolean *) nil_chk((JavaLangBoolean *) cast_chk(objValue, [JavaLangBoolean class]))) booleanValue]];
  }
}

void ASCoordinatorLayoutImpl_setBehaviorSkipCollapsedWithADXCoordinatorLayout_LayoutParams_withId_(ASCoordinatorLayoutImpl *self, ADXCoordinatorLayout_LayoutParams *layoutParams, id objValue) {
  if ([[((ADXCoordinatorLayout_LayoutParams *) nil_chk(layoutParams)) getBehavior] isKindOfClass:[ADXBottomSheetBehavior class]]) {
    [((ADXBottomSheetBehavior *) nil_chk(((ADXBottomSheetBehavior *) cast_chk([layoutParams getBehavior], [ADXBottomSheetBehavior class])))) setSkipCollapsedWithBoolean:[((JavaLangBoolean *) nil_chk((JavaLangBoolean *) cast_chk(objValue, [JavaLangBoolean class]))) booleanValue]];
  }
}

void ASCoordinatorLayoutImpl_setBehaviorHideableWithADXCoordinatorLayout_LayoutParams_withId_(ASCoordinatorLayoutImpl *self, ADXCoordinatorLayout_LayoutParams *layoutParams, id objValue) {
  if ([[((ADXCoordinatorLayout_LayoutParams *) nil_chk(layoutParams)) getBehavior] isKindOfClass:[ADXBottomSheetBehavior class]]) {
    [((ADXBottomSheetBehavior *) nil_chk(((ADXBottomSheetBehavior *) cast_chk([layoutParams getBehavior], [ADXBottomSheetBehavior class])))) setHideableWithBoolean:[((JavaLangBoolean *) nil_chk((JavaLangBoolean *) cast_chk(objValue, [JavaLangBoolean class]))) booleanValue]];
  }
}

void ASCoordinatorLayoutImpl_setBehaviorFitToContentsWithADXCoordinatorLayout_LayoutParams_withId_(ASCoordinatorLayoutImpl *self, ADXCoordinatorLayout_LayoutParams *layoutParams, id objValue) {
  if ([[((ADXCoordinatorLayout_LayoutParams *) nil_chk(layoutParams)) getBehavior] isKindOfClass:[ADXBottomSheetBehavior class]]) {
    [((ADXBottomSheetBehavior *) nil_chk(((ADXBottomSheetBehavior *) cast_chk([layoutParams getBehavior], [ADXBottomSheetBehavior class])))) setFitToContentsWithBoolean:[((JavaLangBoolean *) nil_chk((JavaLangBoolean *) cast_chk(objValue, [JavaLangBoolean class]))) booleanValue]];
  }
}

void ASCoordinatorLayoutImpl_setBehaviorPeekHeightWithADXCoordinatorLayout_LayoutParams_withId_(ASCoordinatorLayoutImpl *self, ADXCoordinatorLayout_LayoutParams *layoutParams, id objValue) {
  if ([[((ADXCoordinatorLayout_LayoutParams *) nil_chk(layoutParams)) getBehavior] isKindOfClass:[ADXBottomSheetBehavior class]]) {
    [((ADXBottomSheetBehavior *) nil_chk(((ADXBottomSheetBehavior *) cast_chk([layoutParams getBehavior], [ADXBottomSheetBehavior class])))) setPeekHeightWithInt:[((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class]))) intValue]];
  }
}

void ASCoordinatorLayoutImpl_setOnSlideWithADXCoordinatorLayout_LayoutParams_withId_(ASCoordinatorLayoutImpl *self, ADXCoordinatorLayout_LayoutParams *layoutParams, id objValue) {
  if ([[((ADXCoordinatorLayout_LayoutParams *) nil_chk(layoutParams)) getBehavior] isKindOfClass:[ADXBottomSheetBehavior class]]) {
    ADXBottomSheetBehavior *behavior = (ADXBottomSheetBehavior *) cast_chk([layoutParams getBehavior], [ADXBottomSheetBehavior class]);
    if (self->onSlideCallBack_ != nil) {
      [((ADXBottomSheetBehavior *) nil_chk(behavior)) removeBottomSheetCallbackWithADXBottomSheetBehavior_BottomSheetCallback:self->onSlideCallBack_];
    }
    if ([objValue isKindOfClass:[NSString class]]) {
      self->onSlideCallBack_ = new_ASCoordinatorLayoutImpl_BottomSheetCallback_initWithASIWidget_withNSString_withNSString_(self, (NSString *) objValue, @"onSlide");
      [((ADXBottomSheetBehavior *) nil_chk(behavior)) addBottomSheetCallbackWithADXBottomSheetBehavior_BottomSheetCallback:self->onSlideCallBack_];
    }
    else {
      self->onSlideCallBack_ = (ADXBottomSheetBehavior_BottomSheetCallback *) cast_chk(objValue, [ADXBottomSheetBehavior_BottomSheetCallback class]);
      [((ADXBottomSheetBehavior *) nil_chk(behavior)) addBottomSheetCallbackWithADXBottomSheetBehavior_BottomSheetCallback:self->onSlideCallBack_];
    }
  }
}

void ASCoordinatorLayoutImpl_setOnStateChangedWithADXCoordinatorLayout_LayoutParams_withId_(ASCoordinatorLayoutImpl *self, ADXCoordinatorLayout_LayoutParams *layoutParams, id objValue) {
  if ([[((ADXCoordinatorLayout_LayoutParams *) nil_chk(layoutParams)) getBehavior] isKindOfClass:[ADXBottomSheetBehavior class]]) {
    ADXBottomSheetBehavior *behavior = (ADXBottomSheetBehavior *) cast_chk([layoutParams getBehavior], [ADXBottomSheetBehavior class]);
    if (self->onStateChangeCallBack_ != nil) {
      [((ADXBottomSheetBehavior *) nil_chk(behavior)) removeBottomSheetCallbackWithADXBottomSheetBehavior_BottomSheetCallback:self->onStateChangeCallBack_];
    }
    if ([objValue isKindOfClass:[NSString class]]) {
      self->onStateChangeCallBack_ = new_ASCoordinatorLayoutImpl_BottomSheetCallback_initWithASIWidget_withNSString_withNSString_(self, (NSString *) objValue, @"onStateChanged");
      [((ADXBottomSheetBehavior *) nil_chk(behavior)) addBottomSheetCallbackWithADXBottomSheetBehavior_BottomSheetCallback:self->onStateChangeCallBack_];
    }
    else {
      self->onStateChangeCallBack_ = (ADXBottomSheetBehavior_BottomSheetCallback *) cast_chk(objValue, [ADXBottomSheetBehavior_BottomSheetCallback class]);
      [((ADXBottomSheetBehavior *) nil_chk(behavior)) addBottomSheetCallbackWithADXBottomSheetBehavior_BottomSheetCallback:self->onStateChangeCallBack_];
    }
  }
}

void ASCoordinatorLayoutImpl_setBehaviorStateWithADXCoordinatorLayout_LayoutParams_withId_(ASCoordinatorLayoutImpl *self, ADXCoordinatorLayout_LayoutParams *layoutParams, id objValue) {
  if ([[((ADXCoordinatorLayout_LayoutParams *) nil_chk(layoutParams)) getBehavior] isKindOfClass:[ADXBottomSheetBehavior class]]) {
    [((ADXBottomSheetBehavior *) nil_chk(((ADXBottomSheetBehavior *) cast_chk([layoutParams getBehavior], [ADXBottomSheetBehavior class])))) setStateWithInt:[((JavaLangInteger *) nil_chk((JavaLangInteger *) cast_chk(objValue, [JavaLangInteger class]))) intValue]];
  }
}

void ASCoordinatorLayoutImpl_setMyKeyLinesWithIntArray_(ASCoordinatorLayoutImpl *self, IOSIntArray *keyLines) {
  [((ADXCoordinatorLayout *) nil_chk(self->coordinatorLayout_)) setKeyLinesWithIntArray:keyLines];
}

void ASCoordinatorLayoutImpl_onChildViewsChanged(ASCoordinatorLayoutImpl *self) {
  [((ADXCoordinatorLayout *) nil_chk(self->coordinatorLayout_)) onChildViewsChangedWithInt:0];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASCoordinatorLayoutImpl)

J2OBJC_NAME_MAPPING(ASCoordinatorLayoutImpl, "com.ashera.coordinatorlayout", "AS")

@implementation ASCoordinatorLayoutImpl_InsetEdge

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ASCoordinatorLayoutImpl_InsetEdge_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (id<JavaUtilMap>)getMapping {
  return mapping_;
}

- (JavaLangInteger *)getDefault {
  return JavaLangInteger_valueOfWithInt_(0);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
    { NULL, "LJavaUtilMap;", 0x1, -1, -1, -1, 0, -1, -1 },
    { NULL, "LJavaLangInteger;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(getMapping);
  methods[2].selector = @selector(getDefault);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "mapping_", "LJavaUtilMap;", .constantValue.asLong = 0, 0x2, -1, -1, 1, -1 },
  };
  static const void *ptrTable[] = { "()Ljava/util/Map<Ljava/lang/String;Ljava/lang/Integer;>;", "Ljava/util/Map<Ljava/lang/String;Ljava/lang/Integer;>;", "LASCoordinatorLayoutImpl;" };
  static const J2ObjcClassInfo _ASCoordinatorLayoutImpl_InsetEdge = { "InsetEdge", "com.ashera.coordinatorlayout", ptrTable, methods, fields, 7, 0x18, 3, 1, 2, -1, -1, -1, -1 };
  return &_ASCoordinatorLayoutImpl_InsetEdge;
}

@end

void ASCoordinatorLayoutImpl_InsetEdge_init(ASCoordinatorLayoutImpl_InsetEdge *self) {
  ASAbstractEnumToIntConverter_init(self);
  self->mapping_ = new_JavaUtilHashMap_init();
  {
    (void) [self->mapping_ putWithId:@"none" withId:JavaLangInteger_valueOfWithInt_((int32_t) 0x0)];
    (void) [((id<JavaUtilMap>) nil_chk(self->mapping_)) putWithId:@"top" withId:JavaLangInteger_valueOfWithInt_((int32_t) 0x30)];
    (void) [((id<JavaUtilMap>) nil_chk(self->mapping_)) putWithId:@"bottom" withId:JavaLangInteger_valueOfWithInt_((int32_t) 0x50)];
    (void) [((id<JavaUtilMap>) nil_chk(self->mapping_)) putWithId:@"left" withId:JavaLangInteger_valueOfWithInt_((int32_t) 0x03)];
    (void) [((id<JavaUtilMap>) nil_chk(self->mapping_)) putWithId:@"right" withId:JavaLangInteger_valueOfWithInt_((int32_t) 0x05)];
    (void) [((id<JavaUtilMap>) nil_chk(self->mapping_)) putWithId:@"start" withId:JavaLangInteger_valueOfWithInt_((int32_t) 0x00800003)];
    (void) [((id<JavaUtilMap>) nil_chk(self->mapping_)) putWithId:@"end" withId:JavaLangInteger_valueOfWithInt_((int32_t) 0x00800005)];
  }
}

ASCoordinatorLayoutImpl_InsetEdge *new_ASCoordinatorLayoutImpl_InsetEdge_init() {
  J2OBJC_NEW_IMPL(ASCoordinatorLayoutImpl_InsetEdge, init)
}

ASCoordinatorLayoutImpl_InsetEdge *create_ASCoordinatorLayoutImpl_InsetEdge_init() {
  J2OBJC_CREATE_IMPL(ASCoordinatorLayoutImpl_InsetEdge, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASCoordinatorLayoutImpl_InsetEdge)

@implementation ASCoordinatorLayoutImpl_DodgeInsetEdge

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ASCoordinatorLayoutImpl_DodgeInsetEdge_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (id<JavaUtilMap>)getMapping {
  return mapping_;
}

- (JavaLangInteger *)getDefault {
  return JavaLangInteger_valueOfWithInt_(0);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
    { NULL, "LJavaUtilMap;", 0x1, -1, -1, -1, 0, -1, -1 },
    { NULL, "LJavaLangInteger;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(getMapping);
  methods[2].selector = @selector(getDefault);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "mapping_", "LJavaUtilMap;", .constantValue.asLong = 0, 0x2, -1, -1, 1, -1 },
  };
  static const void *ptrTable[] = { "()Ljava/util/Map<Ljava/lang/String;Ljava/lang/Integer;>;", "Ljava/util/Map<Ljava/lang/String;Ljava/lang/Integer;>;", "LASCoordinatorLayoutImpl;" };
  static const J2ObjcClassInfo _ASCoordinatorLayoutImpl_DodgeInsetEdge = { "DodgeInsetEdge", "com.ashera.coordinatorlayout", ptrTable, methods, fields, 7, 0x18, 3, 1, 2, -1, -1, -1, -1 };
  return &_ASCoordinatorLayoutImpl_DodgeInsetEdge;
}

@end

void ASCoordinatorLayoutImpl_DodgeInsetEdge_init(ASCoordinatorLayoutImpl_DodgeInsetEdge *self) {
  ASAbstractBitFlagConverter_init(self);
  self->mapping_ = new_JavaUtilHashMap_init();
  {
    (void) [self->mapping_ putWithId:@"none" withId:JavaLangInteger_valueOfWithInt_((int32_t) 0x0)];
    (void) [((id<JavaUtilMap>) nil_chk(self->mapping_)) putWithId:@"top" withId:JavaLangInteger_valueOfWithInt_((int32_t) 0x30)];
    (void) [((id<JavaUtilMap>) nil_chk(self->mapping_)) putWithId:@"bottom" withId:JavaLangInteger_valueOfWithInt_((int32_t) 0x50)];
    (void) [((id<JavaUtilMap>) nil_chk(self->mapping_)) putWithId:@"left" withId:JavaLangInteger_valueOfWithInt_((int32_t) 0x03)];
    (void) [((id<JavaUtilMap>) nil_chk(self->mapping_)) putWithId:@"right" withId:JavaLangInteger_valueOfWithInt_((int32_t) 0x05)];
    (void) [((id<JavaUtilMap>) nil_chk(self->mapping_)) putWithId:@"start" withId:JavaLangInteger_valueOfWithInt_((int32_t) 0x00800003)];
    (void) [((id<JavaUtilMap>) nil_chk(self->mapping_)) putWithId:@"end" withId:JavaLangInteger_valueOfWithInt_((int32_t) 0x00800005)];
    (void) [((id<JavaUtilMap>) nil_chk(self->mapping_)) putWithId:@"all" withId:JavaLangInteger_valueOfWithInt_((int32_t) 0x77)];
  }
}

ASCoordinatorLayoutImpl_DodgeInsetEdge *new_ASCoordinatorLayoutImpl_DodgeInsetEdge_init() {
  J2OBJC_NEW_IMPL(ASCoordinatorLayoutImpl_DodgeInsetEdge, init)
}

ASCoordinatorLayoutImpl_DodgeInsetEdge *create_ASCoordinatorLayoutImpl_DodgeInsetEdge_init() {
  J2OBJC_CREATE_IMPL(ASCoordinatorLayoutImpl_DodgeInsetEdge, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASCoordinatorLayoutImpl_DodgeInsetEdge)

@implementation ASCoordinatorLayoutImpl_BehaviorState

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ASCoordinatorLayoutImpl_BehaviorState_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (id<JavaUtilMap>)getMapping {
  return mapping_;
}

- (JavaLangInteger *)getDefault {
  return JavaLangInteger_valueOfWithInt_(0);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
    { NULL, "LJavaUtilMap;", 0x1, -1, -1, -1, 0, -1, -1 },
    { NULL, "LJavaLangInteger;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(getMapping);
  methods[2].selector = @selector(getDefault);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "mapping_", "LJavaUtilMap;", .constantValue.asLong = 0, 0x2, -1, -1, 1, -1 },
  };
  static const void *ptrTable[] = { "()Ljava/util/Map<Ljava/lang/String;Ljava/lang/Integer;>;", "Ljava/util/Map<Ljava/lang/String;Ljava/lang/Integer;>;", "LASCoordinatorLayoutImpl;" };
  static const J2ObjcClassInfo _ASCoordinatorLayoutImpl_BehaviorState = { "BehaviorState", "com.ashera.coordinatorlayout", ptrTable, methods, fields, 7, 0x18, 3, 1, 2, -1, -1, -1, -1 };
  return &_ASCoordinatorLayoutImpl_BehaviorState;
}

@end

void ASCoordinatorLayoutImpl_BehaviorState_init(ASCoordinatorLayoutImpl_BehaviorState *self) {
  ASAbstractEnumToIntConverter_init(self);
  self->mapping_ = new_JavaUtilHashMap_init();
  {
    (void) [self->mapping_ putWithId:@"state_none" withId:JavaLangInteger_valueOfWithInt_((int32_t) 0x0)];
    (void) [((id<JavaUtilMap>) nil_chk(self->mapping_)) putWithId:@"state_dragging" withId:JavaLangInteger_valueOfWithInt_((int32_t) 0x1)];
    (void) [((id<JavaUtilMap>) nil_chk(self->mapping_)) putWithId:@"state_settling" withId:JavaLangInteger_valueOfWithInt_((int32_t) 0x2)];
    (void) [((id<JavaUtilMap>) nil_chk(self->mapping_)) putWithId:@"state_expanded" withId:JavaLangInteger_valueOfWithInt_((int32_t) 0x3)];
    (void) [((id<JavaUtilMap>) nil_chk(self->mapping_)) putWithId:@"state_collapsed" withId:JavaLangInteger_valueOfWithInt_((int32_t) 0x4)];
    (void) [((id<JavaUtilMap>) nil_chk(self->mapping_)) putWithId:@"state_hidden" withId:JavaLangInteger_valueOfWithInt_((int32_t) 0x5)];
    (void) [((id<JavaUtilMap>) nil_chk(self->mapping_)) putWithId:@"state_half_expanded" withId:JavaLangInteger_valueOfWithInt_((int32_t) 0x6)];
  }
}

ASCoordinatorLayoutImpl_BehaviorState *new_ASCoordinatorLayoutImpl_BehaviorState_init() {
  J2OBJC_NEW_IMPL(ASCoordinatorLayoutImpl_BehaviorState, init)
}

ASCoordinatorLayoutImpl_BehaviorState *create_ASCoordinatorLayoutImpl_BehaviorState_init() {
  J2OBJC_CREATE_IMPL(ASCoordinatorLayoutImpl_BehaviorState, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASCoordinatorLayoutImpl_BehaviorState)

@implementation ASCoordinatorLayoutImpl_CoordinatorLayoutExt

- (id<ASIWidget>)getWidget {
  return this$0_;
}

- (void)setMaxWidthWithInt:(int32_t)width {
  mMaxWidth_ = width;
}

- (void)setMaxHeightWithInt:(int32_t)height {
  mMaxHeight_ = height;
}

- (int32_t)getMaxWidth {
  return mMaxWidth_;
}

- (int32_t)getMaxHeight {
  return mMaxHeight_;
}

- (instancetype)initWithASCoordinatorLayoutImpl:(ASCoordinatorLayoutImpl *)outer$ {
  ASCoordinatorLayoutImpl_CoordinatorLayoutExt_initWithASCoordinatorLayoutImpl_(self, outer$);
  return self;
}

- (void)onMeasureWithInt:(int32_t)widthMeasureSpec
                 withInt:(int32_t)heightMeasureSpec {
  if (mMaxWidth_ > 0) {
    widthMeasureSpec = ADView_MeasureSpec_makeMeasureSpecWithInt_withInt_(mMaxWidth_, ADView_MeasureSpec_AT_MOST);
  }
  if (mMaxHeight_ > 0) {
    heightMeasureSpec = ADView_MeasureSpec_makeMeasureSpecWithInt_withInt_(mMaxHeight_, ADView_MeasureSpec_AT_MOST);
  }
  [super onMeasureWithInt:widthMeasureSpec withInt:heightMeasureSpec];
  id<ASIWidgetLifeCycleListener> listener = [this$0_ getListener];
  if (listener != nil) {
    [((ASMeasureEvent *) nil_chk(measureFinished_)) setWidthWithInt:[self getMeasuredWidth]];
    [((ASMeasureEvent *) nil_chk(measureFinished_)) setHeightWithInt:[self getMeasuredHeight]];
    [listener eventOccurredWithASIWidgetLifeCycleListener_EventId:JreLoadEnum(ASIWidgetLifeCycleListener_EventId, measureFinished) withASWidgetEvent:measureFinished_];
  }
}

- (void)onLayoutWithBoolean:(bool)changed
                    withInt:(int32_t)l
                    withInt:(int32_t)t
                    withInt:(int32_t)r
                    withInt:(int32_t)b {
  [super onLayoutWithBoolean:changed withInt:l withInt:t withInt:r withInt:b];
  ASViewImpl_setDrawableBoundsWithASIWidget_withInt_withInt_withInt_withInt_(this$0_, l, t, r, b);
  if (![self isOverlay]) {
    ASViewImpl_nativeMakeFrameWithId_withInt_withInt_withInt_withInt_([this$0_ asNativeWidget], l, t, r, b);
  }
  [this$0_ replayBufferedEvents];
  ASViewImpl_redrawDrawablesWithASIWidget_(this$0_);
  overlays_ = ASViewImpl_drawOverlayWithASIWidget_withJavaUtilList_(this$0_, overlays_);
  id<ASIWidgetLifeCycleListener> listener = [this$0_ getListener];
  if (listener != nil) {
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setBWithInt:b];
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setLWithInt:l];
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setRWithInt:r];
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setTWithInt:t];
    [((ASOnLayoutEvent *) nil_chk(onLayoutEvent_)) setChangedWithBoolean:changed];
    [listener eventOccurredWithASIWidgetLifeCycleListener_EventId:JreLoadEnum(ASIWidgetLifeCycleListener_EventId, onLayout) withASWidgetEvent:onLayoutEvent_];
  }
  if ([this$0_ isInvalidateOnFrameChange] && [this$0_ isInitialised]) {
    [this$0_ invalidate];
  }
}

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas {
}

- (void)updateMeasuredDimensionWithInt:(int32_t)width
                               withInt:(int32_t)height {
  [self setMeasuredDimensionWithInt:width withInt:height];
}

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (id<JavaUtilList>)getMethods {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (void)initialized {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute {
  @throw new_JavaLangUnsupportedOperationException_init();
}

- (void)drawableStateChanged {
  [super drawableStateChanged];
  if (![this$0_ isWidgetDisposed]) {
    ASViewImpl_drawableStateChangedWithASIWidget_(this$0_);
  }
}

- (ADView *)inflateViewWithNSString:(NSString *)layout {
  if (templates_ == nil) {
    templates_ = new_JavaUtilHashMap_init();
  }
  id<ASIWidget> template_ = [templates_ getWithId:layout];
  if (template_ == nil) {
    template_ = (id<ASIWidget>) cast_check([this$0_ quickConvertWithId:layout withNSString:@"template"], ASIWidget_class_());
    (void) [((id<JavaUtilMap>) nil_chk(templates_)) putWithId:layout withId:template_];
  }
  id<ASIWidget> widget = [((id<ASIWidget>) nil_chk(template_)) loadLazyWidgetsWithASHasWidgets:this$0_];
  return (ADView *) cast_chk([((id<ASIWidget>) nil_chk(widget)) asWidget], [ADView class]);
}

- (void)remeasure {
  if ([this$0_ getFragment] != nil) {
    [((id<ASIFragment>) nil_chk([this$0_ getFragment])) remeasure];
  }
}

- (void)removeFromParent {
  [((id<ASHasWidgets>) nil_chk([this$0_ getParent])) removeWithASIWidget:this$0_];
}

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation {
  *IOSIntArray_GetRef(nil_chk(appScreenLocation), 0) = ASViewImpl_getLocationXOnScreenWithId_([this$0_ asNativeWidget]);
  *IOSIntArray_GetRef(appScreenLocation, 1) = ASViewImpl_getLocationYOnScreenWithId_([this$0_ asNativeWidget]);
}

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame {
  ((ADRect *) nil_chk(displayFrame))->left_ = ASViewImpl_getLocationXOnScreenWithId_([this$0_ asNativeWidget]);
  displayFrame->top_ = ASViewImpl_getLocationYOnScreenWithId_([this$0_ asNativeWidget]);
  displayFrame->right_ = displayFrame->left_ + [self getWidth];
  displayFrame->bottom_ = displayFrame->top_ + [self getHeight];
}

- (void)offsetTopAndBottomWithInt:(int32_t)offset {
  [super offsetTopAndBottomWithInt:offset];
  ASViewImpl_nativeMakeFrameWithId_withInt_withInt_withInt_withInt_([this$0_ asNativeWidget], [self getLeft], [self getTop], [self getRight], [self getBottom]);
}

- (void)offsetLeftAndRightWithInt:(int32_t)offset {
  [super offsetLeftAndRightWithInt:offset];
  ASViewImpl_nativeMakeFrameWithId_withInt_withInt_withInt_withInt_([this$0_ asNativeWidget], [self getLeft], [self getTop], [self getRight], [self getBottom]);
}

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value {
  if ([((NSString *) nil_chk(name)) isEqual:@"state0"]) {
    [self setState0WithId:value];
    return;
  }
  if ([name isEqual:@"state1"]) {
    [self setState1WithId:value];
    return;
  }
  if ([name isEqual:@"state2"]) {
    [self setState2WithId:value];
    return;
  }
  if ([name isEqual:@"state3"]) {
    [self setState3WithId:value];
    return;
  }
  if ([name isEqual:@"state4"]) {
    [self setState4WithId:value];
    return;
  }
  [this$0_ setAttributeWithNSString:name withId:value withBoolean:!([value isKindOfClass:[NSString class]])];
}

- (void)setVisibilityWithInt:(int32_t)visibility {
  [super setVisibilityWithInt:visibility];
  ASViewImpl_nativeSetVisibilityWithId_withBoolean_([this$0_ asNativeWidget], visibility != ADView_VISIBLE);
}

- (void)onLayoutChildWithADView:(ADView *)child
                        withInt:(int32_t)layoutDirection {
  [super onLayoutChildWithADView:child withInt:layoutDirection];
  if ([this$0_ isInitialised]) {
    [((ADXCoordinatorLayout *) nil_chk(this$0_->coordinatorLayout_)) onChildViewsChangedWithInt:0];
  }
}

- (void)setState0WithId:(id)value {
  ASViewImpl_setStateWithASIWidget_withInt_withId_(this$0_, 0, value);
}

- (void)setState1WithId:(id)value {
  ASViewImpl_setStateWithASIWidget_withInt_withId_(this$0_, 1, value);
}

- (void)setState2WithId:(id)value {
  ASViewImpl_setStateWithASIWidget_withInt_withId_(this$0_, 2, value);
}

- (void)setState3WithId:(id)value {
  ASViewImpl_setStateWithASIWidget_withInt_withId_(this$0_, 3, value);
}

- (void)setState4WithId:(id)value {
  ASViewImpl_setStateWithASIWidget_withInt_withId_(this$0_, 4, value);
}

- (void)state0 {
  ASViewImpl_stateWithASIWidget_withInt_(this$0_, 0);
}

- (void)state1 {
  ASViewImpl_stateWithASIWidget_withInt_(this$0_, 1);
}

- (void)state2 {
  ASViewImpl_stateWithASIWidget_withInt_(this$0_, 2);
}

- (void)state3 {
  ASViewImpl_stateWithASIWidget_withInt_(this$0_, 3);
}

- (void)state4 {
  ASViewImpl_stateWithASIWidget_withInt_(this$0_, 4);
}

- (void)stateYes {
  ASViewImpl_stateYesWithASIWidget_(this$0_);
}

- (void)stateNo {
  ASViewImpl_stateNoWithASIWidget_(this$0_);
}

- (void)endViewTransitionWithADView:(ADView *)view {
  [super endViewTransitionWithADView:view];
  [this$0_ runBufferedRunnables];
}

- (void)__javaClone:(ASCoordinatorLayoutImpl_CoordinatorLayoutExt *)original {
  [super __javaClone:original];
  JreRelease(this$0_);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LASIWidget;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 2, 1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 3, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 4, 5, -1, -1, -1, -1 },
    { NULL, "V", 0x4, 6, 7, -1, -1, -1, -1 },
    { NULL, "V", 0x81, 8, 9, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 10, 5, -1, -1, -1, -1 },
    { NULL, "LASILifeCycleDecorator;", 0x1, 11, 12, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 13, 14, -1, -1, -1, -1 },
    { NULL, "LJavaUtilList;", 0x1, -1, -1, -1, 15, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSObject;", 0x1, 16, 17, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LADView;", 0x1, 18, 19, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 20, 21, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 22, 23, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 24, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 25, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 26, 27, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 28, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 29, 30, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 31, 32, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 33, 32, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 34, 32, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 35, 32, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 36, 32, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 37, 38, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(getWidget);
  methods[1].selector = @selector(setMaxWidthWithInt:);
  methods[2].selector = @selector(setMaxHeightWithInt:);
  methods[3].selector = @selector(getMaxWidth);
  methods[4].selector = @selector(getMaxHeight);
  methods[5].selector = @selector(initWithASCoordinatorLayoutImpl:);
  methods[6].selector = @selector(onMeasureWithInt:withInt:);
  methods[7].selector = @selector(onLayoutWithBoolean:withInt:withInt:withInt:withInt:);
  methods[8].selector = @selector(executeWithNSString:withNSObjectArray:);
  methods[9].selector = @selector(updateMeasuredDimensionWithInt:withInt:);
  methods[10].selector = @selector(newInstanceWithASIWidget:);
  methods[11].selector = @selector(setAttributeWithASWidgetAttribute:withNSString:withId:);
  methods[12].selector = @selector(getMethods);
  methods[13].selector = @selector(initialized);
  methods[14].selector = @selector(getAttributeWithASWidgetAttribute:);
  methods[15].selector = @selector(drawableStateChanged);
  methods[16].selector = @selector(inflateViewWithNSString:);
  methods[17].selector = @selector(remeasure);
  methods[18].selector = @selector(removeFromParent);
  methods[19].selector = @selector(getLocationOnScreenWithIntArray:);
  methods[20].selector = @selector(getWindowVisibleDisplayFrameWithADRect:);
  methods[21].selector = @selector(offsetTopAndBottomWithInt:);
  methods[22].selector = @selector(offsetLeftAndRightWithInt:);
  methods[23].selector = @selector(setMyAttributeWithNSString:withId:);
  methods[24].selector = @selector(setVisibilityWithInt:);
  methods[25].selector = @selector(onLayoutChildWithADView:withInt:);
  methods[26].selector = @selector(setState0WithId:);
  methods[27].selector = @selector(setState1WithId:);
  methods[28].selector = @selector(setState2WithId:);
  methods[29].selector = @selector(setState3WithId:);
  methods[30].selector = @selector(setState4WithId:);
  methods[31].selector = @selector(state0);
  methods[32].selector = @selector(state1);
  methods[33].selector = @selector(state2);
  methods[34].selector = @selector(state3);
  methods[35].selector = @selector(state4);
  methods[36].selector = @selector(stateYes);
  methods[37].selector = @selector(stateNo);
  methods[38].selector = @selector(endViewTransitionWithADView:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LASCoordinatorLayoutImpl;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
    { "measureFinished_", "LASMeasureEvent;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "onLayoutEvent_", "LASOnLayoutEvent;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "overlays_", "LJavaUtilList;", .constantValue.asLong = 0, 0x2, -1, -1, 39, -1 },
    { "mMaxWidth_", "I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "mMaxHeight_", "I", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "templates_", "LJavaUtilMap;", .constantValue.asLong = 0, 0x2, -1, -1, 40, -1 },
  };
  static const void *ptrTable[] = { "setMaxWidth", "I", "setMaxHeight", "LASCoordinatorLayoutImpl;", "onMeasure", "II", "onLayout", "ZIIII", "execute", "LNSString;[LNSObject;", "updateMeasuredDimension", "newInstance", "LASIWidget;", "setAttribute", "LASWidgetAttribute;LNSString;LNSObject;", "()Ljava/util/List<Ljava/lang/String;>;", "getAttribute", "LASWidgetAttribute;", "inflateView", "LNSString;", "getLocationOnScreen", "[I", "getWindowVisibleDisplayFrame", "LADRect;", "offsetTopAndBottom", "offsetLeftAndRight", "setMyAttribute", "LNSString;LNSObject;", "setVisibility", "onLayoutChild", "LADView;I", "setState0", "LNSObject;", "setState1", "setState2", "setState3", "setState4", "endViewTransition", "LADView;", "Ljava/util/List<Lcom/ashera/widget/IWidget;>;", "Ljava/util/Map<Ljava/lang/String;Lcom/ashera/widget/IWidget;>;" };
  static const J2ObjcClassInfo _ASCoordinatorLayoutImpl_CoordinatorLayoutExt = { "CoordinatorLayoutExt", "com.ashera.coordinatorlayout", ptrTable, methods, fields, 7, 0x1, 39, 7, 3, -1, -1, -1, -1 };
  return &_ASCoordinatorLayoutImpl_CoordinatorLayoutExt;
}

@end

void ASCoordinatorLayoutImpl_CoordinatorLayoutExt_initWithASCoordinatorLayoutImpl_(ASCoordinatorLayoutImpl_CoordinatorLayoutExt *self, ASCoordinatorLayoutImpl *outer$) {
  self->this$0_ = outer$;
  ADXCoordinatorLayout_init(self);
  self->measureFinished_ = new_ASMeasureEvent_init();
  self->onLayoutEvent_ = new_ASOnLayoutEvent_init();
  self->mMaxWidth_ = -1;
  self->mMaxHeight_ = -1;
}

ASCoordinatorLayoutImpl_CoordinatorLayoutExt *new_ASCoordinatorLayoutImpl_CoordinatorLayoutExt_initWithASCoordinatorLayoutImpl_(ASCoordinatorLayoutImpl *outer$) {
  J2OBJC_NEW_IMPL(ASCoordinatorLayoutImpl_CoordinatorLayoutExt, initWithASCoordinatorLayoutImpl_, outer$)
}

ASCoordinatorLayoutImpl_CoordinatorLayoutExt *create_ASCoordinatorLayoutImpl_CoordinatorLayoutExt_initWithASCoordinatorLayoutImpl_(ASCoordinatorLayoutImpl *outer$) {
  J2OBJC_CREATE_IMPL(ASCoordinatorLayoutImpl_CoordinatorLayoutExt, initWithASCoordinatorLayoutImpl_, outer$)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASCoordinatorLayoutImpl_CoordinatorLayoutExt)

@implementation ASCoordinatorLayoutImpl_BottomSheetCallback

- (NSString *)getAction {
  return action_;
}

- (instancetype)initWithASIWidget:(id<ASIWidget>)w
                     withNSString:(NSString *)strValue {
  ASCoordinatorLayoutImpl_BottomSheetCallback_initWithASIWidget_withNSString_(self, w, strValue);
  return self;
}

- (instancetype)initWithASIWidget:(id<ASIWidget>)w
                     withNSString:(NSString *)strValue
                     withNSString:(NSString *)action {
  ASCoordinatorLayoutImpl_BottomSheetCallback_initWithASIWidget_withNSString_withNSString_(self, w, strValue, action);
  return self;
}

- (void)onStateChangedWithADView:(ADView *)bottomSheet
                         withInt:(int32_t)newState {
  if (action_ == nil || [action_ isEqual:@"onStateChanged"]) {
    [((id<ASIWidget>) nil_chk(w_)) syncModelFromUiToPojoWithNSString:@"onStateChanged"];
    id<JavaUtilMap> obj = [self getOnStateChangedEventObjWithADView:bottomSheet withInt:newState];
    NSString *commandName = (NSString *) cast_chk([((id<JavaUtilMap>) nil_chk(obj)) getWithId:ASEventExpressionParser_KEY_COMMAND_NAME], [NSString class]);
    NSString *commandType = (NSString *) cast_chk([obj getWithId:ASEventExpressionParser_KEY_COMMAND_TYPE], [NSString class]);
    switch (JreIndexOfStr(commandType, (id[]){ @"+" }, 1)) {
      case 0:
      if (ASEventCommandFactory_hasCommandWithNSString_(commandName)) {
        (void) [((id<ASEventCommand>) nil_chk(ASEventCommandFactory_getCommandWithNSString_(commandName))) executeCommandWithASIWidget:w_ withJavaUtilMap:obj withNSObjectArray:[IOSObjectArray newArrayWithObjects:(id[]){ bottomSheet, JavaLangInteger_valueOfWithInt_(newState) } count:2 type:NSObject_class_()]];
      }
      break;
      default:
      break;
    }
    if ([obj containsKeyWithId:@"refreshUiFromModel"]) {
      id widgets = [obj removeWithId:@"refreshUiFromModel"];
      ASViewImpl_refreshUiFromModelWithASIWidget_withId_withBoolean_(w_, widgets, true);
    }
    if ([((id<ASIWidget>) nil_chk(w_)) getModelUiToPojoEventIds] != nil) {
      ASViewImpl_refreshUiFromModelWithASIWidget_withId_withBoolean_(w_, [((id<ASIWidget>) nil_chk(w_)) getModelUiToPojoEventIds], true);
    }
    if (strValue_ != nil && ![strValue_ isEmpty] && ![((NSString *) nil_chk([((NSString *) nil_chk(strValue_)) java_trim])) java_hasPrefix:@"+"]) {
      id<ASIActivity> activity = [((id<ASIFragment>) nil_chk([((id<ASIWidget>) nil_chk(w_)) getFragment])) getRootActivity];
      if (activity != nil) {
        [activity sendEventMessageWithJavaUtilMap:obj];
      }
    }
  }
  return;
}

- (id<JavaUtilMap>)getOnStateChangedEventObjWithADView:(ADView *)bottomSheet
                                               withInt:(int32_t)newState {
  id<JavaUtilMap> obj = ASPluginInvoker_getJSONCompatMap();
  (void) [((id<JavaUtilMap>) nil_chk(obj)) putWithId:@"action" withId:@"action"];
  (void) [obj putWithId:@"eventType" withId:@"statechanged"];
  (void) [obj putWithId:@"fragmentId" withId:[((id<ASIFragment>) nil_chk([((id<ASIWidget>) nil_chk(w_)) getFragment])) getFragmentId]];
  (void) [obj putWithId:@"actionUrl" withId:[((id<ASIFragment>) nil_chk([((id<ASIWidget>) nil_chk(w_)) getFragment])) getActionUrl]];
  (void) [obj putWithId:@"namespace" withId:[((id<ASIFragment>) nil_chk([((id<ASIWidget>) nil_chk(w_)) getFragment])) getNamespace]];
  if ([((id<ASIWidget>) nil_chk(w_)) getComponentId] != nil) {
    (void) [obj putWithId:@"componentId" withId:[((id<ASIWidget>) nil_chk(w_)) getComponentId]];
  }
  ASPluginInvoker_putJSONSafeObjectIntoMapWithJavaUtilMap_withNSString_withId_(obj, @"id", [((id<ASIWidget>) nil_chk(w_)) getId]);
  ASPluginInvoker_putJSONSafeObjectIntoMapWithJavaUtilMap_withNSString_withId_(obj, @"newState", JavaLangInteger_valueOfWithInt_(newState));
  (void) ASEventExpressionParser_parseEventExpressionWithNSString_withJavaUtilMap_(strValue_, obj);
  [((id<ASIWidget>) nil_chk(w_)) updateModelToEventMapWithJavaUtilMap:obj withNSString:@"onStateChanged" withNSString:(NSString *) cast_chk([obj getWithId:ASEventExpressionParser_KEY_EVENT_ARGS], [NSString class])];
  return obj;
}

- (void)onSlideWithADView:(ADView *)bottomSheet
                withFloat:(float)slideOffset {
  if (action_ == nil || [action_ isEqual:@"onSlide"]) {
    [((id<ASIWidget>) nil_chk(w_)) syncModelFromUiToPojoWithNSString:@"onSlide"];
    id<JavaUtilMap> obj = [self getOnSlideEventObjWithADView:bottomSheet withFloat:slideOffset];
    NSString *commandName = (NSString *) cast_chk([((id<JavaUtilMap>) nil_chk(obj)) getWithId:ASEventExpressionParser_KEY_COMMAND_NAME], [NSString class]);
    NSString *commandType = (NSString *) cast_chk([obj getWithId:ASEventExpressionParser_KEY_COMMAND_TYPE], [NSString class]);
    switch (JreIndexOfStr(commandType, (id[]){ @"+" }, 1)) {
      case 0:
      if (ASEventCommandFactory_hasCommandWithNSString_(commandName)) {
        (void) [((id<ASEventCommand>) nil_chk(ASEventCommandFactory_getCommandWithNSString_(commandName))) executeCommandWithASIWidget:w_ withJavaUtilMap:obj withNSObjectArray:[IOSObjectArray newArrayWithObjects:(id[]){ bottomSheet, JavaLangFloat_valueOfWithFloat_(slideOffset) } count:2 type:NSObject_class_()]];
      }
      break;
      default:
      break;
    }
    if ([obj containsKeyWithId:@"refreshUiFromModel"]) {
      id widgets = [obj removeWithId:@"refreshUiFromModel"];
      ASViewImpl_refreshUiFromModelWithASIWidget_withId_withBoolean_(w_, widgets, true);
    }
    if ([((id<ASIWidget>) nil_chk(w_)) getModelUiToPojoEventIds] != nil) {
      ASViewImpl_refreshUiFromModelWithASIWidget_withId_withBoolean_(w_, [((id<ASIWidget>) nil_chk(w_)) getModelUiToPojoEventIds], true);
    }
    if (strValue_ != nil && ![strValue_ isEmpty] && ![((NSString *) nil_chk([((NSString *) nil_chk(strValue_)) java_trim])) java_hasPrefix:@"+"]) {
      id<ASIActivity> activity = [((id<ASIFragment>) nil_chk([((id<ASIWidget>) nil_chk(w_)) getFragment])) getRootActivity];
      if (activity != nil) {
        [activity sendEventMessageWithJavaUtilMap:obj];
      }
    }
  }
  return;
}

- (id<JavaUtilMap>)getOnSlideEventObjWithADView:(ADView *)bottomSheet
                                      withFloat:(float)slideOffset {
  id<JavaUtilMap> obj = ASPluginInvoker_getJSONCompatMap();
  (void) [((id<JavaUtilMap>) nil_chk(obj)) putWithId:@"action" withId:@"action"];
  (void) [obj putWithId:@"eventType" withId:@"slide"];
  (void) [obj putWithId:@"fragmentId" withId:[((id<ASIFragment>) nil_chk([((id<ASIWidget>) nil_chk(w_)) getFragment])) getFragmentId]];
  (void) [obj putWithId:@"actionUrl" withId:[((id<ASIFragment>) nil_chk([((id<ASIWidget>) nil_chk(w_)) getFragment])) getActionUrl]];
  (void) [obj putWithId:@"namespace" withId:[((id<ASIFragment>) nil_chk([((id<ASIWidget>) nil_chk(w_)) getFragment])) getNamespace]];
  if ([((id<ASIWidget>) nil_chk(w_)) getComponentId] != nil) {
    (void) [obj putWithId:@"componentId" withId:[((id<ASIWidget>) nil_chk(w_)) getComponentId]];
  }
  ASPluginInvoker_putJSONSafeObjectIntoMapWithJavaUtilMap_withNSString_withId_(obj, @"id", [((id<ASIWidget>) nil_chk(w_)) getId]);
  ASPluginInvoker_putJSONSafeObjectIntoMapWithJavaUtilMap_withNSString_withId_(obj, @"slideOffset", JavaLangFloat_valueOfWithFloat_(slideOffset));
  (void) ASEventExpressionParser_parseEventExpressionWithNSString_withJavaUtilMap_(strValue_, obj);
  [((id<ASIWidget>) nil_chk(w_)) updateModelToEventMapWithJavaUtilMap:obj withNSString:@"onSlide" withNSString:(NSString *) cast_chk([obj getWithId:ASEventExpressionParser_KEY_EVENT_ARGS], [NSString class])];
  return obj;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 2, 3, -1, -1, -1, -1 },
    { NULL, "LJavaUtilMap;", 0x1, 4, 3, -1, 5, -1, -1 },
    { NULL, "V", 0x1, 6, 7, -1, -1, -1, -1 },
    { NULL, "LJavaUtilMap;", 0x1, 8, 7, -1, 9, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(getAction);
  methods[1].selector = @selector(initWithASIWidget:withNSString:);
  methods[2].selector = @selector(initWithASIWidget:withNSString:withNSString:);
  methods[3].selector = @selector(onStateChangedWithADView:withInt:);
  methods[4].selector = @selector(getOnStateChangedEventObjWithADView:withInt:);
  methods[5].selector = @selector(onSlideWithADView:withFloat:);
  methods[6].selector = @selector(getOnSlideEventObjWithADView:withFloat:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "w_", "LASIWidget;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "view_", "LADView;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "strValue_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "action_", "LNSString;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LASIWidget;LNSString;", "LASIWidget;LNSString;LNSString;", "onStateChanged", "LADView;I", "getOnStateChangedEventObj", "(Lr/android/view/View;I)Ljava/util/Map<Ljava/lang/String;Ljava/lang/Object;>;", "onSlide", "LADView;F", "getOnSlideEventObj", "(Lr/android/view/View;F)Ljava/util/Map<Ljava/lang/String;Ljava/lang/Object;>;", "LASCoordinatorLayoutImpl;" };
  static const J2ObjcClassInfo _ASCoordinatorLayoutImpl_BottomSheetCallback = { "BottomSheetCallback", "com.ashera.coordinatorlayout", ptrTable, methods, fields, 7, 0xa, 7, 4, 10, -1, -1, -1, -1 };
  return &_ASCoordinatorLayoutImpl_BottomSheetCallback;
}

@end

void ASCoordinatorLayoutImpl_BottomSheetCallback_initWithASIWidget_withNSString_(ASCoordinatorLayoutImpl_BottomSheetCallback *self, id<ASIWidget> w, NSString *strValue) {
  ADXBottomSheetBehavior_BottomSheetCallback_init(self);
  self->w_ = w;
  self->strValue_ = strValue;
}

ASCoordinatorLayoutImpl_BottomSheetCallback *new_ASCoordinatorLayoutImpl_BottomSheetCallback_initWithASIWidget_withNSString_(id<ASIWidget> w, NSString *strValue) {
  J2OBJC_NEW_IMPL(ASCoordinatorLayoutImpl_BottomSheetCallback, initWithASIWidget_withNSString_, w, strValue)
}

ASCoordinatorLayoutImpl_BottomSheetCallback *create_ASCoordinatorLayoutImpl_BottomSheetCallback_initWithASIWidget_withNSString_(id<ASIWidget> w, NSString *strValue) {
  J2OBJC_CREATE_IMPL(ASCoordinatorLayoutImpl_BottomSheetCallback, initWithASIWidget_withNSString_, w, strValue)
}

void ASCoordinatorLayoutImpl_BottomSheetCallback_initWithASIWidget_withNSString_withNSString_(ASCoordinatorLayoutImpl_BottomSheetCallback *self, id<ASIWidget> w, NSString *strValue, NSString *action) {
  ADXBottomSheetBehavior_BottomSheetCallback_init(self);
  self->w_ = w;
  self->strValue_ = strValue;
  self->action_ = action;
}

ASCoordinatorLayoutImpl_BottomSheetCallback *new_ASCoordinatorLayoutImpl_BottomSheetCallback_initWithASIWidget_withNSString_withNSString_(id<ASIWidget> w, NSString *strValue, NSString *action) {
  J2OBJC_NEW_IMPL(ASCoordinatorLayoutImpl_BottomSheetCallback, initWithASIWidget_withNSString_withNSString_, w, strValue, action)
}

ASCoordinatorLayoutImpl_BottomSheetCallback *create_ASCoordinatorLayoutImpl_BottomSheetCallback_initWithASIWidget_withNSString_withNSString_(id<ASIWidget> w, NSString *strValue, NSString *action) {
  J2OBJC_CREATE_IMPL(ASCoordinatorLayoutImpl_BottomSheetCallback, initWithASIWidget_withNSString_withNSString_, w, strValue, action)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASCoordinatorLayoutImpl_BottomSheetCallback)

@implementation ASCoordinatorLayoutImpl_$Lambda$1

- (void)run {
  ASViewGroupImpl_nativeRemoveViewWithASIWidget_(val$widget_);
}

@end

void ASCoordinatorLayoutImpl_$Lambda$1_initWithASIWidget_(ASCoordinatorLayoutImpl_$Lambda$1 *self, id<ASIWidget> capture$0) {
  self->val$widget_ = capture$0;
  NSObject_init(self);
}

ASCoordinatorLayoutImpl_$Lambda$1 *new_ASCoordinatorLayoutImpl_$Lambda$1_initWithASIWidget_(id<ASIWidget> capture$0) {
  J2OBJC_NEW_IMPL(ASCoordinatorLayoutImpl_$Lambda$1, initWithASIWidget_, capture$0)
}

ASCoordinatorLayoutImpl_$Lambda$1 *create_ASCoordinatorLayoutImpl_$Lambda$1_initWithASIWidget_(id<ASIWidget> capture$0) {
  J2OBJC_CREATE_IMPL(ASCoordinatorLayoutImpl_$Lambda$1, initWithASIWidget_, capture$0)
}
