//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSCoordinatorLayoutPlugin\src\main\java\com\ashera\coordinatorlayout\CoordinatorLayoutImpl.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_CoordinatorLayoutImpl")
#ifdef RESTRICT_CoordinatorLayoutImpl
#define INCLUDE_ALL_CoordinatorLayoutImpl 0
#else
#define INCLUDE_ALL_CoordinatorLayoutImpl 1
#endif
#undef RESTRICT_CoordinatorLayoutImpl

#if !defined (ASCoordinatorLayoutImpl_) && (INCLUDE_ALL_CoordinatorLayoutImpl || defined(INCLUDE_ASCoordinatorLayoutImpl))
#define ASCoordinatorLayoutImpl_

#define RESTRICT_BaseHasWidgets 1
#define INCLUDE_ASBaseHasWidgets 1
#include "BaseHasWidgets.h"

@class ASWidgetAttribute;
@class IOSClass;
@class JavaLangBoolean;
@class JavaLangInteger;
@class NSString;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASCoordinatorLayoutImpl : ASBaseHasWidgets
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)localname;

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname;

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(int32_t)index;

- (id)asNativeWidget;

- (id)asWidget;

- (bool)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key;

- (IOSClass *)getViewClass;

- (void)invalidate;

- (void)loadAttributesWithNSString:(NSString *)localName;

- (void)nativeCreateWithJavaUtilMap:(id<JavaUtilMap>)params;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (bool)removeWithInt:(int32_t)index;

- (bool)removeWithASIWidget:(id<ASIWidget>)w;

- (void)requestLayout;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setVisibleWithBoolean:(bool)b;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCoordinatorLayoutImpl)

inline NSString *ASCoordinatorLayoutImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASCoordinatorLayoutImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASCoordinatorLayoutImpl, LOCAL_NAME, NSString *)

inline NSString *ASCoordinatorLayoutImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASCoordinatorLayoutImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASCoordinatorLayoutImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASCoordinatorLayoutImpl_init(ASCoordinatorLayoutImpl *self);

FOUNDATION_EXPORT ASCoordinatorLayoutImpl *new_ASCoordinatorLayoutImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCoordinatorLayoutImpl *create_ASCoordinatorLayoutImpl_init(void);

FOUNDATION_EXPORT void ASCoordinatorLayoutImpl_initWithNSString_(ASCoordinatorLayoutImpl *self, NSString *localname);

FOUNDATION_EXPORT ASCoordinatorLayoutImpl *new_ASCoordinatorLayoutImpl_initWithNSString_(NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCoordinatorLayoutImpl *create_ASCoordinatorLayoutImpl_initWithNSString_(NSString *localname);

FOUNDATION_EXPORT void ASCoordinatorLayoutImpl_initWithNSString_withNSString_(ASCoordinatorLayoutImpl *self, NSString *groupName, NSString *localname);

FOUNDATION_EXPORT ASCoordinatorLayoutImpl *new_ASCoordinatorLayoutImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCoordinatorLayoutImpl *create_ASCoordinatorLayoutImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname);

J2OBJC_TYPE_LITERAL_HEADER(ASCoordinatorLayoutImpl)

@compatibility_alias ComAsheraCoordinatorlayoutCoordinatorLayoutImpl ASCoordinatorLayoutImpl;


#endif

#if !defined (ASCoordinatorLayoutImpl_InsetEdge_) && (INCLUDE_ALL_CoordinatorLayoutImpl || defined(INCLUDE_ASCoordinatorLayoutImpl_InsetEdge))
#define ASCoordinatorLayoutImpl_InsetEdge_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASCoordinatorLayoutImpl_InsetEdge : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCoordinatorLayoutImpl_InsetEdge)

FOUNDATION_EXPORT void ASCoordinatorLayoutImpl_InsetEdge_init(ASCoordinatorLayoutImpl_InsetEdge *self);

FOUNDATION_EXPORT ASCoordinatorLayoutImpl_InsetEdge *new_ASCoordinatorLayoutImpl_InsetEdge_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCoordinatorLayoutImpl_InsetEdge *create_ASCoordinatorLayoutImpl_InsetEdge_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASCoordinatorLayoutImpl_InsetEdge)


#endif

#if !defined (ASCoordinatorLayoutImpl_DodgeInsetEdge_) && (INCLUDE_ALL_CoordinatorLayoutImpl || defined(INCLUDE_ASCoordinatorLayoutImpl_DodgeInsetEdge))
#define ASCoordinatorLayoutImpl_DodgeInsetEdge_

#define RESTRICT_AbstractBitFlagConverter 1
#define INCLUDE_ASAbstractBitFlagConverter 1
#include "AbstractBitFlagConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASCoordinatorLayoutImpl_DodgeInsetEdge : ASAbstractBitFlagConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCoordinatorLayoutImpl_DodgeInsetEdge)

FOUNDATION_EXPORT void ASCoordinatorLayoutImpl_DodgeInsetEdge_init(ASCoordinatorLayoutImpl_DodgeInsetEdge *self);

FOUNDATION_EXPORT ASCoordinatorLayoutImpl_DodgeInsetEdge *new_ASCoordinatorLayoutImpl_DodgeInsetEdge_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCoordinatorLayoutImpl_DodgeInsetEdge *create_ASCoordinatorLayoutImpl_DodgeInsetEdge_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASCoordinatorLayoutImpl_DodgeInsetEdge)


#endif

#if !defined (ASCoordinatorLayoutImpl_CoordinatorLayoutExt_) && (INCLUDE_ALL_CoordinatorLayoutImpl || defined(INCLUDE_ASCoordinatorLayoutImpl_CoordinatorLayoutExt))
#define ASCoordinatorLayoutImpl_CoordinatorLayoutExt_

#define RESTRICT_CoordinatorLayout 1
#define INCLUDE_ADXCoordinatorLayout 1
#include "CoordinatorLayout.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

#define RESTRICT_IMaxDimension 1
#define INCLUDE_ASIMaxDimension 1
#include "IMaxDimension.h"

@class ADRect;
@class ADView;
@class ASCoordinatorLayoutImpl;
@class ASWidgetAttribute;
@class IOSIntArray;
@class IOSObjectArray;
@class JavaLangBoolean;
@class JavaLangInteger;
@class NSString;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASCoordinatorLayoutImpl_CoordinatorLayoutExt : ADXCoordinatorLayout < ASILifeCycleDecorator, ASIMaxDimension >

#pragma mark Public

- (instancetype)initWithASCoordinatorLayoutImpl:(ASCoordinatorLayoutImpl *)outer$;

- (void)drawableStateChanged;

- (void)endViewTransitionWithADView:(ADView *)view;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation;

- (int32_t)getMaxHeight;

- (int32_t)getMaxWidth;

- (id<JavaUtilList>)getMethods;

- (id<ASIWidget>)getWidget;

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(int32_t)offset;

- (void)offsetTopAndBottomWithInt:(int32_t)offset;

- (void)onLayoutChildWithADView:(ADView *)child
                        withInt:(int32_t)layoutDirection;

- (void)onMeasureWithInt:(int32_t)widthMeasureSpec
                 withInt:(int32_t)heightMeasureSpec;

- (void)remeasure;

- (void)removeFromParent;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setMaxHeightWithInt:(int32_t)height;

- (void)setMaxWidthWithInt:(int32_t)width;

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value;

- (void)setState0WithId:(id)value;

- (void)setState1WithId:(id)value;

- (void)setState2WithId:(id)value;

- (void)setState3WithId:(id)value;

- (void)setState4WithId:(id)value;

- (void)setVisibilityWithInt:(int32_t)visibility;

- (void)state0;

- (void)state1;

- (void)state2;

- (void)state3;

- (void)state4;

- (void)stateNo;

- (void)stateYes;

- (void)updateMeasuredDimensionWithInt:(int32_t)width
                               withInt:(int32_t)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(bool)changed
                    withInt:(int32_t)l
                    withInt:(int32_t)t
                    withInt:(int32_t)r
                    withInt:(int32_t)b;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCoordinatorLayoutImpl_CoordinatorLayoutExt)

FOUNDATION_EXPORT void ASCoordinatorLayoutImpl_CoordinatorLayoutExt_initWithASCoordinatorLayoutImpl_(ASCoordinatorLayoutImpl_CoordinatorLayoutExt *self, ASCoordinatorLayoutImpl *outer$);

FOUNDATION_EXPORT ASCoordinatorLayoutImpl_CoordinatorLayoutExt *new_ASCoordinatorLayoutImpl_CoordinatorLayoutExt_initWithASCoordinatorLayoutImpl_(ASCoordinatorLayoutImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCoordinatorLayoutImpl_CoordinatorLayoutExt *create_ASCoordinatorLayoutImpl_CoordinatorLayoutExt_initWithASCoordinatorLayoutImpl_(ASCoordinatorLayoutImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASCoordinatorLayoutImpl_CoordinatorLayoutExt)


#endif

#pragma pop_macro("INCLUDE_ALL_CoordinatorLayoutImpl")
